### ISSUE TITLE
TurtleParser fails to parse boolean literal object

### ISSUE THREAD

**Issue by aschwarte10** [eclipse/rdf4j#1006]
Our unit tests have revealed a regression in the TurtleParser of the 2.3.0 Release:

It appears boolean literal objects can no longer be parsed if the "." follows the boolean string value without a space.

Minimal example trig file

```
{
     <http://www.ex.com/s> <http://www.ex.com/b> true.
}
```

Note that the TrigWriter produces exactly this output (i.e. without the space), when feeding it with above triple.

Parsing " true . "  (i.e. with the extra space) seems to work fine.

Unit tests for reproducing (including correctness tests for other literal)
(Note that these can be merged into a single test if desired)

```
@Test
	public void testParseTrig_booleanLiteral() throws Exception {
		
		// parse boolean 
		String trigBoolean = "{\n" + 
				"  <http://www.ex.com/s> <http://www.ex.com/b> true.\n" + 
				"}";
		
		Model m = Rio.parse(new StringReader(trigBoolean), "http://ex/", RDFFormat.TRIG);
		Assert.assertEquals(1, m.size());
	}
	
	@Test
	public void testParseTrig_booleanLiteral_space() throws Exception {
		
		// parse boolean 
		String trigBoolean = "{\n" + 
				"  <http://www.ex.com/s> <http://www.ex.com/b> true .\n" + 
				"}";
		
		Model m = Rio.parse(new StringReader(trigBoolean), "http://ex/", RDFFormat.TRIG);
		Assert.assertEquals(1, m.size());
	}
	
	@Test
	public void testParseTrig_intLiteral() throws Exception {
		
		// parse boolean 
		String trigBoolean = "{\n" + 
				"  <http://www.ex.com/s> <http://www.ex.com/b> 1.\n" + 
				"}";
		
		Model m = Rio.parse(new StringReader(trigBoolean), "http://ex/", RDFFormat.TRIG);
		Assert.assertEquals(1, Models.objectLiteral(m).get().intValue());
	}
	
	
	@Test
	public void testParseTrig_doubleLiteral() throws Exception {
		
		// parse boolean 
		String trigBoolean = "{\n" + 
				"  <http://www.ex.com/s> <http://www.ex.com/b> 1.2.\n" + 
				"}";
		
		Model m = Rio.parse(new StringReader(trigBoolean), "http://ex/", RDFFormat.TRIG);
		Assert.assertEquals(1.2d, Models.objectLiteral(m).get().doubleValue(), 0.01);

	}
```

Stack Trace for the failing example:

```
org.eclipse.rdf4j.rio.RDFParseException: Expected ':', found '
' [line 2]
	at org.eclipse.rdf4j.rio.helpers.RDFParserHelper.reportFatalError(RDFParserHelper.java:403)
	at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.reportFatalError(AbstractRDFParser.java:765)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.reportFatalError(TurtleParser.java:1314)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.verifyCharacterOrFail(TurtleParser.java:1149)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseQNameOrBoolean(TurtleParser.java:996)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseValue(TurtleParser.java:591)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseObject(TurtleParser.java:474)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseObjectList(TurtleParser.java:412)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.parsePredicateObjectList(TurtleParser.java:385)
	at org.eclipse.rdf4j.rio.trig.TriGParser.parseTriples(TriGParser.java:256)
	at org.eclipse.rdf4j.rio.trig.TriGParser.parseGraph(TriGParser.java:178)
	at org.eclipse.rdf4j.rio.trig.TriGParser.parseStatement(TriGParser.java:122)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:201)
	at org.eclipse.rdf4j.rio.Rio.parse(Rio.java:343)
```

**Comment by jamesrdf** [comment]
You say this is a regression, what RDF4J version did these tests pass on?

**Comment by aschwarte10** [comment]
Just had another look: It is actually not a regression - the very same parsing problem existed in 2.2.4.

However, the trig/turtle writer used a different serialization for boolean values which the parse could handle. That is why our unit tests were passing with 2.2.4

```
{
	<http://www.fluidops.com/resource/s> <http://www.fluidops.com/resource/b> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
}
```

I will edit the bug summary accordingly.
