### ISSUE TITLE
ParsedIRI.create() throws errors for perfectly valid urls

### ISSUE THREAD

**Issue by HansBrende** [eclipse/rdf4j#1017]
ParsedIRI.create("http://2017familyandconsumerscienceeduc.sched.com/")

throws:

    Exception in thread "main" java.net.URISyntaxException: Invalid IPv4 address U+66 at index 11: 
    http://2017familyandconsumerscienceeduc.sched.com/
	    at org.eclipse.rdf4j.common.net.ParsedIRI.error(ParsedIRI.java:1098)
	    at org.eclipse.rdf4j.common.net.ParsedIRI.parseHost(ParsedIRI.java:979)
	    at org.eclipse.rdf4j.common.net.ParsedIRI.parse(ParsedIRI.java:858)
	    at org.eclipse.rdf4j.common.net.ParsedIRI.<init>(ParsedIRI.java:314)

Additionally: 

    ParsedIRI.create("http://69.agendaculturel.fr/concert/")

throws: 

    Exception in thread "main" java.lang.NumberFormatException: For input string: ""
	    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	    at java.lang.Integer.parseInt(Integer.java:592)
	    at java.lang.Integer.parseInt(Integer.java:615)
	    at org.eclipse.rdf4j.common.net.ParsedIRI.parseHost(ParsedIRI.java:977)
	    at org.eclipse.rdf4j.common.net.ParsedIRI.parse(ParsedIRI.java:858)
	    at org.eclipse.rdf4j.common.net.ParsedIRI.<init>(ParsedIRI.java:314)

**Comment by barthanssens** [comment]
ParsedIRI in 2.3.x assumes  that, when an IRI starts with a number, it is an IP-address
This might also breaks (sub)domains like http://2017.rdf.org,  http://256.be, http://127.0.0.1.me :-/

**Comment by manuelfiorelli** [comment]
I encountered a seemingly related problem using the RDF4J OSGi runtime.

In this scenario, a URL to a resource inside a bundle (a JAR) may look like this: `bundle://21.0:0/META-INF/test/test.ttl`. When I use that URL as base URI for `RDFLoader`, I get the following stacktrace.
```java
java.lang.IllegalArgumentException: Invalid IPv4 address U+3A at index 13: bundle://21.0:0/META-INF/test/test.ttl
        at org.eclipse.rdf4j.common.net.ParsedIRI.create(ParsedIRI.java:266)
        at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.setBaseURI(AbstractRDFParser.java:306)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:194)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:143)
        at org.eclipse.rdf4j.repository.util.RDFLoader.loadInputStreamOrReader(RDFLoader.java:286)
        at org.eclipse.rdf4j.repository.util.RDFLoader.load(RDFLoader.java:197)
        at org.eclipse.rdf4j.repository.util.RDFLoader.load(RDFLoader.java:161)
```

The test URI seems legal to me (after reading RFC 3989), and it can be parsed by `java.net.URI`

Does the PR address this kind of problems too?

**Comment by barthanssens** [comment]
Well, I haven't tested it with RDFLoader just yet, but the PR disables the IPv4 parsing, so it should work...

**Comment by manuelfiorelli** [comment]
I'm happy to hear that this PR should fix my issue too. In fact, I didn't use the `RDFLoader` explicitly, but I discovered this issue in a perhaps more critical scenario. It seems that because of this parse exception, the `LocalRepositoryManager` (when used inside OSGi) is not able to upgrade its configuration (from using a `SystemRepository` to using textual configuration files), preventing me from opening "old" repositories. Accordingly, I'm very interested in a solution to this problem.

**Comment by manuelfiorelli** [comment]
This is the exception I obtain when the {{LocalRepositoryManager}} tries to upgrade its configuration from the use of a `SystemRepository` to the use of textual files:
```
java.lang.IllegalArgumentException: Invalid IPv4 address U+3A at index 14: bundle://159.0:1/org/eclipse/rdf4j/repository/config/system.ttl
```

Can you add a test for the URI above, in order to check this important use case?

**Comment by D063520** [comment]
Hi I get a very similar error:

Unexpected character U+23 at index 102: 
http://www.univ-paris3.fr/adminsite/webservices/export_rss.jsp?NOMBRE=10&CODE_RUBRIQUE=&LANGUE=0#KLINK#KLINK [line 10093827]

It is contained in a Wikidata dump so I would guess it is a correct uri. Can you check if this is a bug?
