### ISSUE TITLE
query with path, values and bind expression returned NullPointerException

### ISSUE THREAD

**Issue by blcham** [eclipse/rdf4j#1018]
The following query works on my rdf4jserver 2.2.2, but stopped working in version 2.3.0 :

```
SELECT *
WHERE {
        VALUES (?NAValue) {
     		(<http://null>)
		}
       BIND(IF(?NAValue != <http://null>, ?NAValue, ?notBoundVar) as ?ValidNAValue)
       { 
                ?disjClass (owl:disjointWith|^owl:disjointWith)? ?disjClass2 .
  	   }
}
```
The query itself does not make much sense because it was part of a complex query that i made as small as possible. If needed i can provide original query as well.

Within the log of the server i found:
[DEBUG] 2018-04-15 20:23:57,061 [repositories/fss-study-formgen] Error rendering view [org.eclipse.rdf4j.http.server.repository.TupleQueryResultView@295e54c0] in DispatcherServlet with name 'rdf4j-http-server'
java.lang.NullPointerException: null
[DEBUG] 2018-04-15 20:23:57,061 [ajp-nio-18009-exec-45] Could not complete request
java.lang.NullPointerException: null

In the attachment i provide full log file.
[rdf4j-server-main.log](https://github.com/eclipse/rdf4j/files/1913155/rdf4j-server-main.log)

**Comment by barthanssens** [comment]
might be related to #1017

**Comment by jeenbroekstra** [comment]
Can reproduce. Full stacktrace:
```

Exception in thread "main" java.lang.NullPointerException
	at org.eclipse.rdf4j.query.AbstractBindingSet.hashCode(AbstractBindingSet.java:58)
	at java.util.HashMap.hash(HashMap.java:339)
	at java.util.HashMap.containsKey(HashMap.java:596)
	at java.util.HashSet.contains(HashSet.java:204)
	at org.eclipse.rdf4j.common.iteration.DistinctIteration.inExcludeSet(DistinctIteration.java:70)
	at org.eclipse.rdf4j.common.iteration.DistinctIteration.accept(DistinctIteration.java:55)
	at org.eclipse.rdf4j.common.iteration.FilterIteration.findNextElement(FilterIteration.java:84)
	at org.eclipse.rdf4j.common.iteration.FilterIteration.hasNext(FilterIteration.java:47)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.JoinIterator.getNextElement(JoinIterator.java:59)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.JoinIterator.getNextElement(JoinIterator.java:1)
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:90)
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:52)
	at org.eclipse.rdf4j.common.iteration.ConvertingIteration.hasNext(ConvertingIteration.java:68)
	at org.eclipse.rdf4j.common.iteration.ConvertingIteration.hasNext(ConvertingIteration.java:68)
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:67)
	at org.eclipse.rdf4j.sail.base.SailClosingIteration.hasNext(SailClosingIteration.java:89)
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:67)
	at org.eclipse.rdf4j.sail.helpers.SailBaseIteration.hasNext(SailBaseIteration.java:48)
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:67)
	at org.eclipse.rdf4j.console.command.TupleAndGraphQueryEvaluator.evaluateTupleQuery(TupleAndGraphQueryEvaluator.java:125)
```

**Comment by jeenbroekstra** [comment]
The problem appears to be introduced by the fix for #79, which was introduced in release 2.2.4
