### ISSUE TITLE
Aggregation functions don't use non-strict comparisons when using ExtendedEvaluationStrategy

### ISSUE THREAD

**Issue by pulquero** [eclipse/rdf4j#1033]
ExtendedEvaluationStrategy doesn't pass-thru strict=false to QueryEvaluationUtil.compareLiterals() for aggregation functions (GroupIteration).

**Comment by SakshiSaini17092** [comment]
Hey, @pulquero can you please explain the issue in detail? 
An example maybe?

**Comment by pulquero** [comment]
Aggregate functions like min/max use compareLiterals. But the behaviour doesn't respect strict=true/false. So if I have some filter(?x>?y) involving dates and then try to aggregate min(?x) using extended evaluation strategy, it doesn't produce the answer you would expect.

**Comment by SakshiSaini17092** [comment]
Hey,
Pardon me if I understand the problem incorrectly, but the compare literals function takes care of strict behaviour, 

```
public static boolean compareLiterals(Literal leftLit, Literal rightLit, CompareOp operator, boolean strict)
			throws ValueExprEvaluationException {
		// type precendence:
		// - simple literal
		// - numeric
		// - xsd:boolean
		// - xsd:dateTime
		// - xsd:string
		// - RDF term (equal and unequal only)
```
like this..
Also, by aggregate functions not taking care of strict rule in ExtendedEvaluationStrategy, you mean that this function passes the strict as false always ?
```
@Override
	public Value evaluate(Compare node, BindingSet bindings)
			throws ValueExprEvaluationException, QueryEvaluationException {
		Value leftVal = evaluate(node.getLeftArg(), bindings);
		Value rightVal = evaluate(node.getRightArg(), bindings);

		// return result of non-strict comparisson.
		return BooleanLiteral.valueOf(QueryEvaluationUtil.compare(leftVal, rightVal, node.getOperator(), false));
	}
```

**Comment by SakshiSaini17092** [comment]
Or, 
the problem is with the FILTER method that it only accounts for the datatypes like string, integers, doubles?

**Comment by pulquero** [comment]
Aggregate functions always use strict=true, even if extended strategy uses strict=false for expressions. If I am using extended strategy, both aggregates and expressions should use strict=false, not just expressions.

**Comment by SakshiSaini17092** [comment]
Hey,
Please refer to my latest commit, I changed the compare method to 
`QueryEvaluationUtil.compare(v, max, Compare.CompareOp.GE, false)` 

please tell me if it is correct. 
And tell me how can I write a test for that ?

**Comment by pulquero** [comment]
The false/true should depend on whether the evaluation strategy is strict or extended.

**Comment by SakshiSaini17092** [comment]
I have added a check for `StrictEvaluationStrategy` instance, and updated the strict boolean variable according to the condition.
And on adding this check two of the test-cases present in `org.eclipse.rdf4j.query.algebra.evaluation.iterator.GroupIteratorTest.java` are failing because of incompatible comparison.
I am attaching the screenshot for the same .
![Screenshot from 2020-05-29 19-14-24](https://user-images.githubusercontent.com/36880884/83268232-eda64880-a1e2-11ea-963a-ef798b744c69.png)

**Comment by pulquero** [comment]
Do you have the full stack, not just a screenshot?

**Comment by pulquero** [comment]
And which test cases exactly?

**Comment by SakshiSaini17092** [comment]
[testcase1](https://github.com/eclipse/rdf4j/blob/055f26d3e4895010a1b7c20a2f0adc7489c1df99/core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/GroupIteratorTest.java#L76)
[testcase2](https://github.com/eclipse/rdf4j/blob/055f26d3e4895010a1b7c20a2f0adc7489c1df99/core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/GroupIteratorTest.java#L97)
This is the stack for testcase1 and testcase2 is same.

```
org.eclipse.rdf4j.query.algebra.evaluation.ValueExprEvaluationException: Only literals with compatible, ordered datatypes can be compared using <, <=, > and >= operators

	at org.eclipse.rdf4j.query.algebra.evaluation.util.QueryEvaluationUtil.compare(QueryEvaluationUtil.java:106)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.GroupIterator$MaxAggregate.processAggregate(GroupIterator.java:520)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.GroupIterator$Entry.addSolution(GroupIterator.java:327)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.GroupIterator.buildEntries(GroupIterator.java:208)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.GroupIterator.createIterator(GroupIterator.java:170)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.GroupIterator.hasNext(GroupIterator.java:129)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.GroupIteratorTest.testMaxEmptySet_DefaultGroup(GroupIteratorTest.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

**Comment by SakshiSaini17092** [comment]
After adding the compare in inline it worked. 
Can you tell me how can I test this?
