### ISSUE TITLE
Parsing NTriple with bnode fails if bnode lable contains "-"

### ISSUE THREAD

**Issue by RavinderSinghMaan** [eclipse/rdf4j#1041]
As per N triple spec https://www.w3.org/TR/n-triples/#BNodes below is allowed

> 2.4 RDF Blank Nodes
> RDF blank nodes in N-Triples are expressed as _: followed by a blank node label which is a series of name characters. The characters in the label are built upon PN_CHARS_BASE, liberalized as follows:
> 
> The characters _ and [0-9] may appear anywhere in a blank node label.
> The character . may appear anywhere except the first or last character.
> The characters -, U+00B7, U+0300 to U+036F and U+203F to U+2040 are permitted anywhere except the first character. 
> 

But if I try to parse below 
```
Rio.parse(new StringReader("<http://example.org/people/alice> <http://www.perceive.net/schemas/relationship/enemyOf> _:genid-7047e9358ae44bd190d9f22a25762c2b-b1 ."), "", RDFFormat.NTRIPLES)
```
it fails with exception
```
org.eclipse.rdf4j.rio.RDFParseException: Expected '.', found: - [line 1]

	at org.eclipse.rdf4j.rio.helpers.RDFParserHelper.reportError(RDFParserHelper.java:322)
	at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.reportError(AbstractRDFParser.java:684)
	at org.eclipse.rdf4j.rio.ntriples.NTriplesParser.reportError(NTriplesParser.java:636)
	at org.eclipse.rdf4j.rio.ntriples.NTriplesParser.parseTriple(NTriplesParser.java:298)
	at org.eclipse.rdf4j.rio.ntriples.NTriplesParser.parse(NTriplesParser.java:177)
	at org.eclipse.rdf4j.rio.Rio.parse(Rio.java:343)
	at org.eclipse.rdf4j.rio.Rio.parse(Rio.java:254)
```

**Comment by RavinderSinghMaan** [comment]
@jeenbroekstra any thoughts on this? If you guys agree that parser should allow extra characters mentioned in spec then I can try to create a patch for it.

**Comment by jeenbroekstra** [comment]
Yeah that seems like a bug. A patch would be most welcome! Can you add a test case as well so we don't regress? Thanks!

**Comment by RavinderSinghMaan** [comment]
@jeenbroekstra below are the test cases and code change required to fix it. If it looks ok then I can signup and do proper PR etc.
```
   @Test
    public void testBlankNodeIdentifiersWithUnderScore()
            throws Exception
    {
        //The characters _ and [0-9] may appear anywhere in a blank node label.
        RDFParser ntriplesParser = new NTriplesParser();
        Model model = new LinkedHashModel();
        ntriplesParser.setRDFHandler(new StatementCollector(model));
        ntriplesParser.parse(new StringReader("_:123_ <urn:test:predicate> _:_456 ."), NTRIPLES_TEST_URL);

        assertEquals(1, model.size());
        assertEquals(1, model.subjects().size());
        assertEquals(1, model.predicates().size());
        assertEquals(1, model.objects().size());
    }

    @Test
    public void testBlankNodeIdentifiersWithDot()
            throws Exception
    {
        //The character . may appear anywhere except the first or last character.
        RDFParser ntriplesParser = new NTriplesParser();
        Model model = new LinkedHashModel();
        ntriplesParser.setRDFHandler(new StatementCollector(model));
        ntriplesParser.parse(new StringReader("_:1.23 <urn:test:predicate> _:45.6 ."), NTRIPLES_TEST_URL);

        assertEquals(1, model.size());
        assertEquals(1, model.subjects().size());
        assertEquals(1, model.predicates().size());
        assertEquals(1, model.objects().size());
    }

    @Test
    public void testBlankNodeIdentifiersWithDotAsFirstCahracter()
            throws Exception
    {
        //The character . may appear anywhere except the first or last character.
        RDFParser ntriplesParser = new NTriplesParser();
        Model model = new LinkedHashModel();
        ntriplesParser.setRDFHandler(new StatementCollector(model));
        try {
            ntriplesParser.parse(new StringReader("_:123 <urn:test:predicate> _:.456 ."), NTRIPLES_TEST_URL);
            fail("Should have failed to parse invalid N-Triples bnode with '.' at the begining of the bnode label");
        } catch (Exception e) {
        }

        assertEquals(0, model.size());
        assertEquals(0, model.subjects().size());
        assertEquals(0, model.predicates().size());
        assertEquals(0, model.objects().size());
    }

    @Test(expected = RDFParseException.class)
    public void testBlankNodeIdentifiersWithDotAsLastCahracter()
            throws Exception
    {
        //The character . may appear anywhere except the first or last character.
        RDFParser ntriplesParser = new NTriplesParser();
        Model model = new LinkedHashModel();
        ntriplesParser.setRDFHandler(new StatementCollector(model));
        try {
            ntriplesParser.parse(new StringReader("_:123 <urn:test:predicate> _:456. ."), NTRIPLES_TEST_URL);
        } catch (RDFParseException e) {
            assertEquals(0, model.size());
            assertEquals(0, model.subjects().size());
            assertEquals(0, model.predicates().size());
            assertEquals(0, model.objects().size());
            throw e;
        }
        fail("Should have failed to parse invalid N-Triples bnode with '.' at the end of the bnode label");
    }

    @Test
    public void testBlankNodeIdentifiersWithOtherCharacters()
            throws Exception
    {
        //The characters -, U+00B7, U+0300 to U+036F and U+203F to U+2040 are permitted anywhere except the first character.
        List<Character> charactersList = new ArrayList<>();
        charactersList.add('-');
        charactersList.add('\u00B7');
        charactersList.add('\u0300');
        charactersList.add('\u036F');
        charactersList.add('\u0301');
        charactersList.add('\u203F');

        for(int i = 0;i < charactersList.size(); i++) {
            Character character = charactersList.get(i);
            RDFParser ntriplesParser = new NTriplesParser();
            Model model = new LinkedHashModel();
            ntriplesParser.setRDFHandler(new StatementCollector(model));

            String triple = "<urn:test:subject> <urn:test:predicate> _:1" + character + " . ";
            try {
                ntriplesParser.parse(new StringReader(triple), NTRIPLES_TEST_URL);
            } catch (Exception e) {
                fail(" Failed to parse triple : "+triple+" containing character '"+character+"' at index "+i+" in charactersList" );
            }

            assertEquals("Should parse '"+character+"'", 1, model.size());
            assertEquals("Should have subject when triple has character : '"+character+"'", 1, model.subjects().size());
            assertEquals("Should have predicate when triple has character : '"+character+"'",1, model.predicates().size());
            assertEquals("Should have object when triple has character : '"+character+"'",1, model.objects().size());
        }

    }

    @Test(expected = RDFParseException.class)
    public void testBlankNodeIdentifiersWithOtherCharactersAsFirstCharacter()
            throws Exception
    {
        //The characters -, U+00B7, U+0300 to U+036F and U+203F to U+2040 are permitted anywhere except the first character.
        List<Character> charactersList = new ArrayList<>();
        charactersList.add('-');
        charactersList.add('\u00B7');
        charactersList.add('\u0300');
        charactersList.add('\u036F');
        charactersList.add('\u0301');
        charactersList.add('\u203F');

        for(Character character:charactersList) {
            RDFParser ntriplesParser = new NTriplesParser();
            Model model = new LinkedHashModel();
            ntriplesParser.setRDFHandler(new StatementCollector(model));

            try {
                ntriplesParser.parse(new StringReader("<urn:test:subject> <urn:test:predicate> _:"+character+"1 . "), NTRIPLES_TEST_URL);
            } catch (RDFParseException e) {
                assertEquals(0, model.size());
                assertEquals(0, model.subjects().size());
                assertEquals(0, model.predicates().size());
                assertEquals(0, model.objects().size());
                throw e;
            }
            fail("Should have failed to parse invalid N-Triples bnode with '"+character+"' at the begining of the bnode label");
        }
    }
```

And to fix it adding in NTriplesUtil.java

```
    /**
     * Checks whether the supplied character is in list of liberal characters according to the N-Triples specification.
     *
     */
    public static boolean isInLiberalCharacterList(int c) {
        return isUnderscore(c) || isDot(c) || c == 45 || c == 183 || (c >= 768 && c <= 879) || c == 8255 || c == 8256;
    }

    /**
     * Checks whether the supplied character is Underscore.
     *
     */
    public static boolean isUnderscore(int c) {
        return c == 95;
    }

    /**
     * Checks whether the supplied character is Dot '.'.
     *
     */
    public static boolean isDot(int c) {
        return c == 46;
    }

    /**

```

in NTriplesParser.java
```
	protected int parseNodeID(int c, StringBuilder name)
		throws IOException, RDFParseException
	{
		if (c != '_') {
			reportError("Supplied char should be a '_', is: " + new String(Character.toChars(c)),
					NTriplesParserSettings.FAIL_ON_NTRIPLES_INVALID_LINES);
		}

		c = readCodePoint();
		if (c == -1) {
			throwEOFException();
		}
		else if (c != ':') {
			reportError("Expected ':', found: " + new String(Character.toChars(c)),
					NTriplesParserSettings.FAIL_ON_NTRIPLES_INVALID_LINES);
		}

		c = readCodePoint();
		if (c == -1) {
			throwEOFException();
		}
		else if (!NTriplesUtil.isLetterOrNumber(c) && !NTriplesUtil.isUnderscore(c)) {
			reportError("Expected a letter or number, found: " + new String(Character.toChars(c)),
					NTriplesParserSettings.FAIL_ON_NTRIPLES_INVALID_LINES);
		}
		name.append(Character.toChars(c));

		// Read all following letter and numbers, they are part of the name
		c = readCodePoint();
		int last = -1;
		while (c != -1 && (NTriplesUtil.isLetterOrNumber(c) || NTriplesUtil.isInLiberalCharacterList(c))) {
			name.append(Character.toChars(c));
			last = c;
			c = readCodePoint();
		}

		if (NTriplesUtil.isDot(last)) {
			reportError("Expected a letter or number, found: " + new String(Character.toChars(c)),
					NTriplesParserSettings.FAIL_ON_NTRIPLES_INVALID_LINES);
		}

		return c;
	}
```

**Comment by jeenbroekstra** [comment]
Looks good to me. But it will be easier to review in an actual PR (also because then I can check out the code and run it locally, if necessary).

**Comment by jeenbroekstra** [comment]
If you need a hand setting up a PR just sing out, happy to talk you through it!

**Comment by RavinderSinghMaan** [comment]
cool thanks for quick check I was about to raise a PR. But Just noticed a small problem and it seems like a conflict in spec. As per existing test below is valid and should parse

```
# Space is optional before final .

<http://example.org/resource15> <http://example.org/property> _:anon.
```

But as per liberalized spec 
> The character . may appear anywhere except the first or last character 

How do we want to treat dot? Can we do below?
- Raise parsing exception If dot is first or last character for subject or dot is first character of object.

However it means we need to pass a flag to parseNodeId method or create 2 methods. It seems that from performance perspective second will be better. What do you guys think?

**Comment by jeenbroekstra** [comment]
In the above existing test, the final dot is not part of the URI/blank node, but is the full-stop at the end of the triple. The test is there because separating the resource id and the end-of-triple fullstop with a whitespace is optional. So there's no conflict, we simply need to ensure that _if_ this situation occurs the parser does not treat the fullstop as part of the resource id.

**Comment by jeenbroekstra** [comment]
I would suggest that the way to treat this is to have parseNodeId not raise an exception on encountering a fullstop at the end, ever, and just let the context handle it. From the top of my head, if the node id is in the subject/predicate position, the parser will next jump to parse the predicate/object, which should then fail on an unexpected full stop.

**Comment by RavinderSinghMaan** [comment]
Sorry I think I was not very clear. What I was trying to say is same as you suggest. But was not sure about the best way to do it? Because `.` is allowed in the middle how can we determine without reading ahead in the stream that it is actully in the middle? Do we add a buffer which keeps record of previous and last character?

For example let us take 2 cases. 

1.  This is valid node name
```
<http://example.org/resource> <http://example.org/property> _:a.b
```
2. This is valid and full stop at the end is indicating end-of-triple
```
<http://example.org/resource> <http://example.org/property> _:ab.
``` 

At the moment loop to read codePoints in parseNodeID method is as below. As only letterOrNumber is allowed it workds quite well without any need to track previous or last codePoint.

```
		c = readCodePoint();
		while (c != -1 && NTriplesUtil.isLetterOrNumber(c)) {
			name.append(Character.toChars(c));
			c = readCodePoint();
		}
```

But when we allow `.` in the middle of the name i.e. `_:a.b` and `.` at the end is treated as end-of-triple then the above loop will require to check that there is another valid codePoint after `.` before it goes in the nodeName. Feels like we will end up some sort buffer(an instance variable or array) to implement this check. What do you think?

On separate note, As rest of the test cases are passing shall I raise PR for scenarios excluding `.` or you prefer all in one go?

**Comment by jeenbroekstra** [comment]
Ah I see. You don't need a separate buffer really, I think. You can use a similar trick to what the TurtleParser also does in these cases. It has a `peekCodePoint` method that looks like this:

	protected int peekCodePoint() throws IOException {
		int result = readCodePoint();
		unread(result);
		return result;
	}

	protected void unread(int codePoint) throws IOException {
		if (codePoint != -1) {
			if (Character.isSupplementaryCodePoint(codePoint)) {
				final char[] surrogatePair = Character.toChars(codePoint);
				reader.unread(surrogatePair);
			} else {
				reader.unread(codePoint);
			}
		}
	}

You should be able to reuse something similar in `NTriplesParser` to look at the next character without advancing the reader.

**Comment by jeenbroekstra** [comment]
As for the PR: just put it up, we can review and continue discussion on further tweaks there, and you can also add additional commits to the PR later if necessary :)

**Comment by RavinderSinghMaan** [comment]
@jeenbroekstra wonderfull!

I was thinking in same direction but did not realize that something must have been already done in other parser. Thanks for the pointers. I have raised PR for it.
