### ISSUE TITLE
create RIO command-line tool

### ISSUE THREAD

**Issue by VladimirAlexiev** [eclipse/rdf4j#1066]
Trying to load https://permid.org/sfiles/bulkDownload/OpenPermID-bulk-organization-20180805_070415.ttl.gz to GraphDB (need free registration at permid.org to obtain this file).
I get this exception:
```
[ERROR] 2018-08-08 12:02:17,230 [import-task-permid-1 | c.o.f.i.FileImportRunnableTask] Could not import file
java.lang.StringIndexOutOfBoundsException: String index out of range: 21
at java.lang.String.codePointAt(String.java:687)
at org.eclipse.rdf4j.common.net.ParsedIRI.error(ParsedIRI.java:1139)
at org.eclipse.rdf4j.common.net.ParsedIRI.parseHost(ParsedIRI.java:997)
at org.eclipse.rdf4j.common.net.ParsedIRI.parse(ParsedIRI.java:858)
```
Ok, so I'll use `jena riot` to validate it.
Please create an `rdf4j rio` command-line utility like RIOT, so I can validate with RIO.

**Comment by barthanssens** [comment]
Sounds like an issue for https://github.com/eclipse/rdf4j-tools subproject.

There is a verify command in the console tool, but what is really missing (IMHO)  is a way to run a command/script from the command line (e.g. Console -x verify <file>) and exit with an exit code (so it could be used in a batch script, instead of interactively)

**Comment by jeenbroekstra** [comment]
@barthanssens you can kinda do that though:

    $ echo verify test.ttl | ./console.sh 

but I agree command line switches would be useful.

**Comment by jeenbroekstra** [comment]
We're kinda conflating issues here though. I'll keep this issue to focus on the parser bug reported, I'll add a separate feature ticket to the tools project for command line switches to do actions like verification.

**Comment by jeenbroekstra** [comment]
I can reproduce this issue in the latest milestone.

**Comment by VladimirAlexiev** [comment]
I didn't know about console verify, thanks! Does it say the line number? 

Riot reports about 50 malformed web URLs (see graphdb jira), I fixed them with a perl script but no cigar

**Comment by jeenbroekstra** [comment]
The problem is specific to an IRI with in IP address, but no path: <http://178.62.246.130> . There is a bug in ParsedIRI that expects either a port number or a path behind this. I'm working on a fix.

**Comment by jeenbroekstra** [comment]
Btw the line on which this first occurs in this file is 6360967. Unfortunately the console also doesn't report this, due to a related error.

**Comment by jeenbroekstra** [comment]
PR up for a fix. I have verified that with this fix in place, the file parses without issues (it doesn't even require disable URI checking).
