### ISSUE TITLE
Upgrade Guava dependency

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1097]
The projects still use Guava 18.0, which is getting a bit old (released 4,5 years ago), latest version is 26.0
Some code changes are to be expected + CQ

- [x] [CQ 22547](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22547) (29.0-jre)

**Comment by barthanssens** [comment]
Probably safer to upgrade to, say, 22.0 first and when that works out as expected, upgrade to e.g. 26 in a release after that (instead of going straight to 26)

**Comment by barthanssens** [comment]
- [ ]  CQ18581(PB), v23.5-jre

**Comment by barthanssens** [comment]
japicmp in storage has a dependency on guava 18 :-/

**Comment by barthanssens** [comment]
Currently an issue with solr

```
 testPredicateLuceneQueries(org.eclipse.rdf4j.sail.solr.SolrSailTest)  Time elapsed: 0.465 s  <<< ERROR!
java.lang.NoSuchMethodError: com.google.common.base.Objects.firstNonNull(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
        at org.apache.solr.handler.component.HighlightComponent.prepare(HighlightComponent.java:118)
        at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:272)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:199)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:2541)
        at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:191)
        at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:194)
        at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:942)
        at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:957)
        at org.eclipse.rdf4j.sail.solr.SolrIndex.search(SolrIndex.java:563)
        at org.eclipse.rdf4j.sail.solr.SolrIndex.query(SolrIndex.java:317)
        at org.eclipse.rdf4j.sail.lucene.AbstractSearchIndex.evaluateQuery(AbstractSearchIndex.java:470)
        at org.eclipse.rdf4j.sail.lucene.AbstractSearchIndex.evaluate(AbstractSearchIndex.java:433)
        at org.eclipse.rdf4j.sail.lucene.LuceneSailConnection.evaluateLuceneQueries(LuceneSailConnection.java:376)
        at org.eclipse.rdf4j.sail.lucene.LuceneSailConnection.evaluateInternal(LuceneSailConnection.java:320)
        at org.eclipse.rdf4j.sail.lucene.LuceneSailConnection.evaluate(LuceneSailConnection.java:287)
        at org.eclipse.rdf4j.repository.sail.SailTupleQuery.evaluate(SailTupleQuery.java:52)
        at org.eclipse.rdf4j.sail.lucene.AbstractLuceneSailTest.evaluate(AbstractLuceneSailTest.java:401)
        at org.eclipse.rdf4j.sail.lucene.AbstractLuceneSailTest.testPredicateLuceneQueries(AbstractLuceneSailTest.java:528)
```

**Comment by barthanssens** [comment]
Seems like Solr 7.5 is not compatible with guava-jre +18 (8.1 is)

**Comment by barthanssens** [comment]
More precisely, using newer versions breaks org.eclipse.rdf4j.sail.solr.SolrSailIndexedPropertiesTest:

java.lang.NoSuchMethodError: java.lang.Object com.google.common.base.Objects.firstNonNull(java.lang.Object, java.lang.Object)

**Comment by jeenbroekstra** [comment]
Let's start making this a bit higher of a priority. Anything in particular I can do to help move this forward?

**Comment by jeenbroekstra** [comment]
@barthanssens I've put up a PR with a version bump, overriding for solr testing. This seems to work. What do you think?

**Comment by barthanssens** [comment]
LGTM !

**Comment by jeenbroekstra** [comment]
Of course the build failed 2 minutes after I said "looks good"....

**Comment by barthanssens** [comment]
@jeenbroekstra I've filed a CQ for 29.0 

(if needed, we could piggyback on an existing CQ for 28.2)

**Comment by jeenbroekstra** [comment]
- [ ] [CQ 22547](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22547)

Thanks!

**Comment by barthanssens** [comment]
@jeenbroekstra  CQ got approved
