### ISSUE TITLE
Server and Workbench heavily depend on the Logback Classic implementation

### ISSUE THREAD

**Issue by abrokenjester** [eclipse/rdf4j#1106]
_From @KMax on September 14, 2018 9:17_

I run the server and workbench on Apache Tomcat 9.0.8.0. Since Tomcat natively supports the JUL logging, I want to use it to configure logging of the server, workbench and my custom SAIL from a single place. But unfortunately, it looks like the server and workbench heavily depend on the logback-classic, therefore I face the following exception:

```
java.lang.ClassCastException: org.slf4j.impl.JDK14LoggerFactory cannot be cast to ch.qos.logback.classic.LoggerContext
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:834)
 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537)
 	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:667)
 	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:633)
 	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:681)
 	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:552)
 	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:493)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
 	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
 	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1124)
 	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1079)
 	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:971)
 	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4813)
 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5125)
 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:742)
 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:718)
 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:703)
 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:986)
 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1858)
 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
 	at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:772)
 	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:426)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1585)
 	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:308)
 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
 	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:424)
 	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:367)
 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:966)
 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:839)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1427)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1417)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:943)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:258)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:770)
 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:682)
 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350)
 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)
Caused by: java.lang.ClassCastException: org.slf4j.impl.JDK14LoggerFactory cannot be cast to ch.qos.logback.classic.LoggerContext
 	at org.eclipse.rdf4j.common.app.logging.logback.LogbackConfiguration.load(LogbackConfiguration.java:70)
 	at org.eclipse.rdf4j.common.app.logging.logback.LogbackConfiguration.init(LogbackConfiguration.java:50)
 	at org.eclipse.rdf4j.common.app.AppConfiguration.init(AppConfiguration.java:162)
 	at org.eclipse.rdf4j.common.app.AppConfiguration.init(AppConfiguration.java:145)
 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1706)
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1645)
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
 	... 60 more
```

Here is SLF4J output:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/tomcat/webapps/server/WEB-INF/lib/slf4j-jdk14-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/tomcat/webapps/server/WEB-INF/lib/logback-classic-1.1.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
```

What is the reason to tightly use logback instead of SLF4J API?

_Copied from original issue: eclipse/rdf4j-tools#75_

**Comment by barthanssens** [comment]
On a similar note, the Console also assumes that Logback is used (one can change console log level with  `set log=`  - whether this is useful / needed is debatable I guess - and setting a log level isn't part of the high-level SLF4J API, requiring an implementation like Logback or Apache Commons SimpleLog instead)
