### ISSUE TITLE
Can't lookup added Statement in SPARQLRepository transaction

### ISSUE THREAD

**Issue by daltontc** [eclipse/rdf4j#1248]
I wrote a simple application using a SPARQLRepository to connect to a local rdf4j-server. In it, I want to start a transaction, add a statement, and try to retrieve that statement during the transaction, then commit. See below:

```
    public static void main(String args[]) {
        String queryEndpoint = "http://127.0.0.1:8080/rdf4j-server/repositories/system";
        String updateEndpoint = "http://127.0.0.1:8080/rdf4j-server/repositories/system/statements";
        SPARQLRepository sparqlRepository = new SPARQLRepository(queryEndpoint, updateEndpoint);
        sparqlRepository.enableQuadMode(true);
        sparqlRepository.initialize();
        RepositoryConnection conn = sparqlRepository.getConnection();

        ValueFactory vf = SimpleValueFactory.getInstance();
        Statement a = vf.createStatement(vf.createIRI("urn:subject1"), vf.createIRI("urn:predicate1"), vf.createIRI("urn:object1"));

        conn.begin();
        conn.add(a);
        RepositoryResult<Statement> iterator = conn.getStatements(vf.createIRI("urn:subject1"), null, null);
        Statement aRepo = iterator.next();
        System.out.println(aRepo.toString());
        conn.commit();
    }
```
I get an exception due to an empty iterator:
```
Exception in thread "main" java.util.NoSuchElementException
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.next(LookAheadIteration.java:74)
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.next(IterationWrapper.java:91)
	at org.eclipse.rdf4j.common.iteration.ConvertingIteration.next(ConvertingIteration.java:91)
	at org.eclipse.rdf4j.common.iteration.ExceptionConvertingIteration.next(ExceptionConvertingIteration.java:97)
	at org.eclipse.rdf4j.repository.RepositoryResult.next(RepositoryResult.java:58)
	at connection.main(connection.java:23)

Process finished with exit code 1
```

I would expect to be able to retrieve the statement that I just added. When I do the same operation with a NativeStore I do not have the same issue. I assume this is a bug in the SPARQLRepository?

**Comment by barthanssens** [comment]
I was able to replicate the problem, using RDF4J 2.4.2 (to remote server with a memory store)

**Comment by damyan-ognyanov** [comment]
system repository uses a `MemoryStore` as a `Sail` so in order to see the changes during open transaction, initiate it with `begin(IsolationLevels.NONE)` instead of `begin()` which uses defaut level which is `IsolationLevels.SNAPSHOT_READ`

**Comment by daltontc** [comment]
@damyan-ognyanov Is that a workaround until a bugfix happens? I would expect operations on a local native store and a remote native store to behave the same when doing a default `begin()` regardless of the connection method (http, sparql). Is this a bad assumption? Perhaps I wasn't clear in the initial ticket that all connections are to a native store.

```
import org.eclipse.rdf4j.model.Statement;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.repository.RepositoryConnection;
import org.eclipse.rdf4j.repository.RepositoryResult;
import org.eclipse.rdf4j.repository.http.HTTPRepository;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.repository.sparql.SPARQLRepository;
import org.eclipse.rdf4j.sail.nativerdf.NativeStore;

import java.io.File;
import java.util.NoSuchElementException;

public class connection {
    public static void main(String args[]) {
        String serverUrl = "http://127.0.0.1:8080/rdf4j-server";
        String queryEndpoint = "http://127.0.0.1:8080/rdf4j-server/repositories/system";
        String updateEndpoint = "http://127.0.0.1:8080/rdf4j-server/repositories/system/statements";

        ValueFactory vf = SimpleValueFactory.getInstance();
        Statement a = vf.createStatement(vf.createIRI("urn:subject1"), vf.createIRI("urn:predicate1"), vf.createIRI("urn:object1"));

        NativeStore ns = new NativeStore();
        ns.setDataDir(new File("/Users/tomdalton/merck/")); //TODO:Change
        SailRepository sr = new SailRepository(ns);
        sr.initialize();

        RepositoryConnection localConn = sr.getConnection();
        System.out.println("\n\nConnecting to local repo.");
        localConn.begin();
        System.out.println("Writing to local repo.");
        localConn.add(a);
        System.out.println("Reading from local repo.");
        RepositoryResult<Statement> iterator = localConn.getStatements(vf.createIRI("urn:subject1"), null, null);
        Statement localStatement = iterator.next();
        System.out.println(localStatement.toString());
        localConn.commit();
        System.out.println("Committed to local repo.");

        HTTPRepository httpRepository = new HTTPRepository(serverUrl, "system");
        httpRepository.initialize();
        RepositoryConnection httpConn = httpRepository.getConnection();
        System.out.println("\n\nConnecting to HTTP repo.");
        httpConn.begin();
        System.out.println("Writing to HTTP repo.");
        httpConn.add(a);
        System.out.println("Reading from HTTP repo.");
        RepositoryResult<Statement> httpIterator = httpConn.getStatements(vf.createIRI("urn:subject1"), null, null);
        Statement httpStatement = httpIterator.next();
        System.out.println(httpStatement.toString());
        httpConn.commit();
        System.out.println("Committed to HTTP repo.");
        httpConn.clear();
        System.out.println("Clearing HTTP repo.");

        SPARQLRepository sparqlRepository = new SPARQLRepository(queryEndpoint, updateEndpoint);
        sparqlRepository.enableQuadMode(true);
        sparqlRepository.initialize();

        RepositoryConnection sparqlConn = sparqlRepository.getConnection();
        System.out.println("\n\nConnecting to SPARQL repo.");
        sparqlConn.begin();
        System.out.println("Writing to SPARQL repo.");
        sparqlConn.add(a);
        System.out.println("Reading from SPARQL repo.");
        RepositoryResult<Statement> sparqlIterator = sparqlConn.getStatements(vf.createIRI("urn:subject1"), null, null);
        try {
            Statement sparqlStatement = sparqlIterator.next();
            System.out.println(sparqlStatement.toString());
        } catch (NoSuchElementException nse) {
            System.out.println("ERROR getting iterator: " + nse.toString());
            nse.printStackTrace();
        }
        sparqlConn.commit();
        System.out.println("Committed to HTTP repo.");
        sparqlConn.clear();
        System.out.println("Clearing SPARQL repo.");
    }
}
```

This test shows that the SPARQL connections iterator is not getting populated for a read. If i changed the connection to a `sparqlConn.begin(IsolationLevels.SNAPSHOT_READ);`, that does not fix the issue either.

**Comment by damyan-ognyanov** [comment]
I see... looking at the SPARQLRepository class, it seems to be designed to serve as a simple proxy allowing one to work with any generic sparql endpoints. 

There is no notion of 'transaction' in SPARQL specification nor anything that could be associated with such, e.g. things like, begin/commit/rollback/isolation-levels etc.  

The code simply start building sparql updates at begin() through the invocations of the rdf4j api methods like add/remove/clear and finally send these at commit or alternatively, drop them on rollback. 
Queries are evaluated as soon as the respective evaluate() methods are invoked, without forcing the execution of the collected update expressions (if any) within current connection.  

If the collected update expressions are executed first, before evaluating the query/getStatements request then there is no way to revoke these so to provide a plausable rollback() functionality, which is essential ...

Suggest to stick with the HTTP versions of the rdf4j api when working with remote rdf4j servers and your use case require a particular isolation level support ...

**Comment by jeenbroekstra** [comment]
As @damyan-ognyanov suggested, this is not exactly a bug: SPARQLRepository has no support for transaction isolation (because the SPARQL protocol lacks this support). If you need transaction-safe operations on a remote rdf4j repository, you should use HTTPRepository as the client instead.
