### ISSUE TITLE
Query results with relative IRIs crash query

### ISSUE THREAD

**Issue by reckart** [eclipse/rdf4j#1300]
I run this query 

```
SELECT DISTINCT ?s ( MIN( ?lc ) AS ?l )
WHERE { { ?s <http://www.w3.org/2000/01/rdf-schema#label> "wine"@en . } UNION { ?s <http://www.w3.org/2000/01/rdf-schema#label> "wine"@en . }
OPTIONAL { ?s <http://www.w3.org/2000/01/rdf-schema#label> ?lc .
FILTER ( LANGMATCHES( LANG( ?lc ), "en" ) ) } }
GROUP BY ?s
LIMIT 1000
```

against http://dbpedia.org/sparql

and get this back:

```
<sparql xmlns="http://www.w3.org/2005/sparql-results#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/sw/DataAccess/rf1/result2.xsd">
 <head>
  <variable name="s"/>
  <variable name="l"/>
 </head>
 <results distinct="false" ordered="true">
  <result>
   <binding name="s"><uri>http://dbpedia.org/property/wine</uri></binding>
   <binding name="l"><literal xml:lang="en">wine</literal></binding>
  </result>
  <result>
   <binding name="s"><uri>#Wine</uri></binding>
   <binding name="l"><literal xml:lang="en">wine</literal></binding>
  </result>
  <result>
   <binding name="s"><uri>http://www.wikidata.org/entity/Q3014419</uri></binding>
   <binding name="l"><literal xml:lang="en">wine</literal></binding>
  </result>
  <result>
   <binding name="s"><uri>http://dbpedia.org/ontology/Wine</uri></binding>
   <binding name="l"><literal xml:lang="en">wine</literal></binding>
  </result>
  <result>
   <binding name="s"><uri>#WN30Word-wine</uri></binding>
   <binding name="l"><literal xml:lang="en">wine</literal></binding>
  </result>
  <result>
   <binding name="s"><uri>http://www.wikidata.org/entity/Q282</uri></binding>
   <binding name="l"><literal xml:lang="en">wine</literal></binding>
  </result>
 </results>
</sparql>
```

This result contains some items with a relative IRI, e.g. `#Wine` and `#WN30Word-wine`.

This causes the entire query to crash with 

```
Caused by: java.lang.IllegalArgumentException: Not a valid (absolute) IRI: #Wine
	at org.eclipse.rdf4j.model.impl.SimpleIRI.setIRIString(SimpleIRI.java:76)
	at org.eclipse.rdf4j.model.impl.SimpleIRI.<init>(SimpleIRI.java:65)
	at org.eclipse.rdf4j.model.impl.AbstractValueFactory.createIRI(AbstractValueFactory.java:88)
	at org.eclipse.rdf4j.query.resultio.sparqlxml.SPARQLResultsSAXParser.startTag(SPARQLResultsSAXParser.java:111)
	at org.eclipse.rdf4j.common.xml.SimpleSAXParser$SimpleSAXDefaultHandler.endElement(SimpleSAXParser.java:305)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.eclipse.rdf4j.common.xml.SimpleSAXParser.parse(SimpleSAXParser.java:207)
	at org.eclipse.rdf4j.common.xml.SimpleSAXParser.parse(SimpleSAXParser.java:186)
	at org.eclipse.rdf4j.query.resultio.sparqlxml.AbstractSPARQLXMLParser.parseQueryResultInternal(AbstractSPARQLXMLParser.java:211)
	... 10 more
```

I didn't find a way to specify a base IRI against which to resolve relative IRIs when parsing query results.

I also didn't find any option allowing to skip problematic results when parsing the response.

**Comment by jeenbroekstra** [comment]
I have never seen that before - a SPARQL XML query result with relative URIs in it. 

That is actually not standards-compliant and the bug is not in RDF4J, but in DBPedia for producing such a result. The [result format recommendation](https://www.w3.org/TR/rdf-sparql-XMLres/) has no provisions for relative URIs, the endpoint should take care to resolve these relative references to full URIs before serializing. 

That being said, we could provide an option in the query results parser to skip malformed results without completely crashing out.

**Comment by jeenbroekstra** [comment]
As an aside: I can not reproduce the issue. If I run your query in the query editor at http://dbpedia.org/sparql, using XML as the result format, I get this:

```
<sparql xmlns="http://www.w3.org/2005/sparql-results#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/sw/DataAccess/rf1/result2.xsd">
 <head>
  <variable name="s"/>
  <variable name="l"/>
 </head>
 <results distinct="false" ordered="true">
  <result>
   <binding name="s"><uri>http://dbpedia.org/property/wine</uri></binding>
   <binding name="l"><literal xml:lang="en">wine</literal></binding>
  </result>
  <result>
   <binding name="s"><uri>http://dbpedia.org/ontology/Wine</uri></binding>
   <binding name="l"><literal xml:lang="en">wine</literal></binding>
  </result>
 </results>
</sparql>
```

which, as far as I can tell, is perfectly fine and contains no relative URIs. How are you executing your query to produce your result?

**Comment by reckart** [comment]
> EDIT I just discovered that if I make the "default dataset name" field blank (by default it is set to `http://dbpedia.org`) I can reproduce your result.

Good catch ;) I haven't been able to reproduce it in the browser either and I didn't find/think of the default dataset option.
