### ISSUE TITLE
How to connect to GraphDB 8.8 with username and password

### ISSUE THREAD

**Issue by jamesatcaas** [eclipse/rdf4j#1367]
I am try to connect to GraphDB 8.8 with RDF4J api as the following:

private static void initRepositoryConnection() {
	  
	  RepositoryManager repositoryManager =
		        new RemoteRepositoryManager(GRAPHDB_SERVER);
		
		CredentialsProvider credsProvider = new BasicCredentialsProvider();
		Credentials credentials = new UsernamePasswordCredentials("admin", "root");
		credsProvider.setCredentials(AuthScope.ANY, credentials);
		HttpClient httpclient = HttpClients.custom()
				.setDefaultCredentialsProvider(credsProvider)
				.build();
		
		repositoryManager.setHttpClient(httpclient);
		
		repositoryManager.init();			
		
    Repository repository =   repositoryManager.getRepository(REPOSITORY_ID);
    repository.init();
      
    repositoryConnection =  repository.getConnection();
  }

When I called the following function:
public static void insertModelToGraphDB() {
	  initRepositoryConnection();
		    repositoryConnection.begin();    
		    	    
		    Model model = new LinkedHashModel();
		    model.setNamespace("dc", "http://purl.org/dc/elements/1.1/");
		    
		    ValueFactory factory = SimpleValueFactory.getInstance();
		    
		    System.out.println("start...");
		    
		    for(int i = 0; i < 100; i++)
		    {
		    IRI bob = factory.createIRI("http://example.org/bob" + i);
		    IRI graphID = factory.createIRI("http://example.org/person");
		    IRI name = factory.createIRI("http://example.org/name");
		    Literal bobsName = factory.createLiteral("Bob" + i);
		    Statement nameStatement = factory.createStatement(bob, name, bobsName, graphID);
		    
		    model.add(nameStatement);
		    }
		    
		    try {
		    	//System.out.println(model);
		    	
		      repositoryConnection.add(model);	
		      repositoryConnection.commit();
		      System.out.println("finished");
		      
		    } catch (Exception e) {
		    	
		      e.printStackTrace();
		      
		      if (repositoryConnection.isActive())
		        repositoryConnection.rollback();
		    }
		  }
  

I get the errors as:
org.eclipse.rdf4j.repository.manager.RemoteRepositoryManager - Not authorized to retrieve list of repositories
org.eclipse.rdf4j.http.protocol.UnauthorizedException: null
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.execute(SPARQLProtocolSession.java:1107)
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.executeOK(SPARQLProtocolSession.java:1049)
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.sendTupleQueryViaHttp(SPARQLProtocolSession.java:825)
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.getTupleQueryResult(SPARQLProtocolSession.java:754)
	at org.eclipse.rdf4j.http.client.RDF4JProtocolSession.getRepositoryList(RDF4JProtocolSession.java:213)
	at org.eclipse.rdf4j.http.client.RDF4JProtocolSession.getRepositoryList(RDF4JProtocolSession.java:195)
	at org.eclipse.rdf4j.repository.manager.RemoteRepositoryManager.getAllRepositoryInfos(RemoteRepositoryManager.java:255)
	at org.eclipse.rdf4j.repository.manager.RepositoryManager.getAllRepositoryInfos(RepositoryManager.java:555)
	at org.eclipse.rdf4j.repository.manager.RepositoryManager.getRepositoryInfo(RepositoryManager.java:545)
	at org.eclipse.rdf4j.repository.manager.RepositoryManager.hasRepositoryConfig(RepositoryManager.java:237)
	at org.eclipse.rdf4j.repository.manager.RemoteRepositoryManager.createRepository(RemoteRepositoryManager.java:221)
	at org.eclipse.rdf4j.repository.manager.RepositoryManager.getRepository(RepositoryManager.java:427)
	at org.graphdb.rdf4j.tutorial.RDF4JExample.initRepositoryConnection(RDF4JExample.java:83)
	at org.graphdb.rdf4j.tutorial.RDF4JExample.insertModelToGraphDB(RDF4JExample.java:91)
	at org.graphdb.rdf4j.tutorial.RDF4JExample.main(RDF4JExample.java:213)
org.eclipse.rdf4j.repository.RepositoryException: org.eclipse.rdf4j.http.protocol.UnauthorizedException
	at org.eclipse.rdf4j.repository.manager.RemoteRepositoryManager.getAllRepositoryInfos(RemoteRepositoryManager.java:298)
	at org.eclipse.rdf4j.repository.manager.RepositoryManager.getAllRepositoryInfos(RepositoryManager.java:555)
	at org.eclipse.rdf4j.repository.manager.RepositoryManager.getRepositoryInfo(RepositoryManager.java:545)
	at org.eclipse.rdf4j.repository.manager.RepositoryManager.hasRepositoryConfig(RepositoryManager.java:237)
	at org.eclipse.rdf4j.repository.manager.RemoteRepositoryManager.createRepository(RemoteRepositoryManager.java:221)
	at org.eclipse.rdf4j.repository.manager.RepositoryManager.getRepository(RepositoryManager.java:427)
	at org.graphdb.rdf4j.tutorial.RDF4JExample.initRepositoryConnection(RDF4JExample.java:83)
	at org.graphdb.rdf4j.tutorial.RDF4JExample.insertModelToGraphDB(RDF4JExample.java:91)
	at org.graphdb.rdf4j.tutorial.RDF4JExample.main(RDF4JExample.java:213)
Caused by: org.eclipse.rdf4j.http.protocol.UnauthorizedException
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.execute(SPARQLProtocolSession.java:1107)
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.executeOK(SPARQLProtocolSession.java:1049)
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.sendTupleQueryViaHttp(SPARQLProtocolSession.java:825)
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.getTupleQueryResult(SPARQLProtocolSession.java:754)
	at org.eclipse.rdf4j.http.client.RDF4JProtocolSession.getRepositoryList(RDF4JProtocolSession.java:213)
	at org.eclipse.rdf4j.http.client.RDF4JProtocolSession.getRepositoryList(RDF4JProtocolSession.java:195)
	at org.eclipse.rdf4j.repository.manager.RemoteRepositoryManager.getAllRepositoryInfos(RemoteRepositoryManager.java:255)
	... 8 more

What's the right way to set the username and password while connect to GraphDB?
Thanks a lot.

**Comment by barthanssens** [comment]
Hi,

does this work ?
```
RemoteRepositoryManager mgr = new RemoteRepositoryManager(GRAPHDB_SERVER);
mgr.setUsernameAndPassword("admin", "root")
```
(instead of / without the CredentialsProvider and setHttpClient() in your code)

**Comment by jamesatcaas** [comment]
Thanks a lot @barthanssens !
It works!
