### ISSUE TITLE
How to ignore or skip the invalid IRI while parse RDF triples?

### ISSUE THREAD

**Issue by jamesatcaas** [eclipse/rdf4j#1446]
I am trying to parse and upload  the Freebase  N-Triples RDF to GraphDB, 

	MyRdfInserter inserter = new MyRdfInserter(con, graphIRI);
	rdfParser.setRDFHandler(inserter); 
	rdfParser.parse(inputStream, meta.getBaseIRI()); 

and got the error as：

org.eclipse.rdf4j.repository.RepositoryException: Transaction handling error: org.eclipse.rdf4j.rio.RDFParseException: Unexpected character U+5B at index 67: http://www.clicker.com/movie/y-tu-mama-tambien-and-your-mother-too-[spn]
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.execute(SPARQLProtocolSession.java:1019)
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.executeNoContent(SPARQLProtocolSession.java:978)
	at org.eclipse.rdf4j.http.client.RDF4JProtocolSession.upload(RDF4JProtocolSession.java:906)
	at org.eclipse.rdf4j.http.client.RDF4JProtocolSession.upload(RDF4JProtocolSession.java:730)
	at org.eclipse.rdf4j.http.client.RDF4JProtocolSession.addData(RDF4JProtocolSession.java:710)
	at org.eclipse.rdf4j.repository.http.HTTPRepositoryConnection.addModel(HTTPRepositoryConnection.java:539)
	at org.eclipse.rdf4j.repository.http.HTTPRepositoryConnection.flushTransactionState(HTTPRepositoryConnection.java:602)
	at org.eclipse.rdf4j.repository.http.HTTPRepositoryConnection.commit(HTTPRepositoryConnection.java:301)
	at org.graphdb.rdf4j.tutorial.MyRdfInserter.handleStatement(MyRdfInserter.java:57)
	at org.eclipse.rdf4j.rio.ntriples.NTriplesParser.parseTriple(NTriplesParser.java:287)
	at org.eclipse.rdf4j.rio.ntriples.NTriplesParser.parse(NTriplesParser.java:160)
	at org.eclipse.rdf4j.rio.ntriples.NTriplesParser.parse(NTriplesParser.java:109)
	at org.graphdb.rdf4j.tutorial.RDF4JExample.loadFileToGraphDB(RDF4JExample.java:235)
	at org.graphdb.rdf4j.tutorial.RDF4JExample.main(RDF4JExample.java:320)

I've already set the parameters as:
rdfParser.getParserConfig().set(BasicParserSettings.VERIFY_URI_SYNTAX, false);
OR
rdfParser.getParserConfig().set(NTriplesParserSettings.FAIL_ON_INVALID_LINES, false);

But still got the above error, Could someone help me?

**Comment by jeenbroekstra** [comment]
Sorry it took so long to get back to you, we overlooked this issue.

The problem is that you are trying to add data to a remote store, and while you have configured your parser at the _client_ end to not verify uri syntax, the server-side parser is still set to defaults. 

Tweaking the server-side parser configuration programmatically is currently not possible (see #446), however, you can use commandline switches to reconfigure the server on startup. See https://rdf4j.eclipse.org/documentation/programming/rio/#configuring-the-parser-writer for details. For example, you could add the following switches to your Java options when the server starts up: `-Dorg.eclipse.rdf4j.rio.verify_uri_syntax=false -Dorg.eclipse.rdf4j.rio.ntriples.fail_on_invalid_lines=false`.

**Comment by flyon** [comment]
@jeenbroekstra are these settings still correct? I've added them to the java options, but I'm still getting the same error when importing

![image](https://user-images.githubusercontent.com/341567/90135203-e4ba2180-dda4-11ea-8cbd-3ed4feb021d4.png)
![image](https://user-images.githubusercontent.com/341567/90135224-ed125c80-dda4-11ea-8877-aaacc2dbea1c.png)
![image](https://user-images.githubusercontent.com/341567/90135253-fb607880-dda4-11ea-9cfa-36236a689e78.png)

**Comment by flyon** [comment]
or would that be GraphDB specific?

**Comment by jeenbroekstra** [comment]
They are still correct. A couple of things to note: 1) you will need to restart your server after applying these properties for the settings to take effect, and 2) this should work as expected for the NQuads file you're trying to load, but the JSONLD parser's behavior is not influenced by the `fail_on_invalid_lines` setting (for the simple reason that JSONLD is not a line-by-line format). 

I am not 100% sure if this would be GraphDB-specific, but I wouldn't expect so. If you have trouble still after a restart, can you please open a new issue, and add a sample of the file(s) you are trying to upload that reproduces the problem?

**Comment by flyon** [comment]
I couldn't get it to work with the flags. GraphDB has a checkbox for "stopping on error", even with that turned off it stops the import. I ended up splitting the files up a number of times until I found the faulty line. A URL with a double hash ##. The error messages did not show me which IRI was faulty, but maybe that's something for the GraphDB team. Either way, thank you for your reply.
