### ISSUE TITLE
rdf4j v2.4.6 not integrated with yasqe?

### ISSUE THREAD

**Issue by tomas-knap** [eclipse/rdf4j#1465]
`i am running rdf4j version 2.4.6+3409524 and have noticed that the query page is not integrated with YASQE while version 2.3.3 is. Is there some configuration that needs to be done in order to get this to work, or was this removed?

**Comment by barthanssens** [comment]
Hmz, should still be there, there is a ticket for planning to  use a newer version of YASQE, but 2.3/2.4/2.5 should not make a difference....

**Comment by barthanssens** [comment]
Could you provide some info about your browser ? I've quickly spun up a docker for 2.4.6 (Linux/FF 66 64-bit), and it seems to work for SPARQL (syntax highlighting + toggling between full screen and text field)

(there seems to be a bug though, when I switch to SERQL and back to SPARQL, then YASQE isn't available, I have to reload the page)

**Comment by amarhubi** [comment]
Hello

I am using Chrome 75.0.3770.100 and Edge 41.16299.1004.0

I did not change between SERQL and SPARQL. I can see an error in the Chrome console and am wondering if this is related?

`Uncaught DOMExcetion: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
      at Array.<anonymous> ({URL}/rdf4j-workbench/scirpts/template.js:84:51)
      at {URL}/rdf4j-workbench/srcipts/template.js:11:24  `

**Comment by barthanssens** [comment]
Weird, looks good on my Windows 10 with Edge and with Chrome 74.0.3729.157, the console does not show an DOMException, but does display a few other warnings ("Resource interpreted as Stylesheet but transferred with MIME type application/xml: ...messages.xsl".)

I'll try to test in on another Windows machine...

If you would have docker running, could you check 2.5.2 to see if that makes a difference ?
https://hub.docker.com/r/eclipse/rdf4j-workbench/tags

**Comment by barthanssens** [comment]
Is it still an issue with more recent (2.5.x or 3.0.x) rdf4j versions ? Or can this be closed ?
