### ISSUE TITLE
NPX during context cache initialization in NativeSailStore 2.5.3

### ISSUE THREAD

**Issue by ledsoft** [eclipse/rdf4j#1498]
Hi,

I think I've discovered a bug in the new context cache in Native stores.

This issue occurs in case a Native store is initialized over an existing data directory which does not contain the `contexts.dat` cache file.

There is a cycle of dependencies `NativeSailStore (line 94)` -> `ContextStore (line 101)` -> `NativeSailStore.initializeContextCache (line 199)`, where the `contextStore` field is still null.

The bug is easy to reproduce. Just take an existing (non-empty, with some statements in contexts) native store data directory from an older RDF4J (e.g. 2.4.x) instance or remove the `contexts.dat` file from a new one and run the following:

```Java
File dataDir = new File("/home/user/.RDF4J/server/repositories/existing-repository/");
Repository repo = new SailRepository(new NativeStore(dataDir));
repo.init();
```
For reference, here's the relevant part of the stack trace:
```Caused by: org.eclipse.rdf4j.sail.SailException: java.lang.NullPointerException
	at org.eclipse.rdf4j.sail.nativerdf.NativeStore.initializeInternal(NativeStore.java:300)
	at org.eclipse.rdf4j.sail.helpers.AbstractSail.init(AbstractSail.java:189)
	at org.eclipse.rdf4j.repository.sail.SailRepository.initializeInternal(SailRepository.java:146)
	... 41 more
Caused by: java.lang.NullPointerException
	at org.eclipse.rdf4j.sail.nativerdf.NativeSailStore.initializeContextCache(NativeSailStore.java:199)
	at org.eclipse.rdf4j.sail.nativerdf.ContextStore.<init>(ContextStore.java:101)
	at org.eclipse.rdf4j.sail.nativerdf.NativeSailStore.<init>(NativeSailStore.java:94)
	at org.eclipse.rdf4j.sail.nativerdf.NativeStore.initializeInternal(NativeStore.java:259)
	... 43 more
```

Discovered through RDF4J server which stopped returning query results after migration to 2.5.3. Seems to be caused by PR [#253](https://github.com/eclipse/rdf4j-storage/pull/253).

**Comment by jeenbroekstra** [comment]
Oh my. Thanks for reporting this! We'll roll out a patch ASAP.

**Comment by ledsoft** [comment]
Thanks for the quick fix!
