### ISSUE TITLE
Console: NPE when just typing "prefix" 

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1511]
NPE when just entering "prefix" at the command prompt (Console is expecting a full query)

See message on forum: https://groups.google.com/forum/#!topic/rdf4j-users/x-dPGe53Wk4

**Comment by barthanssens** [comment]
```
Exception in thread "main" java.lang.NullPointerException
        at org.eclipse.rdf4j.query.parser.QueryPrologLexer.getRestOfQueryToken(QueryPrologLexer.java:161)
        at org.eclipse.rdf4j.query.parser.QueryParserUtil.removeSPARQLQueryProlog(QueryParserUtil.java:167)
        at org.eclipse.rdf4j.query.parser.QueryParserUtil.parseOperation(QueryParserUtil.java:45)
        at org.eclipse.rdf4j.console.command.QueryEvaluator.parseAndEvaluateQuery(QueryEvaluator.java:323)
        at org.eclipse.rdf4j.console.command.QueryEvaluator.executeQuery(QueryEvaluator.java:194)
        at org.eclipse.rdf4j.console.Console.executeCommand(Console.java:344)
        at org.eclipse.rdf4j.console.Console.start(Console.java:304)
        at org.eclipse.rdf4j.console.Console.main(Console.java:143)
```
