### ISSUE TITLE
Better handling of contexts with or without <> in Workbench

### ISSUE THREAD

**Issue by jakubklimek** [eclipse/rdf4j#1560]
In Workbench, when I try to add data into a context, e.g. `http://data`, I get an error:
```
Malformed value: http://data
```
I am running rdf4j 3.0.0, Apache Tomcat 9.0.17 and 9.0.26 and OpenJDK 13. In the tomcat log its says `org.eclipse.rdf4j.workbench.exceptions.BadRequestException: Undefined prefix: http://data`. Not sure why it would parse the context url as prefixed url. Full log:
```
13:06:09.214 [http-nio-8080-exec-4] WARN org.eclipse.rdf4j.workbench.proxy.ServerValidator - server URL null does not have a prefix file: http: https:
13:06:09.214 [http-nio-8080-exec-4] INFO org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet - Servicing repository: aaaa
13:06:09.220 [http-nio-8080-exec-4] INFO org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet - RemoteRepositoryManager URL: http://localhost:8080/rdf4j-server
13:06:09.223 [http-nio-8080-exec-4] DEBUG org.apache.http.client.protocol.RequestAddCookies - CookieSpec selected: default
13:06:09.224 [http-nio-8080-exec-4] DEBUG org.apache.http.client.protocol.RequestAuthCache - Auth cache not set in the context
13:06:09.225 [http-nio-8080-exec-4] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection request: [route: {}->http://localhost:8080][total kept alive: 2; route allocated: 2 of 5; total allocated: 2 of 10]
13:06:09.227 [http-nio-8080-exec-4] DEBUG org.apache.http.wire - http-outgoing-10 << "[read] I/O error: Read timed out"
13:06:09.227 [http-nio-8080-exec-4] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection leased: [id: 10][route: {}->http://localhost:8080][total kept alive: 1; route allocated: 2 of 5; total allocated: 2 of 10]
13:06:09.229 [http-nio-8080-exec-4] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-10: set socket timeout to 0
13:06:09.239 [http-nio-8080-exec-4] DEBUG org.apache.http.impl.execchain.MainClientExec - Executing request GET /rdf4j-server/repositories/aaaa/namespaces/http HTTP/1.1
13:06:09.240 [http-nio-8080-exec-4] DEBUG org.apache.http.impl.execchain.MainClientExec - Target auth state: UNCHALLENGED
13:06:09.241 [http-nio-8080-exec-4] DEBUG org.apache.http.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
13:06:09.243 [http-nio-8080-exec-4] DEBUG org.apache.http.headers - http-outgoing-10 >> GET /rdf4j-server/repositories/aaaa/namespaces/http HTTP/1.1
13:06:09.244 [http-nio-8080-exec-4] DEBUG org.apache.http.headers - http-outgoing-10 >> Host: localhost:8080
13:06:09.246 [http-nio-8080-exec-4] DEBUG org.apache.http.headers - http-outgoing-10 >> Connection: Keep-Alive
13:06:09.247 [http-nio-8080-exec-4] DEBUG org.apache.http.headers - http-outgoing-10 >> User-Agent: Apache-HttpClient/4.5.9 (Java/13)
13:06:09.260 [http-nio-8080-exec-4] DEBUG org.apache.http.headers - http-outgoing-10 >> Accept-Encoding: gzip,deflate
13:06:09.261 [http-nio-8080-exec-4] DEBUG org.apache.http.wire - http-outgoing-10 >> "GET /rdf4j-server/repositories/aaaa/namespaces/http HTTP/1.1[\r][\n]"
13:06:09.262 [http-nio-8080-exec-4] DEBUG org.apache.http.wire - http-outgoing-10 >> "Host: localhost:8080[\r][\n]"
13:06:09.264 [http-nio-8080-exec-4] DEBUG org.apache.http.wire - http-outgoing-10 >> "Connection: Keep-Alive[\r][\n]"
13:06:09.265 [http-nio-8080-exec-4] DEBUG org.apache.http.wire - http-outgoing-10 >> "User-Agent: Apache-HttpClient/4.5.9 (Java/13)[\r][\n]"
13:06:09.267 [http-nio-8080-exec-4] DEBUG org.apache.http.wire - http-outgoing-10 >> "Accept-Encoding: gzip,deflate[\r][\n]"
13:06:09.268 [http-nio-8080-exec-4] DEBUG org.apache.http.wire - http-outgoing-10 >> "[\r][\n]"
13:06:09.274 [http-nio-8080-exec-4] DEBUG org.apache.http.wire - http-outgoing-10 << "HTTP/1.1 404 [\r][\n]"
13:06:09.280 [http-nio-8080-exec-4] DEBUG org.apache.http.wire - http-outgoing-10 << "Vary: Accept-Encoding[\r][\n]"
13:06:09.281 [http-nio-8080-exec-4] DEBUG org.apache.http.wire - http-outgoing-10 << "Content-Type: text/plain;charset=UTF-8[\r][\n]"
13:06:09.282 [http-nio-8080-exec-4] DEBUG org.apache.http.wire - http-outgoing-10 << "Content-Language: en-US[\r][\n]"
13:06:09.283 [http-nio-8080-exec-4] DEBUG org.apache.http.wire - http-outgoing-10 << "Content-Length: 22[\r][\n]"
13:06:09.285 [http-nio-8080-exec-4] DEBUG org.apache.http.wire - http-outgoing-10 << "Date: Wed, 25 Sep 2019 11:06:09 GMT[\r][\n]"
13:06:09.286 [http-nio-8080-exec-4] DEBUG org.apache.http.wire - http-outgoing-10 << "[\r][\n]"
13:06:09.288 [http-nio-8080-exec-4] DEBUG org.apache.http.wire - http-outgoing-10 << "Undefined prefix: http"
13:06:09.298 [http-nio-8080-exec-4] DEBUG org.apache.http.headers - http-outgoing-10 << HTTP/1.1 404
13:06:09.299 [http-nio-8080-exec-4] DEBUG org.apache.http.headers - http-outgoing-10 << Vary: Accept-Encoding
13:06:09.301 [http-nio-8080-exec-4] DEBUG org.apache.http.headers - http-outgoing-10 << Content-Type: text/plain;charset=UTF-8
13:06:09.303 [http-nio-8080-exec-4] DEBUG org.apache.http.headers - http-outgoing-10 << Content-Language: en-US
13:06:09.306 [http-nio-8080-exec-4] DEBUG org.apache.http.headers - http-outgoing-10 << Content-Length: 22
13:06:09.308 [http-nio-8080-exec-4] DEBUG org.apache.http.headers - http-outgoing-10 << Date: Wed, 25 Sep 2019 11:06:09 GMT
13:06:09.327 [http-nio-8080-exec-4] DEBUG org.apache.http.impl.execchain.MainClientExec - Connection can be kept alive indefinitely
13:06:09.332 [http-nio-8080-exec-4] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection [id: 10][route: {}->http://localhost:8080] can be kept alive indefinitely
13:06:09.332 [http-nio-8080-exec-4] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-10: set socket timeout to 0
13:06:09.333 [http-nio-8080-exec-4] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection released: [id: 10][route: {}->http://localhost:8080][total kept alive: 2; route allocated: 2 of 5; total allocated: 2 of 10]
13:06:09.335 [http-nio-8080-exec-4] DEBUG org.apache.http.impl.execchain.MainClientExec - Cancelling request execution
13:06:09.345 [http-nio-8080-exec-4] WARN org.eclipse.rdf4j.workbench.util.ValueDecoder - org.eclipse.rdf4j.workbench.exceptions.BadRequestException: Undefined prefix: http://data
org.eclipse.rdf4j.workbench.exceptions.BadRequestException: Undefined prefix: http://data
        at org.eclipse.rdf4j.workbench.util.ValueDecoder.parseURI(ValueDecoder.java:84)
        at org.eclipse.rdf4j.workbench.util.ValueDecoder.decodeValue(ValueDecoder.java:66)
        at org.eclipse.rdf4j.workbench.util.WorkbenchRequest.getValue(WorkbenchRequest.java:263)
        at org.eclipse.rdf4j.workbench.util.WorkbenchRequest.getResource(WorkbenchRequest.java:186)
        at org.eclipse.rdf4j.workbench.commands.AddServlet.doPost(AddServlet.java:46)
        at org.eclipse.rdf4j.workbench.base.TransformationServlet.service(TransformationServlet.java:93)
        at org.eclipse.rdf4j.workbench.base.AbstractServlet.service(AbstractServlet.java:125)
        at org.eclipse.rdf4j.workbench.proxy.ProxyRepositoryServlet.service(ProxyRepositoryServlet.java:99)
        at org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:188)
        at org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.handleRequest(WorkbenchServlet.java:128)
        at org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:103)
        at org.eclipse.rdf4j.workbench.proxy.WorkbenchGateway.service(WorkbenchGateway.java:114)
        at org.eclipse.rdf4j.workbench.base.AbstractServlet.service(AbstractServlet.java:125)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.eclipse.rdf4j.workbench.proxy.CacheFilter.doFilter(CacheFilter.java:61)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.eclipse.rdf4j.workbench.proxy.CookieCacheControlFilter.doFilter(CookieCacheControlFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:830)
13:06:09.347 [http-nio-8080-exec-4] WARN org.eclipse.rdf4j.workbench.commands.AddServlet - org.eclipse.rdf4j.workbench.exceptions.BadRequestException: Malformed value: http://data
org.eclipse.rdf4j.workbench.exceptions.BadRequestException: Malformed value: http://data
        at org.eclipse.rdf4j.workbench.util.ValueDecoder.decodeValue(ValueDecoder.java:74)
        at org.eclipse.rdf4j.workbench.util.WorkbenchRequest.getValue(WorkbenchRequest.java:263)
        at org.eclipse.rdf4j.workbench.util.WorkbenchRequest.getResource(WorkbenchRequest.java:186)
        at org.eclipse.rdf4j.workbench.commands.AddServlet.doPost(AddServlet.java:46)
        at org.eclipse.rdf4j.workbench.base.TransformationServlet.service(TransformationServlet.java:93)
        at org.eclipse.rdf4j.workbench.base.AbstractServlet.service(AbstractServlet.java:125)
        at org.eclipse.rdf4j.workbench.proxy.ProxyRepositoryServlet.service(ProxyRepositoryServlet.java:99)
        at org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:188)
        at org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.handleRequest(WorkbenchServlet.java:128)
        at org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:103)
        at org.eclipse.rdf4j.workbench.proxy.WorkbenchGateway.service(WorkbenchGateway.java:114)
        at org.eclipse.rdf4j.workbench.base.AbstractServlet.service(AbstractServlet.java:125)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.eclipse.rdf4j.workbench.proxy.CacheFilter.doFilter(CacheFilter.java:61)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.eclipse.rdf4j.workbench.proxy.CookieCacheControlFilter.doFilter(CookieCacheControlFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: org.eclipse.rdf4j.workbench.exceptions.BadRequestException: Undefined prefix: http://data
        at org.eclipse.rdf4j.workbench.util.ValueDecoder.parseURI(ValueDecoder.java:84)
        at org.eclipse.rdf4j.workbench.util.ValueDecoder.decodeValue(ValueDecoder.java:66)
        ... 39 common frames omitted
13:06:09.481 [http-nio-8080-exec-3] WARN org.eclipse.rdf4j.workbench.proxy.ServerValidator - server URL null does not have a prefix file: http: https:
13:06:09.481 [http-nio-8080-exec-3] INFO org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet - Servicing repository: aaaa
13:06:09.486 [http-nio-8080-exec-3] INFO org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet - RemoteRepositoryManager URL: http://localhost:8080/rdf4j-server
13:06:09.488 [http-nio-8080-exec-3] DEBUG org.apache.http.client.protocol.RequestAddCookies - CookieSpec selected: default
13:06:09.488 [http-nio-8080-exec-3] DEBUG org.apache.http.client.protocol.RequestAuthCache - Auth cache not set in the context
13:06:09.489 [http-nio-8080-exec-3] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection request: [route: {}->http://localhost:8080][total kept alive: 2; route allocated: 2 of 5; total allocated: 2 of 10]
13:06:09.490 [http-nio-8080-exec-3] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection leased: [id: 10][route: {}->http://localhost:8080][total kept alive: 1; route allocated: 2 of 5; total allocated: 2 of 10]
13:06:09.491 [http-nio-8080-exec-3] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-10: set socket timeout to 0
13:06:09.492 [http-nio-8080-exec-3] DEBUG org.apache.http.impl.execchain.MainClientExec - Executing request GET /rdf4j-server/repositories HTTP/1.1
13:06:09.493 [http-nio-8080-exec-3] DEBUG org.apache.http.impl.execchain.MainClientExec - Target auth state: UNCHALLENGED
13:06:09.494 [http-nio-8080-exec-3] DEBUG org.apache.http.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
13:06:09.509 [http-nio-8080-exec-3] DEBUG org.apache.http.headers - http-outgoing-10 >> GET /rdf4j-server/repositories HTTP/1.1
13:06:09.510 [http-nio-8080-exec-3] DEBUG org.apache.http.headers - http-outgoing-10 >> Accept: text/csv;q=0.8, application/sparql-results+json;q=0.8, application/json;q=0.8, application/sparql-results+xml;q=0.8, application/xml;q=0.8, text/tab-separated-values;q=0.8, application/x-binary-rdf-results-table
13:06:09.512 [http-nio-8080-exec-3] DEBUG org.apache.http.headers - http-outgoing-10 >> Host: localhost:8080
13:06:09.513 [http-nio-8080-exec-3] DEBUG org.apache.http.headers - http-outgoing-10 >> Connection: Keep-Alive
13:06:09.514 [http-nio-8080-exec-3] DEBUG org.apache.http.headers - http-outgoing-10 >> User-Agent: Apache-HttpClient/4.5.9 (Java/13)
13:06:09.519 [http-nio-8080-exec-3] DEBUG org.apache.http.headers - http-outgoing-10 >> Accept-Encoding: gzip,deflate
13:06:09.537 [http-nio-8080-exec-3] DEBUG org.apache.http.wire - http-outgoing-10 >> "GET /rdf4j-server/repositories HTTP/1.1[\r][\n]"
13:06:09.538 [http-nio-8080-exec-3] DEBUG org.apache.http.wire - http-outgoing-10 >> "Accept: text/csv;q=0.8, application/sparql-results+json;q=0.8, application/json;q=0.8, application/sparql-results+xml;q=0.8, application/xml;q=0.8, text/tab-separated-values;q=0.8, application/x-binary-rdf-results-table[\r][\n]"
13:06:09.539 [http-nio-8080-exec-3] DEBUG org.apache.http.wire - http-outgoing-10 >> "Host: localhost:8080[\r][\n]"
13:06:09.543 [http-nio-8080-exec-3] DEBUG org.apache.http.wire - http-outgoing-10 >> "Connection: Keep-Alive[\r][\n]"
13:06:09.545 [http-nio-8080-exec-3] DEBUG org.apache.http.wire - http-outgoing-10 >> "User-Agent: Apache-HttpClient/4.5.9 (Java/13)[\r][\n]"
13:06:09.562 [http-nio-8080-exec-3] DEBUG org.apache.http.wire - http-outgoing-10 >> "Accept-Encoding: gzip,deflate[\r][\n]"
13:06:09.564 [http-nio-8080-exec-3] DEBUG org.apache.http.wire - http-outgoing-10 >> "[\r][\n]"
13:06:09.589 [http-nio-8080-exec-3] DEBUG org.apache.http.wire - http-outgoing-10 << "HTTP/1.1 200 [\r][\n]"
13:06:09.590 [http-nio-8080-exec-3] DEBUG org.apache.http.wire - http-outgoing-10 << "Vary: Accept[\r][\n]"
13:06:09.591 [http-nio-8080-exec-3] DEBUG org.apache.http.wire - http-outgoing-10 << "Content-Disposition: attachment; filename=repositories.brt[\r][\n]"
13:06:09.595 [http-nio-8080-exec-3] DEBUG org.apache.http.wire - http-outgoing-10 << "Content-Type: application/x-binary-rdf-results-table;charset=ISO-8859-1[\r][\n]"
13:06:09.595 [http-nio-8080-exec-3] DEBUG org.apache.http.wire - http-outgoing-10 << "Content-Language: en-US[\r][\n]"
13:06:09.611 [http-nio-8080-exec-3] DEBUG org.apache.http.wire - http-outgoing-10 << "Transfer-Encoding: chunked[\r][\n]"
13:06:09.613 [http-nio-8080-exec-3] DEBUG org.apache.http.wire - http-outgoing-10 << "Date: Wed, 25 Sep 2019 11:06:09 GMT[\r][\n]"
13:06:09.615 [http-nio-8080-exec-3] DEBUG org.apache.http.wire - http-outgoing-10 << "[\r][\n]"
13:06:09.617 [http-nio-8080-exec-3] DEBUG org.apache.http.wire - http-outgoing-10 << "1d0[\r][\n]"
13:06:09.618 [http-nio-8080-exec-3] DEBUG org.apache.http.wire - http-outgoing-10 << "BRTR[0x0][0x0][0x0][0x4][0x0][0x0][0x0][0x5][0x0][0x0][0x0][0x3]uri[0x0][0x0][0x0][0x2]id[0x0][0x0][0x0][0x5]title[0x0][0x0][0x0][0x8]readable[0x0][0x0][0x0][0x8]writable[0x2][0x0][0x0][0x0][0x0][0x0][0x0][0x0]0http://localhost:8080/rdf4j-server/repositories/[0x3][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x4]aaaa[0x2][0x0][0x0][0x0][0x1][0x0][0x0][0x0]!http://www.w3.org/2001/XMLSchema#[0x8][0x0][0x0][0x0][0x4]aaaa[0x3][0x0][0x0][0x0][0x1][0x0][0x0][0x0][0x6]string[0x8][0x0][0x0][0x0][0xc]Memory store[0x3][0x0][0x0][0x0][0x1][0x0][0x0][0x0][0x6]string[0x8][0x0][0x0][0x0][0x4]true[0x3][0x0][0x0][0x0][0x1][0x0][0x0][0x0][0x7]boolean[0x8][0x0][0x0][0x0][0x4]true[0x3][0x0][0x0][0x0][0x1][0x0][0x0][0x0][0x7]boolean[0x3][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x2]r1[0x8][0x0][0x0][0x0][0x2]r1[0x3][0x0][0x0][0x0][0x1][0x0][0x0][0x0][0x6]string[0x8][0x0][0x0][0x0][0x4]test[0x3][0x0][0x0][0x0][0x1][0x0][0x0][0x0][0x6]string[0x1][0x1][0x3][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x5]shacl[0x8][0x0][0x0][0x0][0x5]shacl[0x3][0x0][0x0][0x0][0x1][0x0][0x0][0x0][0x6]string[0x8][0x0][0x0][0x0][0x17]Memory store with SHACL[0x3][0x0][0x0][0x0][0x1][0x0][0x0][0x0][0x6]string[0x1][0x1][0x3][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x6]SYSTEM[0x8][0x0][0x0][0x0][0x6]SYSTEM[0x3][0x0][0x0][0x0][0x1][0x0][0x0][0x0][0x6]string[0x0][0x1][0x1][\r][\n]"
13:06:09.639 [http-nio-8080-exec-3] DEBUG org.apache.http.headers - http-outgoing-10 << HTTP/1.1 200
13:06:09.640 [http-nio-8080-exec-3] DEBUG org.apache.http.headers - http-outgoing-10 << Vary: Accept
13:06:09.641 [http-nio-8080-exec-3] DEBUG org.apache.http.headers - http-outgoing-10 << Content-Disposition: attachment; filename=repositories.brt
13:06:09.643 [http-nio-8080-exec-3] DEBUG org.apache.http.headers - http-outgoing-10 << Content-Type: application/x-binary-rdf-results-table;charset=ISO-8859-1
13:06:09.644 [http-nio-8080-exec-3] DEBUG org.apache.http.headers - http-outgoing-10 << Content-Language: en-US
13:06:09.645 [http-nio-8080-exec-3] DEBUG org.apache.http.headers - http-outgoing-10 << Transfer-Encoding: chunked
13:06:09.674 [http-nio-8080-exec-3] DEBUG org.apache.http.headers - http-outgoing-10 << Date: Wed, 25 Sep 2019 11:06:09 GMT
13:06:09.681 [http-nio-8080-exec-3] DEBUG org.apache.http.impl.execchain.MainClientExec - Connection can be kept alive indefinitely
13:06:09.682 [http-nio-8080-exec-3] DEBUG org.eclipse.rdf4j.http.client.SharedHttpClientSessionManager$3 - reponse MIME type is application/x-binary-rdf-results-table
13:06:09.683 [http-nio-8080-exec-3] DEBUG org.apache.http.wire - http-outgoing-10 << "0[\r][\n]"
13:06:09.684 [http-nio-8080-exec-3] DEBUG org.apache.http.wire - http-outgoing-10 << "[\r][\n]"
13:06:09.685 [http-nio-8080-exec-3] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection [id: 10][route: {}->http://localhost:8080] can be kept alive indefinitely
13:06:09.687 [http-nio-8080-exec-3] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-10: set socket timeout to 0
13:06:09.688 [http-nio-8080-exec-3] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection released: [id: 10][route: {}->http://localhost:8080][total kept alive: 2; route allocated: 2 of 5; total allocated: 2 of 10]
13:06:09.689 [http-nio-8080-exec-3] DEBUG org.apache.http.impl.execchain.MainClientExec - Cancelling request execution
```

**Comment by barthanssens** [comment]
Hi Jakub,

have used &lt;http://data&gt; ? Seems like the &lt; / &gt; are missing, resulting in an attempt to decode a prefix ...

**Comment by jakubklimek** [comment]
Hi @barthanssens, you are right. Adding < > is indeed a workaround for this.

Still, it seems strange to me (definitely unexpected) that Workbench requires putting context IRI in < >, when there is a special text field for it. I would expect this to be handled by the UI.

**Comment by barthanssens** [comment]
Well.. it could be considered a feature that one can use prefixes in contexts, but indeed the UI could be a bit smarter about this

**Comment by hmottestad** [comment]
I would recommend to add an example below the field in the UI eg. “ex:graph1 or <http://example.com/graph1>“

**Comment by hmottestad** [comment]
I propose the following task:

In the case where the context does not match the pattern `<.*?>` try to expand the context with the namespace, if the expanded version is equal to the unexpanded version then the user probably made a mistake. Throw an exception if this is the case, but this should happen in Workbench and not in Server.

Eg. 
 - `ex:graph1` expands to `http://example.org/graph1` which is not equal to `ex:graph1` so is fine
 - `http://example.org/graph1` expands to `http://example.org/graph1` and does not start with `<` and end with `>` so we throw an exception
 - `<http://example.org/graph1>` starts with `<` and ends with `>` so is fine
