### ISSUE TITLE
SHACL repo exception: casting blank nodes to IRIs

### ISSUE THREAD

**Issue by jakubklimek** [eclipse/rdf4j#1561]
When adding a SHACL rule to the SHACL rules named graph `http://rdf4j.org/schema/rdf4j#SHACLShapeGraph` in a `Memory store with SHACL` repository in both rdf4j 2.5.4 and rdf4j 3.0.0, I get an exception:
```
javax.servlet.ServletException: org.eclipse.rdf4j.repository.RepositoryException: class org.eclipse.rdf4j.sail.memory.model.MemBNode cannot be cast to class org.eclipse.rdf4j.model.IRI (org.eclipse.rdf4j.sail.memory.model.MemBNode and org.eclipse.rdf4j.model.IRI are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @3e2059ae)
```
The rule (one from [DCAT-AP v1.2.1 SHACL](http://joinup-prd-lb-01-1519654270.eu-west-1.elb.amazonaws.com/sites/default/files/distribution/access_url/2019-05/0da4d5d1-88fd-4b43-8783-9e85ef561a4e/dcat-ap_1.2.1_shacl.zip)):
```turtle
@prefix : <http://data.europa.eu/r5r/mandatory-classes#> .
@prefix dcat: <http://www.w3.org/ns/dcat#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

:MandatoryDataset a sh:NodeShape ;
    rdfs:label "Mandatory dataset" ;
    rdfs:comment "Mandatory dataset" ;
    sh:property [ sh:minCount 1 ;
            sh:path [ sh:inversePath rdf:type ] ] ;
    sh:targetNode dcat:Dataset .
```
The full exception:
```
Exception

javax.servlet.ServletException: org.eclipse.rdf4j.repository.RepositoryException: class org.eclipse.rdf4j.sail.memory.model.MemBNode cannot be cast to class org.eclipse.rdf4j.model.IRI (org.eclipse.rdf4j.sail.memory.model.MemBNode and org.eclipse.rdf4j.model.IRI are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @3e2059ae)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.handleRequest(WorkbenchServlet.java:140)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:103)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchGateway.service(WorkbenchGateway.java:114)
	org.eclipse.rdf4j.workbench.base.AbstractServlet.service(AbstractServlet.java:125)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	org.eclipse.rdf4j.workbench.proxy.CacheFilter.doFilter(CacheFilter.java:61)
	org.eclipse.rdf4j.workbench.proxy.CookieCacheControlFilter.doFilter(CookieCacheControlFilter.java:53)
Root Cause

org.eclipse.rdf4j.repository.RepositoryException: class org.eclipse.rdf4j.sail.memory.model.MemBNode cannot be cast to class org.eclipse.rdf4j.model.IRI (org.eclipse.rdf4j.sail.memory.model.MemBNode and org.eclipse.rdf4j.model.IRI are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @3e2059ae)
	org.eclipse.rdf4j.http.client.SPARQLProtocolSession.execute(SPARQLProtocolSession.java:1019)
	org.eclipse.rdf4j.http.client.SPARQLProtocolSession.executeNoContent(SPARQLProtocolSession.java:978)
	org.eclipse.rdf4j.http.client.RDF4JProtocolSession.upload(RDF4JProtocolSession.java:951)
	org.eclipse.rdf4j.http.client.RDF4JProtocolSession.upload(RDF4JProtocolSession.java:775)
	org.eclipse.rdf4j.http.client.RDF4JProtocolSession.upload(RDF4JProtocolSession.java:766)
	org.eclipse.rdf4j.repository.http.HTTPRepositoryConnection.add(HTTPRepositoryConnection.java:427)
	org.eclipse.rdf4j.workbench.commands.AddServlet.add(AddServlet.java:91)
	org.eclipse.rdf4j.workbench.commands.AddServlet.doPost(AddServlet.java:50)
	org.eclipse.rdf4j.workbench.base.TransformationServlet.service(TransformationServlet.java:93)
	org.eclipse.rdf4j.workbench.base.AbstractServlet.service(AbstractServlet.java:125)
	org.eclipse.rdf4j.workbench.proxy.ProxyRepositoryServlet.service(ProxyRepositoryServlet.java:99)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:188)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.handleRequest(WorkbenchServlet.java:128)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:103)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchGateway.service(WorkbenchGateway.java:114)
	org.eclipse.rdf4j.workbench.base.AbstractServlet.service(AbstractServlet.java:125)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	org.eclipse.rdf4j.workbench.proxy.CacheFilter.doFilter(CacheFilter.java:61)
	org.eclipse.rdf4j.workbench.proxy.CookieCacheControlFilter.doFilter(CookieCacheControlFilter.java:53)
```

However, when I substitute the blank nodes for IRIs like this, the validation goes through:
```turtle
@prefix : <http://data.europa.eu/r5r/mandatory-classes#> .
@prefix dcat: <http://www.w3.org/ns/dcat#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

:MandatoryDataset
  rdf:type sh:NodeShape ;
  rdfs:comment "Mandatory dataset" ;
  rdfs:label "Mandatory dataset" ;
  sh:targetNode dcat:Dataset ;
  sh:property :p .

:p sh:minCount 1 ;
   sh:path :path .
:path sh:inversePath rdf:type .
```

**Comment by barthanssens** [comment]
Indeed, also in console so not tied to workbench. Unsurprisingly I'm actually looking at the very same ruleset myself, so I'll dig into it.

**Comment by jakubklimek** [comment]
Yes, I actually first discovered this through LinkedPipes ETL, and only verified it later in workbench as I wanted to make sure that it is an rdf4j bug.

**Comment by barthanssens** [comment]
Underlying stack trace in console
```
Exception in thread "main" java.lang.ClassCastException: org.eclipse.rdf4j.sail.memory.model.MemBNode cannot be cast to org.eclipse.rdf4j.model.IRI
        at org.eclipse.rdf4j.sail.shacl.AST.PathPropertyShape.<init>(PathPropertyShape.java:43)
        at org.eclipse.rdf4j.sail.shacl.AST.MinCountPropertyShape.<init>(MinCountPropertyShape.java:50)
        at org.eclipse.rdf4j.sail.shacl.AST.PropertyShape$Factory.getPropertyShapesInner(PropertyShape.java:175)
        at org.eclipse.rdf4j.sail.shacl.AST.PropertyShape$Factory.lambda$getPropertyShapes$1(PropertyShape.java:159)
        at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at org.eclipse.rdf4j.common.iteration.IterationSpliterator.forEachRemaining(IterationSpliterator.java:67)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.collect(Unknown Source)
        at org.eclipse.rdf4j.sail.shacl.AST.PropertyShape$Factory.getPropertyShapes(PropertyShape.java:163)
        at org.eclipse.rdf4j.sail.shacl.AST.NodeShape.<init>(NodeShape.java:51)
        at org.eclipse.rdf4j.sail.shacl.AST.TargetNode.<init>(TargetNode.java:40)
        at org.eclipse.rdf4j.sail.shacl.AST.NodeShape$Factory.lambda$getShapes$0(NodeShape.java:164)
        at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at org.eclipse.rdf4j.common.iteration.IterationSpliterator.forEachRemaining(IterationSpliterator.java:67)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.collect(Unknown Source)
        at org.eclipse.rdf4j.sail.shacl.AST.NodeShape$Factory.getShapes(NodeShape.java:188)
        at org.eclipse.rdf4j.sail.shacl.ShaclSail.refreshShapes(ShaclSail.java:296)
        at org.eclipse.rdf4j.sail.shacl.ShaclSailConnection.refreshShapes(ShaclSailConnection.java:290)
        at org.eclipse.rdf4j.sail.shacl.ShaclSailConnection.prepare(ShaclSailConnection.java:544)
        at org.eclipse.rdf4j.repository.sail.SailRepositoryConnection.commit(SailRepositoryConnection.java:157)
```

**Comment by barthanssens** [comment]
A temporarily workaround could be loading the SHACL rules with a configured parser setting `BasicParserSettings.SKOLEMIZE_ORIGIN` to convert the blank nodes in the shapes to skolem URIs (and then setting it back to null before loading the data)

```
parser = Rio.createParser(RDFormat.TURTLE);
parser.getParserConfig().set(BasicParserSettings.SKOLEMIZE_ORIGIN, "http://example.com");
```

**Comment by hmottestad** [comment]
https://rdf4j.eclipse.org/documentation/programming/shacl/#supported-shacl-features

sh:path is limited to single predicate paths, eg. ex:age. Sequence paths, alternative paths, inverse paths and the like are not supported.

**Comment by hmottestad** [comment]
Should probably handle that exception better though.

**Comment by hmottestad** [comment]
Proposed fix: https://github.com/eclipse/rdf4j/pull/1571
