### ISSUE TITLE
Missing commons-logging / jcl-over-slf4j dependency for module rdf4j-repository-sparql

### ISSUE THREAD

**Issue by knoan** [eclipse/rdf4j#1617]
The Work.main() in the attached maven project with a BOM dependency on `rdf4j-repository-sparql` code fails to execute a query using a `SPARQLRepository` with:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
	at org.apache.http.conn.ssl.DefaultHostnameVerifier.<init>(DefaultHostnameVerifier.java:82)
	at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:966)
	at org.eclipse.rdf4j.http.client.SharedHttpClientSessionManager.createHttpClient(SharedHttpClientSessionManager.java:132)
	at org.eclipse.rdf4j.http.client.SharedHttpClientSessionManager.getHttpClient(SharedHttpClientSessionManager.java:92)
	at org.eclipse.rdf4j.http.client.SharedHttpClientSessionManager.createSPARQLProtocolSession(SharedHttpClientSessionManager.java:137)
	at org.eclipse.rdf4j.repository.sparql.SPARQLRepository.createHTTPClient(SPARQLRepository.java:138)
	at org.eclipse.rdf4j.repository.sparql.SPARQLRepository.getConnection(SPARQLRepository.java:154)
	at Work.main(Work.java:8)
```

To fix the following dependency must be manually included:

```
<dependency>
	<groupId>commons-logging</groupId>
	<artifactId>commons-logging</artifactId>
	<version>1.2</version>
</dependency>
```

[work.zip](https://github.com/eclipse/rdf4j/files/3742994/work.zip)

**Comment by jeenbroekstra** [comment]
This should not be part of the BOM, but should be one of the dependencies pulled in by the rdf4j-http-client (or at least, the jcl-over-slf4j bridge, rather than commons-logging itself). For some reason this dependency is currently defined as test-scoped.  

Related, I've noticed that the queryresultio-text module currently transitively pulls in commons-logging. That should probably be excluded and replaced with the same legacy bridge.
