### ISSUE TITLE
.IllegalArgumentException: datatype rdf:langString requires a language tag for Shacl shape literal with language tags

### ISSUE THREAD

**Issue by desislava-hristova-ontotext** [eclipse/rdf4j#1968]
Some Shacl Compliance tests in RDF4J fail with IllegalArgumentException: datatype rdf:langString requires a language tag bcause of wrong language tag transformation made by Shacl. See the full stack bellow. 

```j
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: datatype rdf:langString requires a language tag

	at org.eclipse.rdf4j.sail.shacl.ShaclSailConnection.lambda$performValidation$4(ShaclSailConnection.java:421)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.eclipse.rdf4j.sail.shacl.ShaclSailConnection.performValidation(ShaclSailConnection.java:424)
	at org.eclipse.rdf4j.sail.shacl.ShaclSailConnection.validate(ShaclSailConnection.java:313)
	at org.eclipse.rdf4j.sail.shacl.ShaclSailConnection.prepare(ShaclSailConnection.java:626)
	at org.eclipse.rdf4j.repository.sail.SailRepositoryConnection.commit(SailRepositoryConnection.java:157)
	at org.eclipse.rdf4j.repository.base.AbstractRepositoryConnection.conditionalCommit(AbstractRepositoryConnection.java:323)
	at org.eclipse.rdf4j.repository.base.AbstractRepositoryConnection.add(AbstractRepositoryConnection.java:377)
	at org.eclipse.rdf4j.shacl.manifest.AbstractSHACLTest.createRepository(AbstractSHACLTest.java:85)
	at org.eclipse.rdf4j.shacl.manifest.AbstractSHACLTest.setUp(AbstractSHACLTest.java:75)
	at junit.framework.TestCase.runBare(TestCase.java:139)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.eclipse.rdf4j.shacl.manifest.SHACLManifestTestSuiteFactory$1.run(SHACLManifestTestSuiteFactory.java:109)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: datatype rdf:langString requires a language tag
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.eclipse.rdf4j.sail.shacl.ShaclSailConnection.lambda$performValidation$4(ShaclSailConnection.java:419)
	... 31 more
Caused by: java.lang.IllegalArgumentException: datatype rdf:langString requires a language tag
	at org.eclipse.rdf4j.model.impl.SimpleLiteral.<init>(SimpleLiteral.java:94)
	at org.eclipse.rdf4j.model.impl.AbstractValueFactory.createLiteral(AbstractValueFactory.java:116)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:2467)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:106)
	at org.eclipse.rdf4j.query.parser.sparql.ast.ASTRDFLiteral.jjtAccept(ASTRDFLiteral.java:26)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:2395)
	at org.eclipse.rdf4j.query.parser.sparql.ast.ASTBind.jjtAccept(ASTBind.java:25)
	at org.eclipse.rdf4j.query.parser.sparql.ast.SimpleNode.childrenAccept(SimpleNode.java:152)
	at org.eclipse.rdf4j.query.parser.sparql.AbstractASTVisitor.visit(AbstractASTVisitor.java:231)
	at org.eclipse.rdf4j.query.parser.sparql.ast.ASTBasicGraphPattern.jjtAccept(ASTBasicGraphPattern.java:24)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:1022)
	at org.eclipse.rdf4j.query.parser.sparql.ast.ASTGraphPatternGroup.jjtAccept(ASTGraphPatternGroup.java:24)
	at org.eclipse.rdf4j.query.parser.sparql.ast.SimpleNode.childrenAccept(SimpleNode.java:152)
	at org.eclipse.rdf4j.query.parser.sparql.AbstractASTVisitor.visit(AbstractASTVisitor.java:730)
	at org.eclipse.rdf4j.query.parser.sparql.ast.ASTWhereClause.jjtAccept(ASTWhereClause.java:24)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:222)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:106)
	at org.eclipse.rdf4j.query.parser.sparql.ast.ASTSelectQuery.jjtAccept(ASTSelectQuery.java:24)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:1022)
	at org.eclipse.rdf4j.query.parser.sparql.ast.ASTGraphPatternGroup.jjtAccept(ASTGraphPatternGroup.java:24)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:1022)
	at org.eclipse.rdf4j.query.parser.sparql.ast.ASTGraphPatternGroup.jjtAccept(ASTGraphPatternGroup.java:24)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:1105)
	at org.eclipse.rdf4j.query.parser.sparql.ast.ASTUnionGraphPattern.jjtAccept(ASTUnionGraphPattern.java:24)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:1022)
	at org.eclipse.rdf4j.query.parser.sparql.ast.ASTGraphPatternGroup.jjtAccept(ASTGraphPatternGroup.java:24)
	at org.eclipse.rdf4j.query.parser.sparql.ast.SimpleNode.childrenAccept(SimpleNode.java:152)
	at org.eclipse.rdf4j.query.parser.sparql.AbstractASTVisitor.visit(AbstractASTVisitor.java:730)
	at org.eclipse.rdf4j.query.parser.sparql.ast.ASTWhereClause.jjtAccept(ASTWhereClause.java:24)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:222)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:106)
	at org.eclipse.rdf4j.query.parser.sparql.ast.ASTSelectQuery.jjtAccept(ASTSelectQuery.java:24)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:213)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:106)
	at org.eclipse.rdf4j.query.parser.sparql.ast.ASTQueryContainer.jjtAccept(ASTQueryContainer.java:26)
	at org.eclipse.rdf4j.query.parser.sparql.SPARQLParser.buildQueryModel(SPARQLParser.java:186)
	at org.eclipse.rdf4j.query.parser.sparql.SPARQLParser.parseQuery(SPARQLParser.java:151)
	at org.eclipse.rdf4j.sail.shacl.planNodes.Select$1.<init>(Select.java:63)
	at org.eclipse.rdf4j.sail.shacl.planNodes.Select.iterator(Select.java:52)
	at org.eclipse.rdf4j.sail.shacl.planNodes.BufferedSplitter.init(BufferedSplitter.java:44)
	at org.eclipse.rdf4j.sail.shacl.planNodes.BufferedSplitter.access$000(BufferedSplitter.java:29)
	at org.eclipse.rdf4j.sail.shacl.planNodes.BufferedSplitter$1.iterator(BufferedSplitter.java:67)
	at org.eclipse.rdf4j.sail.shacl.planNodes.TrimTuple$1.<init>(TrimTuple.java:36)
	at org.eclipse.rdf4j.sail.shacl.planNodes.TrimTuple.iterator(TrimTuple.java:34)
	at org.eclipse.rdf4j.sail.shacl.planNodes.Unique$1.<init>(Unique.java:41)
	at org.eclipse.rdf4j.sail.shacl.planNodes.Unique.iterator(Unique.java:39)
	at org.eclipse.rdf4j.sail.shacl.planNodes.BufferedSplitter.init(BufferedSplitter.java:44)
	at org.eclipse.rdf4j.sail.shacl.planNodes.BufferedSplitter.access$000(BufferedSplitter.java:29)
	at org.eclipse.rdf4j.sail.shacl.planNodes.BufferedSplitter$1.iterator(BufferedSplitter.java:67)
	at org.eclipse.rdf4j.sail.shacl.planNodes.ModifyTuple$1.<init>(ModifyTuple.java:31)
	at org.eclipse.rdf4j.sail.shacl.planNodes.ModifyTuple.iterator(ModifyTuple.java:29)
	at org.eclipse.rdf4j.sail.shacl.planNodes.FilterPlanNode$1.calculateNext(FilterPlanNode.java:80)
	at org.eclipse.rdf4j.sail.shacl.planNodes.FilterPlanNode$1.hasNext(FilterPlanNode.java:133)
	at org.eclipse.rdf4j.sail.shacl.planNodes.FilterPlanNode.incrementIterator(FilterPlanNode.java:203)
	at org.eclipse.rdf4j.sail.shacl.planNodes.UnBufferedPlanNode$1.calculateNext(UnBufferedPlanNode.java:60)
	at org.eclipse.rdf4j.sail.shacl.planNodes.UnBufferedPlanNode$1.hasNext(UnBufferedPlanNode.java:54)
	at org.eclipse.rdf4j.sail.shacl.planNodes.EnrichWithShape$1.localHasNext(EnrichWithShape.java:43)
	at org.eclipse.rdf4j.sail.shacl.planNodes.LoggingCloseableIteration.hasNext(LoggingCloseableIteration.java:46)
	at org.eclipse.rdf4j.common.iteration.IterationSpliterator.forEachRemaining(IterationSpliterator.java:74)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.eclipse.rdf4j.sail.shacl.ShaclSailConnection.lambda$null$2(ShaclSailConnection.java:375)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

Seems that the Select created by Shacl sail has invalid datatype:

```
select ?a ?c where { {{ select * where {BIND("Hallo"^^<http://www.w3.org/1999/02/22-rdf-syntax-ns#langString> as ?a). ?a ?b1 ?c .}}}
 UNION 
{{ select * where {BIND("Hallo"^^<http://www.w3.org/1999/02/22-rdf-syntax-ns#langString> as ?a). ?c ?b1 ?a .}}} UNION {{ select * where {BIND("<span>Hello</span>"^^<http://www.w3.org/1999/02/22-rdf-syntax-ns#HTML> as ?a). ?a ?b1 ?c .}}}
 UNION 
{{ select * where {BIND("<span>Hello</span>"^^<http://www.w3.org/1999/02/22-rdf-syntax-ns#HTML> as ?a). ?c ?b1 ?a .}}} UNION {{ select * where {BIND("Hello"^^<http://www.w3.org/2001/XMLSchema#string> as ?a). ?a ?b1 ?c .}}}
 UNION 
{{ select * where {BIND("Hello"^^<http://www.w3.org/2001/XMLSchema#string> as ?a). ?c ?b1 ?a .}}} UNION {{ select * where {BIND("G'day"^^<http://www.w3.org/1999/02/22-rdf-syntax-ns#langString> as ?a). ?a ?b1 ?c .}}}
 UNION 
{{ select * where {BIND("G'day"^^<http://www.w3.org/1999/02/22-rdf-syntax-ns#langString> as ?a). ?c ?b1 ?a .}}}} order by ?a
```
when a literal in the shape has a language tag, i.e 
`  sh:targetNode "G'day"@en-AU ;
  sh:targetNode "Hallo"@de ;`
 in test datatype-002.ttl

**Comment by hmottestad** [comment]
@desislava-hristova-ontotext thanks for pointing this out, I actually have a fix for this in a branch I'm working on that also aims to fix targetNode in combination with minCount where the target node is not present. Still WIP. Here is the fix for the language issue: https://github.com/eclipse/rdf4j/blob/3d00a40922c7c056e9fcbf92b20f48fcd760d2de/core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/AST/TargetNode.java#L95
