### ISSUE TITLE
Deadlock on a query across services on the same server

### ISSUE THREAD

**Issue by ledsoft** [eclipse/rdf4j#2040]
When I run a query which uses `OPTIONAL SERVICE` requests to repositories on the same server as the repository on which the query is run, two threads apparently become deadlocked on the `QueueIteration`, one attempting to `put` into the queue, while the other tries to `getNextElement` from it. I uploaded test data (repositories folder which can be dropped into the .RDF4J folder, the problematic query and a thread dump showing the deadlock) which should reproduce the issue to [Google Drive](https://drive.google.com/file/d/1HECGjO4xg3ugM6aL1dn3Pu1PDzS2xiVn/view?usp=sharing).

The problem is apparently with the `SERVICE` calls. If I remove them, the query runs without any issues.

I reproduced it on RDF4J 3.1.2, 3.1.1 and 2.5.x, various Tomcat versions, JDK 8 (HotSpot). Also tried on GraphDB Free 9.1.1 and it does not have this problem.

The query, for reference, is as follows (it is a simplified version of a more complex query we use):
```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ufo: <http://onto.fel.cvut.cz/ontologies/ufo/>
PREFIX doc: <http://onto.fel.cvut.cz/ontologies/documentation/>
PREFIX aso: <http://onto.fel.cvut.cz/ontologies/aviation-safety/>
PREFIX rt: <http://onto.fel.cvut.cz/ontologies/reporting-tool/>
PREFIX er: <http://localhost:8080/rdf4j-server/repositories/>

SELECT ?event_type ?relation_type ?factor_type (COUNT(DISTINCT *) AS ?count) {
  ?report doc:documents ?occurrence .
  ?occurrence ufo:has_part+ ?ct ;
  aso:has_start_time ?start_time ;
  aso:has_end_time ?end_time .

  FILTER (?start_time >= "1900-01-01T00:00:00.0"^^xsd:dateTime && ?end_time <= NOW())

    ?ct rt:has_event_type <http://onto.fel.cvut.cz/ontologies/eccairs/aviation-3.4.0.2/vl-a-390/v-99010622> .
      {
        ?ft rt:has_event_type ?event_f_t;
            aso:has_factor+ ?ct.
      } UNION {
        BIND(?ct AS ?ft)
        BIND(?central_type AS ?event_f_t)
      }

      OPTIONAL { SERVICE SILENT er:model { ?event_f_t rdfs:label ?factor_type_label. } }
      OPTIONAL {
        [rt:has_event_type ?event_e_t] aso:has_factor [
          a ?rt ;
          aso:has_factor ?ft
        ]
        FILTER (?rt != aso:factor)
        OPTIONAL { SERVICE SILENT er:model { ?event_e_t rdfs:label ?event_type_label. } }
        OPTIONAL { SERVICE SILENT er:model        { ?rt rdfs:label ?relation_type_label. } }
      }

  BIND(COALESCE(COALESCE(?event_type_label, ?event_e_t),"NONE") AS ?event_type)
  BIND(COALESCE(COALESCE(?factor_type_label, ?event_f_t),"NONE") AS ?factor_type)
  BIND(COALESCE(COALESCE(?relation_type_label, ?rt),"NONE") AS ?relation_type)
}
GROUP BY ?event_type ?relation_type ?factor_type
ORDER BY desc(?count) asc(?event_type)
```

Relevant parts of the stack traces:
```
"rdf4j-sesameclientimpl-5" #54 daemon prio=5 os_prio=0 tid=0x00007f2ec8356000 nid=0x426c waiting on condition [0x00007f2f2bbfd000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000077dfb9dc8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ArrayBlockingQueue.offer(ArrayBlockingQueue.java:379)
	at org.eclipse.rdf4j.common.iteration.QueueIteration.put(QueueIteration.java:85)
	at org.eclipse.rdf4j.query.resultio.helpers.BackgroundTupleResult.handleSolution(BackgroundTupleResult.java:111)
	at org.eclipse.rdf4j.query.resultio.sparqlxml.SPARQLResultsSAXParser.endTag(SPARQLResultsSAXParser.java:164)
	at org.eclipse.rdf4j.common.xml.SimpleSAXParser$SimpleSAXDefaultHandler.endElement(SimpleSAXParser.java:302)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.eclipse.rdf4j.common.xml.SimpleSAXParser.parse(SimpleSAXParser.java:197)
	- locked <0x00000007809c89d0> (a org.eclipse.rdf4j.common.xml.SimpleSAXParser)
	at org.eclipse.rdf4j.common.xml.SimpleSAXParser.parse(SimpleSAXParser.java:178)
	at org.eclipse.rdf4j.query.resultio.sparqlxml.AbstractSPARQLXMLParser.parseQueryResultInternal(AbstractSPARQLXMLParser.java:187)
	at org.eclipse.rdf4j.query.resultio.sparqlxml.SPARQLResultsXMLParser.parseQueryResult(SPARQLResultsXMLParser.java:73)
	at org.eclipse.rdf4j.query.resultio.helpers.BackgroundTupleResult.run(BackgroundTupleResult.java:89)
	at org.eclipse.rdf4j.http.client.BackgroundResultExecutor.lambda$autoCloseRunnable$0(BackgroundResultExecutor.java:65)
	at org.eclipse.rdf4j.http.client.BackgroundResultExecutor$$Lambda$133/1429043754.run(Unknown Source)
```

```
"repositories/reports-akaene-inbas" #24 daemon prio=5 os_prio=0 tid=0x00007f2f552fc000 nid=0x408c waiting on condition [0x00007f2f32069000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000077dfe29c8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:403)
	at org.eclipse.rdf4j.common.iteration.QueueIteration.getNextElement(QueueIteration.java:127)
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:81)
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:49)
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63)
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63)
	at org.eclipse.rdf4j.repository.sparql.federation.RepositoryFederatedService$CloseConnectionIteration.hasNext(RepositoryFederatedService.java:144)
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63)
	at org.eclipse.rdf4j.common.iteration.SilentIteration.hasNext(SilentIteration.java:31)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.LeftJoinIterator.getNextElement(LeftJoinIterator.java:78)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.LeftJoinIterator.getNextElement(LeftJoinIterator.java:23)
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:81)
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:49)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.LeftJoinIterator.getNextElement(LeftJoinIterator.java:67)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.LeftJoinIterator.getNextElement(LeftJoinIterator.java:23)
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:81)
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:49)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.LeftJoinIterator.getNextElement(LeftJoinIterator.java:78)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.LeftJoinIterator.getNextElement(LeftJoinIterator.java:23)
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:81)
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:49)
	at org.eclipse.rdf4j.common.iteration.ConvertingIteration.hasNext(ConvertingIteration.java:62)
	at org.eclipse.rdf4j.common.iteration.ConvertingIteration.hasNext(ConvertingIteration.java:62)
	at org.eclipse.rdf4j.common.iteration.ConvertingIteration.hasNext(ConvertingIteration.java:62)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.GroupIterator.buildEntries(GroupIterator.java:211)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.GroupIterator.createIterator(GroupIterator.java:167)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.GroupIterator.hasNext(GroupIterator.java:126)
	- locked <0x00000007bc94bde8> (a java.lang.Object)
	at org.eclipse.rdf4j.common.iteration.ConvertingIteration.hasNext(ConvertingIteration.java:62)
	at org.eclipse.rdf4j.common.iteration.ConvertingIteration.hasNext(ConvertingIteration.java:62)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.OrderIterator.createIteration(OrderIterator.java:277)
	at org.eclipse.rdf4j.common.iteration.DelayedIteration.hasNext(DelayedIteration.java:62)
	- locked <0x00000007bc69ff10> (a org.eclipse.rdf4j.query.algebra.evaluation.iterator.OrderIterator)
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63)
	at org.eclipse.rdf4j.sail.base.SailClosingIteration.hasNext(SailClosingIteration.java:81)
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63)
	at org.eclipse.rdf4j.sail.helpers.SailBaseIteration.hasNext(SailBaseIteration.java:41)
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63)
	at org.eclipse.rdf4j.query.QueryResults.report(QueryResults.java:231)
	at org.eclipse.rdf4j.http.server.repository.TupleQueryResultView.renderInternal(TupleQueryResultView.java:99)
	at org.eclipse.rdf4j.http.server.repository.QueryResultView.render(QueryResultView.java:63)
```

**Comment by jeenbroekstra** [comment]
I _think_ a possible cause is QueueIteration line 127, which blocks indefinitely  until an item becomes available. Apparently this deadlocks the offer method. That has a timeout, and a loop to keep trying, but since the lock never ceases it never gets to insert an item in the queue. 

If that is the issue, the solution might be to introduce a timed take on 127, with a similar loop construct.

**Comment by jeenbroekstra** [comment]
> I _think_ a possible cause is QueueIteration line 127, which blocks indefinitely until an item becomes available. Apparently this deadlocks the offer method. That has a timeout, and a loop to keep trying, but since the lock never ceases it never gets to insert an item in the queue.
> 
> If that is the issue, the solution might be to introduce a timed take on 127, with a similar loop construct.

Took a slightly closer look and this does not appear to be the issue. The calls to take and offer do not block each other - they are simply both waiting for a condition to be fulfilled. We'll need to dive in closer as to why those conditions are never met in this case, but my current hunch is that the two threads we're looking at here are not necessarily operating on the same queue, and there is some dance going on between the various queues (for earch service clause).

**Comment by jeenbroekstra** [comment]
Question: I've noticed that for the first service clause in your query, the variable `?event_f_t` may be unbound. This is because in the right args of UNION clause before it, this variable is bound to the value of `?central_type`, but this variable is itself never bound. 

The consequence of this is that your first SERVICE clause effectively retrieves _all_ label-statements from your model repository - so it significantly blows up the query result.

Is the intent that `?central_type` has the value `<http://onto.fel.cvut.cz/ontologies/eccairs/aviation-3.4.0.2/vl-a-390/v-99010622>`? Reason I ask is that if I substitute that, the query runs as expected.

**Comment by ledsoft** [comment]
Jeen, you are absolutely right! `?central_type` was supposed to be bound using `VALUES`, I messed it up when preparing the simplified version of the query. The query should look like:
```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

PREFIX ufo: <http://onto.fel.cvut.cz/ontologies/ufo/>
PREFIX doc: <http://onto.fel.cvut.cz/ontologies/documentation/>
PREFIX aso: <http://onto.fel.cvut.cz/ontologies/aviation-safety/>
PREFIX rt: <http://onto.fel.cvut.cz/ontologies/reporting-tool/>

PREFIX er: <http://localhost:8080/rdf4j-server/repositories/>

SELECT ?event_type ?relation_type ?factor_type (COUNT(DISTINCT *) AS ?count) {
  VALUES ( ?central_type ) { ( <http://onto.fel.cvut.cz/ontologies/eccairs/aviation-3.4.0.2/vl-a-390/v-5020100>) }
  ?report doc:documents ?occurrence .
  ?occurrence ufo:has_part+ ?ct ;
  aso:has_start_time ?start_time ;
  aso:has_end_time ?end_time .

  FILTER (?start_time >= "1900-01-01T00:00:00.0"^^xsd:dateTime && ?end_time <= NOW())

    ?ct rt:has_event_type ?central_type .
      {
        ?ft rt:has_event_type ?event_f_t;
            aso:has_factor+ ?ct.
      } UNION {
        BIND(?ct AS ?ft)
        BIND(?central_type AS ?event_f_t)
      }

      OPTIONAL { SERVICE SILENT er:model { ?event_f_t rdfs:label ?factor_type_label. } }
      OPTIONAL {
        [rt:has_event_type ?event_e_t] aso:has_factor [
          a ?rt ;
          aso:has_factor ?ft
        ]
        FILTER (?rt != aso:factor)
        OPTIONAL { SERVICE SILENT er:model { ?event_e_t rdfs:label ?event_type_label. } }
        OPTIONAL { SERVICE SILENT er:model        { ?rt rdfs:label ?relation_type_label. } }
      }

  BIND(COALESCE(COALESCE(?event_type_label, ?event_e_t),"NONE") AS ?event_type)
  BIND(COALESCE(COALESCE(?factor_type_label, ?event_f_t),"NONE") AS ?factor_type)
  BIND(COALESCE(COALESCE(?relation_type_label, ?rt),"NONE") AS ?relation_type)
}
GROUP BY ?event_type ?relation_type ?factor_type
ORDER BY desc(?count) asc(?event_type)
```
If I run it like this, the problem is still the same. But now when I'm looking at it and based on your comment about the query loading all labels, could the problem be bad scope of the `VALUES` block? Joshua Taylor's answer to [this SO question](https://stackoverflow.com/questions/35627447/what-is-the-scope-of-values-in-sparql-query-graph) would suggest so...

**Comment by jeenbroekstra** [comment]
Ah. Yes, that's likely the problem - a UNION is a scoped group, and the VALUES clause is outside that group - so `?event_ft` is never bound to anything in the right hand arg of the union (in fact, neither is `?ft` of course). 

This probably also explains why it works on GraphDB as their SPARQL engine allows injection of values clauses into subgroups (this is not standards-compliant, but sometimes practical). 

I won't pretend it's pretty but something like this might solve your issue:
```
VALUES ( ?central_type ) { ( <http://onto.fel.cvut.cz/ontologies/eccairs/aviation-3.4.0.2/vl-a-390/v-5020100>) }
?ct rt:has_event_type ?central_type .
OPTIONAL {
            ?optional_ft rt:has_event_type ?optional_event_f_t;
                                aso:has_factor+ ?ct.
}
BIND(COALESCE(?optional_ft, ?ct) as ?ft)
BIND(COALESCE(?optional_event_f_t, ?central_type) as ?event_f_t)
```

As an aside: COALESCE takes multiple input arguments so you can simplify this:

    BIND(COALESCE(COALESCE(?event_type_label, ?event_e_t),"NONE") AS ?event_type)

to this:

    BIND(COALESCE(?event_type_label, ?event_e_t, "NONE") AS ?event_type)

**Comment by ledsoft** [comment]
Jeen, thank you so much, moving the `VALUES` inwards fixed the query and it finishes now in no time.  Thanks for the `COALESCE` tip, I didn't know that:)
I'm closing the issue, sorry for the false alarm.
