### ISSUE TITLE
configure timeout for rdf client

### ISSUE THREAD

**Issue by antonkulaga** [eclipse/rdf4j#2074]
When I run a long-running query i.e.
```scala
val serverURL: String ="http://10.40.3.21:7200/" //path to GRAPHDB
val repositoryManager = new RemoteRepositoryManager( serverURL )
repositoryManager.init()
val repository = repositoryManager.getRepository("ensembl")
val con: RepositoryConnection = repository.getConnection()
val results = con.prepareTupleQuery(query).evaluate().toVector
```
which is supposed to run many minutes I often get timeout exceptions from the client, while when I run the same query via GraphDB workbench things take 10 minutes but the query is not interupted. . It is totally unclear for me how to configure http-client in repository Manager to make it run for 10 and more minutes. I cound not find it in documentation :(

**Comment by jeenbroekstra** [comment]
By default the client should be configured to not have a fixed timeout. What exact error (stacktrace) are you getting?

**Comment by antonkulaga** [comment]
@jeenbroekstra I have
```
Exception in thread "main" org.eclipse.rdf4j.repository.http.HTTPQueryEvaluationException: Connection reset by peer (Write failed)
	at org.eclipse.rdf4j.repository.http.HTTPTupleQuery.evaluate(HTTPTupleQuery.java:49)
Caused by: java.net.SocketException: Connection reset by peer (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:124)
	at org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:160)
	at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:113)
	at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:120)
	at org.apache.http.entity.StringEntity.writeTo(StringEntity.java:167)
	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156)
	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:152)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.execute(SPARQLProtocolSession.java:986)
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.executeOK(SPARQLProtocolSession.java:950)
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.sendTupleQueryViaHttp(SPARQLProtocolSession.java:747)
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.getBackgroundTupleQueryResult(SPARQLProtocolSession.java:649)
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.sendTupleQuery(SPARQLProtocolSession.java:364)
	at org.eclipse.rdf4j.repository.http.HTTPTupleQuery.evaluate(HTTPTupleQuery.java:46)
```
It happens when I send large sparql queries with tens of thousands of bindings to be returned.
In my case I ask for gene expressions, when I ask for 1K genes in 50 samples it is ok, but when I ask for 20K in 50 samples it crashes.

**Comment by jeenbroekstra** [comment]
Looks like a socket timeout while waiting for a response. Peculiar as even on a large query (with a large result) it should stream the response, and shouldn't time out.

To answer your original question: there are several ways you can tweak the httpclient configuration, here's a code snippet for one way:

		HTTPRepository repository;
		SharedHttpClientSessionManager manager = (SharedHttpClientSessionManager) repository.getHttpClientSessionManager();

		int timeout = 10 * 60 * 1000; // socket timeout in ms. Set to 0 for infinite wait
		RequestConfig defaultRequestConfig = RequestConfig.custom()
				.setCookieSpec(CookieSpecs.STANDARD)
		        .setSocketTimeout(timeout)
		        .build();

		HttpClientBuilder httpClientBuilder = HttpClients
				.custom()
				.setDefaultRequestConfig(defaultRequestConfig);

		manager.setHttpClientBuilder(httpClientBuilder);

If you do this on a newly created HTTPRepository, it should use your custom request configuration for all requests. 

Can you let me know if either setting a larger timeout (or even setting it explicitly to 0) solves the issue?
