### ISSUE TITLE
QueryEvaluationException: Unknown function 'http://www.w3.org/2001/XMLSchema#date'

### ISSUE THREAD

**Issue by D063520** [eclipse/rdf4j#2090]
Hello!

I'm using rdf4j by importing the following dependency:

```
<dependency>
            <groupId>org.eclipse.rdf4j</groupId>
            <artifactId>rdf4j-runtime</artifactId>
            <version>3.1.3</version>
            <type>pom</type>
</dependency>
```

When I query something like:

```
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix my: <>
select ?date where { 
  my:Q53036 my:P20 ?startT. 
  bind(xsd:date(concat(str(year(?startT)),"-",
                       str(month(?startT)),"-",
                       str(day(?startT))))
  as ?date)
} 
```

i get:

```
Caused by: org.eclipse.rdf4j.query.QueryEvaluationException: Unknown function 'http://www.w3.org/2001/XMLSchema#date'
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategy.lambda$evaluate$0(StrictEvaluationStrategy.java:1478)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategy$$Lambda$937/300383439.get(Unknown Source)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategy.evaluate(StrictEvaluationStrategy.java:1478)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategy.evaluate(StrictEvaluationStrategy.java:1011)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.ExtensionIterator.convert(ExtensionIterator.java:47)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.ExtensionIterator.convert(ExtensionIterator.java:23)
	at org.eclipse.rdf4j.common.iteration.ConvertingIteration.next(ConvertingIteration.java:81)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.LeftJoinIterator.getNextElement(LeftJoinIterator.java:79)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.LeftJoinIterator.getNextElement(LeftJoinIterator.java:23)
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:81)
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:49)
```

is something missing in the bundle?

Thank you
D063520

**Comment by damyan-ognyanov** [comment]
There is no `xsd:date` function in RDF4J nor in SPARQL. If you like to construct a literal with a specific datatype use `STRDT()`

**Comment by D063520** [comment]
oh, I see ..... sorry my mistake!
