### ISSUE TITLE
Parallel upgrading of DynamicModel can cause NullPointerException

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#2211]
```
2020-05-10T20:06:47.1141940Z ----------------------------------------------------------------------
2020-05-10T20:06:47.1142203Z Class: java.util.concurrent.ExecutionException
2020-05-10T20:06:47.1142435Z Message: java.lang.NullPointerException
2020-05-10T20:06:47.1142674Z java.util.concurrent.ExecutionException: java.lang.NullPointerException
2020-05-10T20:06:47.1143116Z 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
2020-05-10T20:06:47.1144095Z 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
2020-05-10T20:06:47.1145921Z 	at org.eclipse.rdf4j.sail.shacl.MultithreadedTest.lambda$runValidationFailuresTest$5(MultithreadedTest.java:503)
2020-05-10T20:06:47.1146692Z 	at java.util.ArrayList.forEach(ArrayList.java:1257)
2020-05-10T20:06:47.1148431Z 	at org.eclipse.rdf4j.sail.shacl.MultithreadedTest.runValidationFailuresTest(MultithreadedTest.java:501)
2020-05-10T20:06:47.1150328Z 	at org.eclipse.rdf4j.sail.shacl.MultithreadedTest.testLotsOfValidationFailuresSerializable(MultithreadedTest.java:372)
2020-05-10T20:06:47.1151265Z 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
2020-05-10T20:06:47.1152951Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-05-10T20:06:47.1153729Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-05-10T20:06:47.1155184Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
2020-05-10T20:06:47.1156586Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2020-05-10T20:06:47.1157921Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
2020-05-10T20:06:47.1159301Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2020-05-10T20:06:47.1160581Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2020-05-10T20:06:47.1161907Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2020-05-10T20:06:47.1162956Z 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
2020-05-10T20:06:47.1164343Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
2020-05-10T20:06:47.1165658Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
2020-05-10T20:06:47.1166683Z 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
2020-05-10T20:06:47.1167851Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
2020-05-10T20:06:47.1168969Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
2020-05-10T20:06:47.1170075Z 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
2020-05-10T20:06:47.1171149Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
2020-05-10T20:06:47.1172091Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
2020-05-10T20:06:47.1172906Z 	at org.junit.runners.Suite.runChild(Suite.java:128)
2020-05-10T20:06:47.1173725Z 	at org.junit.runners.Suite.runChild(Suite.java:27)
2020-05-10T20:06:47.1174690Z 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
2020-05-10T20:06:47.1175765Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
2020-05-10T20:06:47.1176626Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
2020-05-10T20:06:47.1177670Z 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
2020-05-10T20:06:47.1178719Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
2020-05-10T20:06:47.1179996Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2020-05-10T20:06:47.1180968Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
2020-05-10T20:06:47.1182367Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
2020-05-10T20:06:47.1183936Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
2020-05-10T20:06:47.1185171Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
2020-05-10T20:06:47.1186449Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
2020-05-10T20:06:47.1188150Z 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
2020-05-10T20:06:47.1189609Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
2020-05-10T20:06:47.1190873Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
2020-05-10T20:06:47.1210296Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
2020-05-10T20:06:47.1218231Z Caused by: java.lang.NullPointerException
2020-05-10T20:06:47.1223978Z 	at org.eclipse.rdf4j.model.impl.DynamicModel.contains(DynamicModel.java:197)
2020-05-10T20:06:47.1229102Z 	at org.eclipse.rdf4j.sail.base.SailDatasetImpl$3.accept(SailDatasetImpl.java:331)
2020-05-10T20:06:47.1315515Z 	at org.eclipse.rdf4j.sail.base.SailDatasetImpl$3.accept(SailDatasetImpl.java:327)
2020-05-10T20:06:47.1328436Z 	at org.eclipse.rdf4j.common.iteration.FilterIteration.findNextElement(FilterIteration.java:77)
2020-05-10T20:06:47.1333846Z 	at org.eclipse.rdf4j.common.iteration.FilterIteration.hasNext(FilterIteration.java:45)
2020-05-10T20:06:47.1357074Z 	at org.eclipse.rdf4j.sail.base.DistinctModelReducingUnionIteration.getNextElement(DistinctModelReducingUnionIteration.java:53)
2020-05-10T20:06:47.1364572Z 	at org.eclipse.rdf4j.sail.base.DistinctModelReducingUnionIteration.getNextElement(DistinctModelReducingUnionIteration.java:34)
2020-05-10T20:06:47.1370321Z 	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:81)
2020-05-10T20:06:47.1375944Z 	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:49)
2020-05-10T20:06:47.1381261Z 	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63)
2020-05-10T20:06:47.1386349Z 	at org.eclipse.rdf4j.sail.base.SailClosingIteration.hasNext(SailClosingIteration.java:81)
2020-05-10T20:06:47.1436279Z 	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63)
2020-05-10T20:06:47.1442292Z 	at org.eclipse.rdf4j.sail.helpers.SailBaseIteration.hasNext(SailBaseIteration.java:41)
2020-05-10T20:06:47.1447273Z 	at org.eclipse.rdf4j.sail.SailConnection.hasStatement(SailConnection.java:152)
2020-05-10T20:06:47.1453986Z 	at org.eclipse.rdf4j.sail.shacl.ShaclSailConnection.hasStatement(ShaclSailConnection.java:753)
2020-05-10T20:06:47.1459142Z 	at org.eclipse.rdf4j.sail.shacl.ConnectionHelper.isEmpty(ConnectionHelper.java:67)
2020-05-10T20:06:47.1464630Z 	at org.eclipse.rdf4j.sail.shacl.ShaclSailConnection.isEmpty(ShaclSailConnection.java:758)
2020-05-10T20:06:47.1470103Z 	at org.eclipse.rdf4j.sail.shacl.ShaclSailConnection.prepare(ShaclSailConnection.java:583)
2020-05-10T20:06:47.1476510Z 	at org.eclipse.rdf4j.repository.sail.SailRepositoryConnection.commit(SailRepositoryConnection.java:161)
2020-05-10T20:06:47.1482132Z 	at org.eclipse.rdf4j.sail.shacl.MultithreadedTest.lambda$null$3(MultithreadedTest.java:450)
2020-05-10T20:06:47.1486839Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-05-10T20:06:47.1490785Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-05-10T20:06:47.1496144Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-05-10T20:06:47.1501254Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-05-10T20:06:47.1504207Z 	at java.lang.Thread.run(Thread.java:748)
2020-05-10T20:06:47.1505000Z 
2020-05-10T20:06:47.1509922Z ----------------------------------------------------------------------
2020-05-10T20:06:47.1512862Z Class: java.lang.NullPointerException
2020-05-10T20:06:47.1514335Z Message: null
2020-05-10T20:06:47.1518659Z java.lang.NullPointerException
2020-05-10T20:06:47.1523535Z 	at org.eclipse.rdf4j.model.impl.DynamicModel.contains(DynamicModel.java:197)
2020-05-10T20:06:47.1528992Z 	at org.eclipse.rdf4j.sail.base.SailDatasetImpl$3.accept(SailDatasetImpl.java:331)
2020-05-10T20:06:47.1534085Z 	at org.eclipse.rdf4j.sail.base.SailDatasetImpl$3.accept(SailDatasetImpl.java:327)
2020-05-10T20:06:47.1539901Z 	at org.eclipse.rdf4j.common.iteration.FilterIteration.findNextElement(FilterIteration.java:77)
2020-05-10T20:06:47.1548723Z 	at org.eclipse.rdf4j.common.iteration.FilterIteration.hasNext(FilterIteration.java:45)
2020-05-10T20:06:47.1561337Z 	at org.eclipse.rdf4j.sail.base.DistinctModelReducingUnionIteration.getNextElement(DistinctModelReducingUnionIteration.java:53)
2020-05-10T20:06:47.1651933Z 	at org.eclipse.rdf4j.sail.base.DistinctModelReducingUnionIteration.getNextElement(DistinctModelReducingUnionIteration.java:34)
2020-05-10T20:06:47.1652821Z 	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:81)
2020-05-10T20:06:47.1653601Z 	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:49)
2020-05-10T20:06:47.1654355Z 	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63)
2020-05-10T20:06:47.1655089Z 	at org.eclipse.rdf4j.sail.base.SailClosingIteration.hasNext(SailClosingIteration.java:81)
2020-05-10T20:06:47.1655840Z 	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63)
2020-05-10T20:06:47.1656594Z 	at org.eclipse.rdf4j.sail.helpers.SailBaseIteration.hasNext(SailBaseIteration.java:41)
2020-05-10T20:06:47.1657338Z 	at org.eclipse.rdf4j.sail.SailConnection.hasStatement(SailConnection.java:152)
2020-05-10T20:06:47.1658084Z 	at org.eclipse.rdf4j.sail.shacl.ShaclSailConnection.hasStatement(ShaclSailConnection.java:753)
2020-05-10T20:06:47.1658832Z 	at org.eclipse.rdf4j.sail.shacl.ConnectionHelper.isEmpty(ConnectionHelper.java:67)
2020-05-10T20:06:47.1659586Z 	at org.eclipse.rdf4j.sail.shacl.ShaclSailConnection.isEmpty(ShaclSailConnection.java:758)
2020-05-10T20:06:47.1660326Z 	at org.eclipse.rdf4j.sail.shacl.ShaclSailConnection.prepare(ShaclSailConnection.java:583)
2020-05-10T20:06:47.1661077Z 	at org.eclipse.rdf4j.repository.sail.SailRepositoryConnection.commit(SailRepositoryConnection.java:161)
2020-05-10T20:06:47.1661828Z 	at org.eclipse.rdf4j.sail.shacl.MultithreadedTest.lambda$null$3(MultithreadedTest.java:450)
2020-05-10T20:06:47.1662578Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-05-10T20:06:47.1663669Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-05-10T20:06:47.1664847Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-05-10T20:06:47.1665590Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-05-10T20:06:47.1666327Z 	at java.lang.Thread.run(Thread.java:748)
```

This is probably due to us setting the statements to null when upgrading the model.

**Comment by hmottestad** [comment]
Propose we switch the upgrade method to wrap the statement set in unmodifiable. And synchronize all write operations.

**Comment by jeenbroekstra** [comment]
Reopening because of a build failure in master that looks related to this issue.
