### ISSUE TITLE
SPARQL parser exception when parsing a complex property path expression

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2319]
Executing a query containing a complex property path expressions yields an exception while parsing the AST.

Query:

    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
    SELECT ?subject WHERE {
      ?subject (^(rdfs:subClassOf+))/rdfs:label ?label .
    } LIMIT 10

Minimal test case to reproduce:

      String query = "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n" 
                + "SELECT ?subject WHERE {\n"
                + "  ?subject (^(rdfs:subClassOf+))/rdfs:label ?label .\n" 
                + "} LIMIT 10";
 
       QueryParserUtil.parseTupleQuery(QueryLanguage.SPARQL, query, "http://example.org/");

    Stacktrace
    Exception in thread "main" java.lang.IllegalArgumentException: Node is not a child node: Var (name=label)
	at org.eclipse.rdf4j.query.algebra.AbstractQueryModelNode.replaceChildNode(AbstractQueryModelNode.java:85)
	at org.eclipse.rdf4j.query.algebra.ArbitraryLengthPath.replaceChildNode(ArbitraryLengthPath.java:212)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder$VarReplacer.meet(TupleExprBuilder.java:1751)
	at org.eclipse.rdf4j.query.algebra.Var.visit(Var.java:79)
        ...

Related to #2142, likely a regression introduced by #2078

**Comment by jeenbroekstra** [comment]
Problem is addressed by fix for closely related issue #2343.
