### ISSUE TITLE
Null pointer exception when using nested triples in query

### ISSUE THREAD

**Issue by rdstn** [eclipse/rdf4j#2517]
This is probably related to the RDF* implementation. When you execute the following query against any repository (including an empty one), you get a null pointer within the Query parser.

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <https://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
 
INSERT {
	<http://example.com/concept1> skos:inScheme ?scheme .
} WHERE {
	<http://example.com/project1>  <http://example.com/hasSchemePermission> <<<http://example.com/user1> <http://example.com/editor> ?scheme>> .
}
```

And the relevant part of the stack trace:
```
java.lang.NullPointerException: null
        at org.eclipse.rdf4j.query.algebra.UnaryTupleOperator.setArg(UnaryTupleOperator.java:63)
        at org.eclipse.rdf4j.query.algebra.UnaryTupleOperator.<init>(UnaryTupleOperator.java:39)
        at org.eclipse.rdf4j.query.algebra.Extension.<init>(Extension.java:35)
        at org.eclipse.rdf4j.query.parser.sparql.UpdateExprBuilder.visit(UpdateExprBuilder.java:405)
        at org.eclipse.rdf4j.query.parser.sparql.UpdateExprBuilder.visit(UpdateExprBuilder.java:66)
        at org.eclipse.rdf4j.query.parser.sparql.ast.ASTTripleRef.jjtAccept(ASTTripleRef.java:36)
        at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:1920)
        at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:231)
        at org.eclipse.rdf4j.query.parser.sparql.ast.ASTObjectList.jjtAccept(ASTObjectList.java:24)
        at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:1390)
        at org.eclipse.rdf4j.query.parser.sparql.ast.ASTPathSequence.jjtAccept(ASTPathSequence.java:27)
        at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:1338)
        at org.eclipse.rdf4j.query.parser.sparql.ast.ASTPathAlternative.jjtAccept(ASTPathAlternative.java:25)
        at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:1887)
        at org.eclipse.rdf4j.query.parser.sparql.ast.ASTPropertyListPath.jjtAccept(ASTPropertyListPath.java:25)
        at org.eclipse.rdf4j.query.parser.sparql.ast.SimpleNode.childrenAccept(SimpleNode.java:154)
        at org.eclipse.rdf4j.query.parser.sparql.AbstractASTVisitor.visit(AbstractASTVisitor.java:843)
        at org.eclipse.rdf4j.query.parser.sparql.ast.ASTTriplesSameSubjectPath.jjtAccept(ASTTriplesSameSubjectPath.java:25)
        at org.eclipse.rdf4j.query.parser.sparql.ast.SimpleNode.childrenAccept(SimpleNode.java:154)
        at org.eclipse.rdf4j.query.parser.sparql.AbstractASTVisitor.visit(AbstractASTVisitor.java:378)
        at org.eclipse.rdf4j.query.parser.sparql.ast.ASTBasicGraphPattern.jjtAccept(ASTBasicGraphPattern.java:24)
        at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:1171)
        at org.eclipse.rdf4j.query.parser.sparql.ast.ASTGraphPatternGroup.jjtAccept(ASTGraphPatternGroup.java:24)
        at org.eclipse.rdf4j.query.parser.sparql.ast.SimpleNode.childrenAccept(SimpleNode.java:154)
        at org.eclipse.rdf4j.query.parser.sparql.AbstractASTVisitor.visit(AbstractASTVisitor.java:877)
        at org.eclipse.rdf4j.query.parser.sparql.ast.ASTWhereClause.jjtAccept(ASTWhereClause.java:24)
        at org.eclipse.rdf4j.query.parser.sparql.UpdateExprBuilder.visit(UpdateExprBuilder.java:298)
        at org.eclipse.rdf4j.query.parser.sparql.UpdateExprBuilder.visit(UpdateExprBuilder.java:66)
        at org.eclipse.rdf4j.query.parser.sparql.ast.ASTModify.jjtAccept(ASTModify.java:25)
        at org.eclipse.rdf4j.query.parser.sparql.SPARQLParser.parseUpdate(SPARQLParser.java:126)
        at org.eclipse.rdf4j.query.parser.QueryParserUtil.parseUpdate(QueryParserUtil.java:76)
```

**Comment by damyan-ognyanov** [comment]
@rdstn you did not mention the RDF4J version - there was a simmilar issue recently https://github.com/eclipse/rdf4j/issues/2441 which has been fixed ...

**Comment by rdstn** [comment]
It's an old one. Appears to already be fixed, then.
