### ISSUE TITLE
RDF* triples in DELETE WHERE don't work

### ISSUE THREAD

**Issue by pulquero** [eclipse/rdf4j#2618]
Test
```
	@Test
	public void testDeleteWhere() {
		Repository repo = new SailRepository(new MemoryStore());
		RepositoryConnection conn = repo.getConnection();
		conn.prepareUpdate("delete where { << <local:1> <local:2> <local:3> >> ?p ?o}");
	}
```
Exception
```
Caused by: org.eclipse.rdf4j.query.parser.sparql.ast.VisitorException: DELETE WHERE may not contain blank nodes
	at org.eclipse.rdf4j.query.parser.sparql.UpdateExprBuilder.visit(UpdateExprBuilder.java:158)
	at org.eclipse.rdf4j.query.parser.sparql.UpdateExprBuilder.visit(UpdateExprBuilder.java:66)
	at org.eclipse.rdf4j.query.parser.sparql.ast.ASTDeleteWhere.jjtAccept(ASTDeleteWhere.java:25)
	at org.eclipse.rdf4j.query.parser.sparql.SPARQLParser.parseUpdate(SPARQLParser.java:126)
	... 28 more
```
Looks like you need to track/ignore vars used in TripleRefs:
```
Join
   TripleRef
      Var (name=_const_142bb7e2_uri, value=local:1, anonymous)
      Var (name=_const_142bb7e3_uri, value=local:2, anonymous)
      Var (name=_const_142bb7e4_uri, value=local:3, anonymous)
      Var (name=_anon_75415e82_9f0b_4824_afdb_87a14da5e29a, anonymous)
   StatementPattern
      Var (name=_anon_75415e82_9f0b_4824_afdb_87a14da5e29a, anonymous)
      Var (name=p)
      Var (name=o)
```

**Comment by damyan-ognyanov** [comment]
Threre is a missing check in`UpdateExprBuilder.visit(ASTDeleteWhere ...)` for vars comming from TripleRef's as it is done in `UpdateExprBuilder.visit(ASTDeleteClause...)`

will handle it ...

**Comment by pulquero** [comment]
If there is a snapshot repo, I'm happy to test on my side too.

**Comment by jeenbroekstra** [comment]
> If there is a snapshot repo, I'm happy to test on my side too.

There is. See https://rdf4j.org/download/#source-code-and-nightly-builds. You may have to wait 24 hours for this fix to become available there though.

**Comment by pulquero** [comment]
Yep, working fine here.
