### ISSUE TITLE
SPARQL CONSTRUCT with ORDER BY RAND() fail

### ISSUE THREAD

**Issue by skodapetr** [eclipse/rdf4j#263]
Given a SailRepository(MemoryStore) with a single statement

```
<http://localhost/resource/0> a  <http://purl.org/linked-data/cube#Observation>
```

the query

```
CONSTRUCT {
  ?observation a <http://purl.org/linked-data/cube#Observation> 
} WHERE {
  ?observation a <http://purl.org/linked-data/cube#Observation> 
} ORDER BY RAND()
```

fails with exception

```
Exception in thread "main" java.lang.NullPointerException
    at org.eclipse.rdf4j.query.algebra.evaluation.iterator.OrderIterator$1.getNextElement(OrderIterator.java:177)
    at org.eclipse.rdf4j.query.algebra.evaluation.iterator.OrderIterator$1.getNextElement(OrderIterator.java:165)
    at org.eclipse.rdf4j.common.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:78)
    at org.eclipse.rdf4j.common.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:48)
    at org.eclipse.rdf4j.common.iteration.DelayedIteration.hasNext(DelayedIteration.java:68)
    at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:56)
    at org.eclipse.rdf4j.common.iteration.FilterIteration.findNextElement(FilterIteration.java:69)
    at org.eclipse.rdf4j.common.iteration.FilterIteration.hasNext(FilterIteration.java:44)
    at org.eclipse.rdf4j.common.iteration.ConvertingIteration.hasNext(ConvertingIteration.java:62)
    at org.eclipse.rdf4j.common.iteration.ConvertingIteration.hasNext(ConvertingIteration.java:62)
    at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:56)
    at org.eclipse.rdf4j.common.iteration.FilterIteration.findNextElement(FilterIteration.java:69)
    at org.eclipse.rdf4j.common.iteration.FilterIteration.hasNext(FilterIteration.java:44)
    at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:56)
    at org.eclipse.rdf4j.sail.base.SailClosingIteration.hasNext(SailClosingIteration.java:86)
    at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:56)
    at org.eclipse.rdf4j.sail.helpers.SailBaseIteration.hasNext(SailBaseIteration.java:44)
    at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:56)
    at org.eclipse.rdf4j.common.iteration.FilterIteration.findNextElement(FilterIteration.java:69)
    at org.eclipse.rdf4j.common.iteration.FilterIteration.hasNext(FilterIteration.java:44)
    at org.eclipse.rdf4j.common.iteration.ConvertingIteration.hasNext(ConvertingIteration.java:62)
    at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:56)
    at org.eclipse.rdf4j.common.iteration.Iterations.addAll(Iterations.java:72)
    at org.eclipse.rdf4j.common.iteration.Iterations.asList(Iterations.java:37)
    at eu.skodape.sandbox.rdf4j.ConstructSelectOrderRand.lambda$main$0(ConstructSelectOrderRand.java:62)
    at org.eclipse.rdf4j.repository.util.Repositories.lambda$graphQuery$16(Repositories.java:289)
    at org.eclipse.rdf4j.repository.util.Repositories.get(Repositories.java:127)
    at org.eclipse.rdf4j.repository.util.Repositories.graphQuery(Repositories.java:286)
    at eu.skodape.sandbox.rdf4j.ConstructSelectOrderRand.main(ConstructSelectOrderRand.java:61)
```

Tested with 2.0M3 version.

**Comment by jeenbroekstra** [comment]
Confirmed. Root cause is undeterministic (random) behavior of the OrderComparator, causing lookups in an internal ordered TreeMap to fail.

**Comment by jeenbroekstra** [comment]
Workaround is to rewrite the query slightly:
```

CONSTRUCT {
  ?observation a <http://purl.org/linked-data/cube#Observation> 
} WHERE {
  ?observation a <http://purl.org/linked-data/cube#Observation> 
  BIND(RAND() as ?r) 
} ORDER BY ?r
```

works as intended.
