### ISSUE TITLE
FedXRuntimeException on DESCRIBE query

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2759]
Reported on the rdf4j-users group (see https://groups.google.com/d/msgid/rdf4j-users/da1876bb-7792-48e1-9b07-a8b4fe84de20n%40googlegroups.com ). 

 FedX fails with a FedXRuntimeException when executing a query of the following form:

```
describe ?s where {?s ?p ?o }
```

Stacktrace:

```
Exception in thread "main" org.eclipse.rdf4j.federated.exception.FedXRuntimeException: Federation Strategy does not support org.openrdf.query.algebra.evaluation.TripleSource#getStatements. If you encounter this exception, please report it.
	at org.eclipse.rdf4j.federated.evaluation.FederationEvalStrategy$1.getStatements(FederationEvalStrategy.java:131)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategy.evaluate(StrictEvaluationStrategy.java:557)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategy.evaluate(StrictEvaluationStrategy.java:284)
	at org.eclipse.rdf4j.federated.evaluation.FederationEvalStrategy.evaluate(FederationEvalStrategy.java:352)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.DescribeIteration.createNextIteration(DescribeIteration.java:216)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.DescribeIteration.resetCurrentDescribeExprIter(DescribeIteration.java:106)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.DescribeIteration.getNextElement(DescribeIteration.java:130)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.DescribeIteration.getNextElement(DescribeIteration.java:1)
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:81)
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:49)
	at org.eclipse.rdf4j.federated.evaluation.iterator.StopRemainingExecutionsOnCloseIteration.hasNext(StopRemainingExecutionsOnCloseIteration.java:45)
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63)
	at org.eclipse.rdf4j.sail.helpers.SailBaseIteration.hasNext(SailBaseIteration.java:41)
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63)
	at org.eclipse.rdf4j.common.iteration.FilterIteration.findNextElement(FilterIteration.java:74)
	at org.eclipse.rdf4j.common.iteration.FilterIteration.hasNext(FilterIteration.java:45)
	at org.eclipse.rdf4j.common.iteration.ConvertingIteration.hasNext(ConvertingIteration.java:62)
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63)
	at org.eclipse.rdf4j.common.iteration.Iterations.addAll(Iterations.java:64)
	at org.eclipse.rdf4j.query.QueryResults.asModel(QueryResults.java:88)
	at org.eclipse.rdf4j.query.QueryResults.asModel(QueryResults.java:72)
	at scratchpad.Scratchpad.executeConstructDescribeFederation(Scratchpad.java:46)
```

Test code to reproduce (assumes a running RDF4J Server with two repositories test1 and test2 to serve as federation sparql endpoints):

```java
	private static Model executeConstructDescribeFederation() {
		List<String> endpoints = Arrays.asList("http://localhost:8080/rdf4j-server/repositories/test1", "http://localhost:8080/rdf4j-server/repositories/test2");

		Repository repository = FedXFactory.newFederation().withSparqlEndpoints(endpoints).create();

		try (RepositoryConnection conn = repository.getConnection()) {
			GraphQuery graphQuery = conn.prepareGraphQuery("describe ?s where {?s ?p ?o }");
			Model model = QueryResults.asModel(graphQuery.evaluate());
			return model;
		} finally {
			repository.shutDown();
		}
	}
```

**Comment by jeenbroekstra** [comment]
@aschwarte10 I'd like your expert opinion on this when you have a minute.

**Comment by Fex97** [comment]
Hello Jeenbroekstra, just wondering if this issue is being worked on or if there is some other solution to this. Thanks

**Comment by aschwarte10** [comment]
There is now a change for supporting DESCRIBE queries in FedX in https://github.com/eclipse/rdf4j/pull/3575/

Not a very tricky change, but also not straight forward. Also this is a functional and "simple" implementation. Maybe there are optimizations possible, which can be looked at in a later stage. I'd propose to get this working first, and if there is demand (or better said: if there are issues) look deeper at performance

I guess we are OK to have this in the develop branch, targeted for 4.0?
