### ISSUE TITLE
QueryParserUtil fails to parse some URIs

### ISSUE THREAD

**Issue by AlyHdr** [eclipse/rdf4j#2785]
I am trying to insert triples from wikidata into a native store however the query parser for updates fails to parse the query with this error:
```
Exception in thread "main" org.eclipse.rdf4j.query.MalformedQueryException: Unexpected character U+23 at index 63: https://cowboybebop.fandom.com/wiki/Mars#cite_ref-1?oldid=23168#References [line 1]
	at org.eclipse.rdf4j.query.parser.sparql.SPARQLParser.parseUpdate(SPARQLParser.java:158)
	at org.eclipse.rdf4j.query.parser.QueryParserUtil.parseUpdate(QueryParserUtil.java:76)
	at eu.qanswer.enpoint.TestNativeStore.main(TestNativeStore.java:24)
Caused by: org.eclipse.rdf4j.rio.RDFParseException: Unexpected character U+23 at index 63: https://cowboybebop.fandom.com/wiki/Mars#cite_ref-1?oldid=23168#References [line 1]
	at org.eclipse.rdf4j.rio.helpers.RDFParserHelper.reportError(RDFParserHelper.java:272)
	at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.reportError(AbstractRDFParser.java:638)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.reportError(TurtleParser.java:1305)
	at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.createURI(AbstractRDFParser.java:409)
	at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.resolveURI(AbstractRDFParser.java:397)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseURI(TurtleParser.java:948)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseValue(TurtleParser.java:580)
	at org.eclipse.rdf4j.rio.trigstar.TriGStarParser.parseValue(TriGStarParser.java:56)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseObject(TurtleParser.java:462)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseObjectList(TurtleParser.java:390)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.parsePredicateObjectList(TurtleParser.java:363)
	at org.eclipse.rdf4j.query.parser.sparql.SPARQLUpdateDataBlockParser.parseGraph(SPARQLUpdateDataBlockParser.java:147)
	at org.eclipse.rdf4j.rio.trig.TriGParser.parseStatement(TriGParser.java:112)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:179)
	at org.eclipse.rdf4j.query.parser.sparql.SPARQLParser.parseUpdate(SPARQLParser.java:145)
	... 2 more
```

I tried to set the configuration for the parser to not check the URI syntax however it didn't solve the problem:

```
...
String indexes = "spoc,posc,cosp";
        Repository repo = new SailRepository(new NativeStore(dataDir, indexes));

        RepositoryConnection connection = repo.getConnection();
        connection.setParserConfig(new ParserConfig().set(BasicParserSettings.VERIFY_URI_SYNTAX, false));
        QueryParserUtil.parseUpdate(QueryLanguage.SPARQL,"","");
        connection.prepareUpdate("insert data {" +
                "<http://www.wikidata.org/reference/7746291fe09868c54f05f8bebe8447dffdcb05d1>" +
                " <http://www.wikidata.org/prop/reference/P854>" +
                " <https://cowboybebop.fandom.com/wiki/Mars#cite_ref-1?oldid=23168#References> ." +
                "}");
...
```
I'm wondering if there is a way to bypass this error.

**Comment by jeenbroekstra** [comment]
You can't bypass this, for several reasons: first of all the parser config settings only influence the RDF parsers, not the SPARQL query parser. Secondly, the query parser is correct to flag this as an error, the URI is in fact syntactically incorrect, leading to a syntactically illegal SPARQL query. 

What you can do is fix the syntax error in the input. The problem is the second '#' character in the URI `https://cowboybebop.fandom.com/wiki/Mars#cite_ref-1?oldid=23168#References`. A URI fragment identifier is not allowed to contain further '#' characters - it will need to be %-encoded. 

RDF4J offers a handy tool to convert any URI string to a syntactically legal encoding (if possible): `ParsedIRI.create()`.

```java
IRI iri = ParsedIRI.create("https://cowboybebop.fandom.com/wiki/Mars#cite_ref-1?oldid=23168#References");
System.out.println(iri.toString()); // output: https://cowboybebop.fandom.com/wiki/Mars#cite_ref-1?oldid=23168%23References
```

**Comment by jeenbroekstra** [comment]
I just realized that in this case, because it is an INSERT DATA operation, the sparql parser actually does delegate parsing of the data to the RDF parsers (which is why you see org.eclipse.rdf4j.rio.* in your stacktrace), so my previous comment was not fully accurate. 

There is no direct programmatic access availble to this parser, but if you wanted to, you could reconfigure it by means of setting an environment variable or java system property, as described here: https://rdf4j.org/documentation/programming/rio/#configuration-via-command-line-switches . Keep in mind though that doing so will influence _all_ parser instances. Also: having syntactically incorrect URIs in your databaseis likely to cause you headaches further down the line.

**Comment by jeenbroekstra** [comment]
I hope this has answered your question. If you have any further comments or question, feel free to comment/reopen this issue.

**Comment by AlyHdr** [comment]
I managed to pass the java system property to disable the URI verification, and in this case it's just because I'm dumping from **wikidata** and considering that they could store this in their triple store then it's fine. However in general this verification should be activated for data insertions from other sources. 

Thanks for your reply!
