### ISSUE TITLE
NullPointerException while processing TupleQueryResult for query with OPTIONAL before VALUES

### ISSUE THREAD

**Issue by tayloj** [eclipse/rdf4j#3072]
In RDF4j 3.7.0 (and 3.2.2) I'm getting a NullPointerException when running a query like this:

```sparql
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix :     <urn:ex:> 

select ?resource ?label where { 
  ?resource a rdfs:Resource . 
  optional { ?resource rdfs:label ?label } 
  values ?label { undef } 
}
```

on data like this:

```ttl
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> . 
@prefix :     <urn:ex:> . 
:r1 a rdfs:Resource . 
:r2 a rdfs:Resource ; rdfs:label "a label" . 
```

If the values and optional blocks are swapped, I get two results, as expected. A self contained unit test is attached as [TestRdf4j.java.txt](https://github.com/eclipse/rdf4j/files/6550060/TestRdf4j.java.txt). The stacktrace is:

```
java.lang.NullPointerException
   at org.eclipse.rdf4j.query.QueryResults.bindingSetsCompatible(QueryResults.java:499)
   at org.eclipse.rdf4j.query.algebra.evaluation.iterator.BadlyDesignedLeftJoinIterator.getNextElement(BadlyDesignedLeftJoinIterator.java:52)
   at org.eclipse.rdf4j.query.algebra.evaluation.iterator.LeftJoinIterator.getNextElement(LeftJoinIterator.java:1)
   at org.eclipse.rdf4j.common.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:81)
   at org.eclipse.rdf4j.common.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:49)
   at org.eclipse.rdf4j.query.algebra.evaluation.iterator.JoinIterator.getNextElement(JoinIterator.java:68)
   at org.eclipse.rdf4j.query.algebra.evaluation.iterator.JoinIterator.getNextElement(JoinIterator.java:1)
   at org.eclipse.rdf4j.common.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:81)
   at org.eclipse.rdf4j.common.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:49)
   at org.eclipse.rdf4j.common.iteration.ConvertingIteration.hasNext(ConvertingIteration.java:62)
   at org.eclipse.rdf4j.common.iteration.ConvertingIteration.hasNext(ConvertingIteration.java:62)
   at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63)
   at org.eclipse.rdf4j.sail.base.SailClosingIteration.hasNext(SailClosingIteration.java:81)
   at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63)
   at org.eclipse.rdf4j.sail.helpers.SailBaseIteration.hasNext(SailBaseIteration.java:41)
   at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63)
   at org.eclipse.rdf4j.common.iterator.CloseableIterationIterator.hasNext(CloseableIterationIterator.java:34)
   at java.lang.Iterable.forEach(Iterable.java:74)
   at TestRdf4j.doTest(TestRdf4j.java:103)
   at TestRdf4j.testWithTurtleOptionalFirst(TestRdf4j.java:76)
```

That part of QueryResults.bindingSetsCompatible looks suspicious to me:

```java
		for (String bindingName : sharedBindings) {
			Value value1 = bs1.getValue(bindingName);
			Value value2 = bs2.getValue(bindingName);

			if (!value1.equals(value2)) { // here's the NPE
				return false;
			}
```

The javadoc states that BindingSet.getValue(String) returns `null` when there's no value for a variable, and that would seem to happen in the cases of an `optional` that doesn't match as well as a `values` with `undef`.  

I *think* that two binding sets should be compatible if at least one of them has no binding for the variable.  That is, they can only be incompatible if both values are non-null, so maybe this could be:

```java
			if (value1 != null && value2 != null && !value1.equals(value2)) {
				return false;
			}
```

(That could probably just be `value1 != null && !value1.equals(value2)` , but a perverse implementation could make `.equals(null)` return true, so checking both values for null might be slightly safer.)

That gets the unit tests passing, at any rate, though I don't know whether it would break something somewhere else.

**Comment by jeenbroekstra** [comment]
> In RDF4j 3.7.0

You're quick, I literally just pressed the release button :)

Thanks for reporting this @tayloj , and for the analysis. It does sound like that compatibility check has a bug. Though I haven't yet made up my mind on whether the query itself is correct (I have to brush up on the scoping rules for optional and values clauses to be certain), but it certainly shouldn't result in an NPE of course.

**Comment by tayloj** [comment]
@jeenbroekstra I use 3.2.2 regularly, but I wanted to check with the latest release before submitting any issue. So I'm not all the quick, just well timed. :)

As also seen in #3071, I've been testing some things with constructions like `values ?x { undef }` lately.  In #3071, there's some behavior that's different between Jena and RDF4j, so something interesting is happening, but #3071 didn't involve `optional`, so it might be the less ambiguous case.

There are some examples in the SPARQL 1.1 spec that suggest (to me anyhow) the behavior I'm expecting, e.g., in [10.2.2](https://www.w3.org/TR/sparql11-query/#inline-data-examples), but I don't think any involve interaction between `optional` and `values` (and examples probably aren't normative anyhow).

**Comment by tayloj** [comment]
@jeenbroekstra Just as an additional data point, Jena gives the same results for the two different queries (optional first vs values first):

```
------------------------
| resource | label     |
========================
| :r2      | "a label" |
| :r1      |           |
------------------------
```

**Comment by jeenbroekstra** [comment]
Fix for both the NPE and the result inconsistency is now up.
