### ISSUE TITLE
FedX cannot handle large joins with > 65k intermediate result

### ISSUE THREAD

**Issue by aschwarte10** [eclipse/rdf4j#3106]
In the concurrency facilities of FedX we make use of the Java Phaser.
This is limited to 65535 registered parties.

In case of large joins we were seeing errors that the the phaser has reached limits.

Example trace

```
Caused by: java.lang.IllegalStateException: Attempt to register more than 65535 parties for java.util.concurrent.Phaser@3ab90002[phase = 0 parties = 65535 arrived = 0]

	at java.base/java.util.concurrent.Phaser.doRegister(Phaser.java:429)

	at java.base/java.util.concurrent.Phaser.register(Phaser.java:581)

	at org.eclipse.rdf4j.federated.evaluation.join.ControlledWorkerLeftJoin.handleBindings(ControlledWorkerLeftJoin.java:61)

	at org.eclipse.rdf4j.federated.evaluation.join.JoinExecutorBase.performExecution(JoinExecutorBase.java:51)
```

**Comment by aschwarte10** [comment]
@jeenbroekstra I have a fix for this locally and will prepare a PR. Should this go as a bugfix for 3.7.x targeted to the master branch?
