### ISSUE TITLE
StackOverflowError when loading RDF documents with Base64 encoded RDF-star triples

### ISSUE THREAD

**Issue by damyan-ognyanov** [eclipse/rdf4j#3323]
### Current Behavior

A StackOverflowError is thrown when trying to load a `RDFFormat.TURTLESTAR` that contain Base64 encoded Triples as IRIs.

To reproduce try parsing following fragment:
```
<urn:1> <urn:2> <urn:rdf4j:triple:PDw8dXJuOjE-IDx1cm46Mj4gIktvIHRlIGthbXVwZW5lICBTLkwuLCBoZSBrYW11cGVuZSBpIHdoYWthcHVtYXV0aWEgaSB0ZSB0YXUgMjAwOSBhIGkgd2hha2F0YXB1YSBraSBuZ2Ega2F1cGFwYSBrb3Jlcm8gbW8gZXRhaGkgYXR1IGthbXVwZW5lLCBtYWkgaSB0ZSAyMDEyIGkgdGlpbWF0YSB0ZSBoYW5nYSBpIG9uYSBha2UgaGFuZ2FyYXUgYSBrdWEgcG9pcG9paGlhIGUgdGUgbWFoaSB0YWhpIG1lIG5nYSBoaW5vbmdhIGEgaXdpLiBJbmEga29hLCBrbyB0ZSBtYWhpIHRhaGkgbWUgdGUgTWFuYXTFqyBvIHRlIFJvdG8gbyBTcGFpbiB0ZSBtZWEgbnVpLCBpIHJ1bmdhIGkgdGUgbmdhbmEga2kgdGUgd2hha2F3aGFuYWtlIGkgbmdhIG90aW5nYSBoYW5nYXJhdSBtb3R1aGFrZSBlIGhhYW5nYWkgYW5hIGtpIG5nYSBoaWFoaWEgbyBuZ2EgSG9pYSBIYXVtYXJ1IG8gdGUgS2F3YW5hdGFuZ2EgbyBQYW5pb3JhIGkgbmdhIHdhYWhpIG8gbmdhIGRyb25lcyBtZSBuZ2EgYW50aS1kcm9uZXMuIHRlIGhvbm9uZ2EgaSB3YWVuZ2EgaSB0ZSB0cmdhIG1lIHRlIE1hbmF0dSBvIHJvdG8gaSB0ZSBtYW5hIGkgcm90byBpIG5nYSB0YXUgZSA4IGt1YSBoaXBhIGt1YSBraXRlYSBpIHJvdG8gaSBuZ2Egd2FhaGFuZ2EgbnVpIGUgcnVhOiBpIHRldGFoaSB0YWhhLCBrbyB0ZSB0YXV0b2tvIGEgdGUgTWluaXRhIGtpIHRlIG1haGEgbyBuZ2Ega2F1cGFwYSBSJkQgaSBoYW5nYWlhIGUgQUVPUlVNIG1lIHRlIHRhaHVhIHRhaHVhIG1lIHRlIGl3aSB3aGFudWkuIG1vbmk7IGEsIGkgdGV0YWhpIGF0dSwga28gdGUgbWFoaSB0YWhpIG51aSBhIHRlIEhla2VyZXRhcmkgbyB0ZSBXaGVudWEgbW8gdGUgSGF1bWFydXRhbmdhIGkgdGUgd2EgZSB3aGFuYWtlaGlhIGFuYSB0ZSBwdW5haGEgIG1lIC4gSGUga2FtdXBlbmUgaGFuZ2FyYXUtaGFuZ2FyYXUgZSB3aGFrYXJhdG8gYW5hIGkgbmdhIG90aW5nYSBhdW5vYSBtbyBuZ2EgcG9rYXB1IHdoYWthaGFlcmUgbWUgbmdhIHdha2Ega2FvcmUgaGUgdGFuZ2F0YSwgaGUgbnVpIHRlIHV0dSBraSBuZ2Egd2FhaGkgZSBoaWFoaWEgYW5hIGtpYSBtYW1hbyB0ZSB3aGFrYWhhZXJlIG1lIHRlIG1vaGlvLiBNbyB0ZW5laSwga2Egd2hha2FtYWhpYSBlIGlhIHRhbmEgYWtlIFImRCBpIHJvdG8gaSBuZ2Egd2FhaGFuZ2EgbyB0ZSB0aXJvaGFuZ2EgbWF0YWtpdGUgKGtpdGVuZ2EgLyBtb2hpbyAvIHRhYXRhcmkgaSBuZ2EgdGFpYW8gbWUgbmdhIHRhdWlyYSksIHRlIHdoYWthaGFlcmUgd2FrYSAod2hha2FoYWVyZSBhdW5vYSBtZSB0ZSBtb2hpbyBvIG5nYSB3YWthIHJlcmVyYW5naSByb2JvdGljIG1lIG5nYSB0YXVpcmEpIG1lIHRlIG1vaGlvIG1vaGlvLiBLbyB0ZSBrYXVwYXBhIHVhcmEgbyB0ZSAsIFNMLCBlIHdoYWFpYSBhbmEgbW8gdGUgaHVuZ2EgZSBhaHVydSBhbmEgaSB0ZSBhaHVydSwga28gdGUgd2hha2FyYXRvIGkgbmdhIHRhcHV0YXB1IHRpcm90aXJvIGhvdSBraWEgYXVrYXRpLCBraWEgdGVyZSwga2lhIHRpa2EgaG9raSB0ZSB3aGFrYXRhdSBpIG5nYSBhaHVhdGFuZ2EgdWF1YSwga2lhIHBhaSBha2UgYWkgdGUgd2hha2FoYWVyZSBpIHRlIGFodXJ1IG1lIHRlIGthcm8gaSBuZ2EgYWh1YXRhbmdhIG9ob3JlcmUuIEtvIG5nYSBwdW5haGEgaSB3aGFrYXdoYW5ha2VoaWEgaSByb3RvIGkgbmdhIHdoYXJlIHRhaXdoYW5nYSBvICwgUy5MLiwga2EgdGFlYSB0ZSB3aGFrYW1haGkgaSBlbmVpIHdhYWhhbmdhIGUgd2hhaSBha2UgbmVpOiDCtyBUZSBUaWFraXRhbmdhIG1lIHRlIFdoYWthaGF1bWFydSBpIG5nYSBIYW5nYW5nYSBIYW5nYS4gwrcgSGF1bWFydXRhbmdhOiBoZSByb25nb2EgbW8gdGUgd2hha2FoYWVyZSwgdGlyb3Rpcm8gbWUgdGUgdGlyb3Rpcm8gYXVub2EgaSBuZ2Egd2hha2FoYWVyZW5nYSB0dXJlLCBoZWkgYXdoaW5hIGkgdGUgd2hhbnVpdGFuZ2EgbyBuZ2EgYWh1YXRhbmdhLiDCtyBXaGFrYWhhZXJlbmdhIG9ob3JlcmUsIG1vIG5nYSByb25nb2EgdGFhbmdhdGEgbWUgbmdhIGhvaWE6IG5nYSB0YXB1dGFwdSBoZWkgdGlyb3Rpcm8gbW8gdGUgd2FhLXR1dXR1cnUgbyBuZ2Egcm9oZSBlIHBhIGFuYSBtZSBuZ2EgcHVuYWhhIG1vaGlvIGhlaSBhd2hpbmEgaSBuZ2EgbWFoaSB3aGFrYXRhdS4gwrcgTmdhIFRhb25lIFRpbm8gbWUgZXRhaGkgYXR1IHdoYWthdXJ1OiBvdGluZ2EgYXVub2EgaGVpIHdoYWthcGFpIGFrZSBpIHRlIHdoYWthaGFlcmVuZ2EgbyB0ZSB0YWlhbyBpIG5nYSB0YW9uZSwgbmdhIHR1YXdoZW51YSBtZSBuZ2Egcm9oZSB0YWt1dGFpICh0ZSB3aGFrYWhhZXJlIHdha2EsIHRlIHRhaWFvLCBuZ2Egd2hhcmUsIHRlIHdoYWthaGFlcmUgdXJ1cnVhLCB0ZSB0aWFraSAuLi4pIFNMLCBoZSBha2UgaGFuZ2FyYXUgaGVpIHdoaXJpaG9yYSBpIHRlIG1haGEgbyBuZ2Egcm9uZ29hLCBrYSB0YWVhIHRlIHVydXRhdSBraSBuZ2EgaGlhaGlhIG1vdHVoYWtlIG8gb25hIGthaWhva286IHRlIHJhcHUgbWUgdGUgd2FhaGkgbyBuZ2EgdGFhbmdhdGEsIHRlIHRpYWtpIG1lIG5nYSBoYW5nYW5nYSB3aGFrYWhpcmFoaXJhLCB0ZSBhdWthdGkgYWhpLCB0ZSB0aXJvdGlybyBpIG5nYSB0YWlhbyB0YW9uZSwgdGUgd2FhaGkgbyBuZ2EgbWFoaSBrb3JldGFrZSBpIG5nYSB3aGFyZSAvIHVtYW5nYSwgbWUgZXJhIGF0dS4gS28gbmdhIGhhbmdhcmF1IGUgd2hhaSBha2UgbmVpIG1lIHdoYWthbnVpOiDCtyA6IFRlIFdoYWthd2hhbmFrZSBpIHRldGFoaSBQdW5haGEgS29yZXJvIE1hYXRhdXJhbmdhIG1vIHRlIFdoYWthaGFlcmUgbWUgdGUgV2hha2FoYXVtYXJ1IGkgbmdhIEhhbmdhbmdhIENyaXRpY2FsLiDCtyA6IFRlIFdoYWthd2hhbmFrZSBpIHRlIHB1bmFoYSBQYWFudWkgbW8gdGUgS2ltaSBtZSB0ZSBXaGFrYWtvcmUgaSBuZ2EgdHVtYSBtZSBuZ2EgLiDCtyA6ICAgLCBtZSB0ZSBtYWhpIHRhaGkgbWUgdGUgdGFyaSBJcmlyYW5naSBvIHRlIEF3aGluYS4gwrcgOiBUZSBXaGFrYXdoYW5ha2UgaSB0ZSBQdW5haGEgV2hha2F0dXR1a2l0YW5nYSBBcsSBIEF0dSBBbsWNIG1vIHRlIFdoYWthYWV0YW5nYSBpIG5nYSBXaGFrYW51aSBUYW9uZSBtZSBuZ2EgSGFuZ2EgVGlubywgbWUgdGUgbWFoaSB0YWhpIG1lIG5nYSBwaXJpaGltYW5hIHBpcmloaW1hbmEgZSBvbm8uIEkgdGUgdGF1bWF0YSBvIHRlIGFvIChrZWkgd2FobyBvIHRlIGZnKSwga2VpIHRlIHR1dSBhICAgUy5MLiBraSBldGFoaSBrYXVwYXBhIHJlcmVrZSBtZSBuZ2EgaG9hIGhhbmdhcmF1LCB3aGFrYWF3ZWF3ZSBpIG5nYSByb29wdSBtZSBuZ2Egcm9vcHUgd2hhbnVpIGkgbmdhIHdoZW51YSBwZW5laSBpIHRlICwgIGtvIG5nYSAiPj4=> .
```

we got an Error like:
```
java.lang.StackOverflowError
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$Loop.match(Pattern.java:4785)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717)
	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4568)
	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3777)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$Loop.match(Pattern.java:4785)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717)
	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4568)
	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3777)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$Loop.match(Pattern.java:4785)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717)
```

### Expected Behavior

no errors should be thrown. The document is corrct

### Version

3.7.1

**Comment by damyan-ognyanov** [comment]
I've traced the cause down to `org.eclipse.rdf4j.rio.helpers.NTriplesUtil` `parseTripleInternal()` where the use of a Regexp pattern `LITERAL_PATTERN` cause the incorrect behaviour. At a glance could not find an issue with that pattern but when used with long literals (> 4k) it could cause the error.

**Comment by barthanssens** [comment]
Vaguely remembering something about backtracking in regex, would it help (and still work correctly) if STRING_LITERAL_QUOTE pattern would end with ```")*+\"";``` instead of  ```")*\"";``` ?

**Comment by damyan-ognyanov** [comment]
@barthanssens thank's for the tip, that fixes it ... will prepare a PR
