### ISSUE TITLE
Exception in ES Sail compliance test

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#3388]
### Current Behavior

```
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.test.ESTestCase
        at java.base/java.lang.Thread.run(Thread.java:829)
Suppressed: java.lang.IllegalStateException: No context information for thread: Thread[id=40, name=Thread-3, 
state=RUNNABLE, group=TGRP-ElasticsearchSailTest]. Is this thread running under a class
com.carrotsearch.randomizedtesting.RandomizedRunner runner context?
Add @RunWith(class com.carrotsearch.randomizedtesting.RandomizedRunner.class) to your test class.
Make sure your code accesses random contexts within @BeforeClass and @AfterClass boundary (for example, static test class initializers are not permitted to access random contexts).
                at com.carrotsearch.randomizedtesting.RandomizedContext.context(RandomizedContext.java:249)
                at com.carrotsearch.randomizedtesting.RandomizedContext.current(RandomizedContext.java:134)
                at com.carrotsearch.randomizedtesting.RandomizedRunner.augmentStackTrace(RandomizedRunner.java:1885)
                at com.carrotsearch.randomizedtesting.RunnerThreadGroup.uncaughtException(RunnerThreadGroup.java:20)
                at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:1997)
```

### Expected Behavior

Test should work without throwing exception

### Steps To Reproduce

Dev tree using JDK 11 and Maven 3.8.3 on Debian, 

### Version

4.0.0-SNAPSHOT

### Are you interested in contributing a solution yourself?

Yes

**Comment by barthanssens** [comment]
More info from console

[ERROR]   ElasticsearchIndexTest » NoClassDefFound Could not initialize class org.elasti...
[ERROR]   ElasticsearchSailGeoSPARQLTest » NoClassDefFound Could not initialize class or...
[ERROR]   ElasticsearchSailIndexedPropertiesTest » NoClassDefFound Could not initialize ...
[ERROR]   ElasticsearchSailTest>ESTestCase.<clinit>:229 » Runtime can not run elasticsea...

**Comment by barthanssens** [comment]
Seems to work after a few cleans, probably machine-specific issue
