### ISSUE TITLE
ExtensibleStore evaluation statistics thread safety

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#3484]
### Current Behavior

```
2021-11-21T15:27:47.4321730Z [ERROR] org.eclipse.rdf4j.sail.extensiblestore.compliance.ExtensibleStoreTupleQueryResultTest.testStreaming  Time elapsed: 0.346 s  <<< ERROR!
2021-11-21T15:27:47.4324737Z java.lang.ArrayIndexOutOfBoundsException: Index 56 out of bounds for length 32
```

### Expected Behavior

-

### Version

-

**Comment by hmottestad** [comment]
```
java.lang.ArrayIndexOutOfBoundsException: Index 64 out of bounds for length 64

	at it.unimi.dsi.fastutil.ints.Int2ByteOpenHashMap.get(Int2ByteOpenHashMap.java:334)
	at net.agkn.hll.HLL.sparseProbabilisticAlgorithmCardinality(HLL.java:544)
	at net.agkn.hll.HLL.cardinality(HLL.java:518)
	at org.eclipse.rdf4j.sail.extensiblestore.evaluationstatistics.ExtensibleDynamicEvaluationStatistics$ExtensibleDynamicEvaluationStatisticsCardinalityCalculator.getCardinality(ExtensibleDynamicEvaluationStatistics.java:153)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.EvaluationStatistics$CardinalityCalculator.meet(EvaluationStatistics.java:150)
	at org.eclipse.rdf4j.query.algebra.StatementPattern.visit(StatementPattern.java:212)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.EvaluationStatistics.getCardinality(EvaluationStatistics.java:47)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.QueryJoinOptimizer$JoinVisitor.meet(QueryJoinOptimizer.java:88)
	at org.eclipse.rdf4j.query.algebra.StatementPattern.visit(StatementPattern.java:212)
	at org.eclipse.rdf4j.query.algebra.UnaryTupleOperator.visitChildren(UnaryTupleOperator.java:79)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetNode(AbstractQueryModelVisitor.java:572)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meet(AbstractQueryModelVisitor.java:415)
	at org.eclipse.rdf4j.query.algebra.QueryRoot.visit(QueryRoot.java:45)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.QueryJoinOptimizer.optimize(QueryJoinOptimizer.java:57)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategy.optimize(StrictEvaluationStrategy.java:272)
	at org.eclipse.rdf4j.sail.base.SailSourceConnection.evaluateInternal(SailSourceConnection.java:244)
	at org.eclipse.rdf4j.sail.helpers.AbstractSailConnection.evaluate(AbstractSailConnection.java:249)
	at org.eclipse.rdf4j.repository.sail.SailTupleQuery.evaluate(SailTupleQuery.java:50)
	at org.eclipse.rdf4j.repository.TupleQueryResultTest.testNotClosingResult(TupleQueryResultTest.java:237)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at 
```
