### ISSUE TITLE
NullPointerException in LMDB TxnRef when using RepositoryConnection and iterating through TupleQueryResult in a transaction

### ISSUE THREAD

**Issue by cadmiumkitty** [eclipse/rdf4j#3805]
### Current Behavior

Remote client using RepositoryConnection iterating over a TupleQueryResult in a transaction against LmdbStore repository fails with the transaction being rolled back due to NullPointerException exception in TxnRef (and server subsequently closing the connection).

### Expected Behavior

Client code using transactions should be executed without exceptions when using LmdbStore on the server.

### Steps To Reproduce

1. Run Rdf4j server 4.0.0-M3

2. Create a repository using RemoteRepositoryManager with the following snippet (I have not tested without the LuceneSail, but suspect the behaviour is the same):

```
<https://example.com/repository> a rep:Repository ;
  rdfs:label "Some label" ;
  rep:repositoryImpl [
      rep:repositoryType "openrdf:SailRepository" ;
      sr:sailImpl [
          sail:delegate [
              sail:sailType "rdf4j:LmdbStore" 
          ];
          sail:sailType "openrdf:LuceneSail" ;
          sl:indexDir "index/"
      ]
  ].

```

3. Execute the following code on the client:

```
TupleQuery select = ...

connection.setIsolationLevel(IsolationLevels.READ_UNCOMMITTED);
connection.begin();

try (TupleQueryResult result = select.evaluate()) {
    if (result.hasNext()) {
        ... some other logic ....
        connection.commit();
    }
}
```

4. Observe the client failing with the transaction being rolled back due to the connection being closed by the server.

5. Observe the following exception on the server (probably because there are several threads involved in processing requests and TxnRef is maintaining a HashMap of states using Thread.currentThread() as key):

```
[INFO ] 2022-04-17 14:59:45,406 [repositories/xxx] POST transaction start
[INFO ] 2022-04-17 14:59:45,408 [repositories/xxx] transaction started
[INFO ] 2022-04-17 14:59:45,418 [repositories/xxx] PUT txn query request
[INFO ] 2022-04-17 14:59:45,431 [repositories/xxx] PUT txn query request finished
[ERROR] 2022-04-17 14:59:45,434 [repositories/xxx] Query evaluation error
org.eclipse.rdf4j.query.QueryEvaluationException: java.lang.NullPointerException
	at org.eclipse.rdf4j.sail.base.SailDatasetTripleSource$Eval.convert(SailDatasetTripleSource.java:67)
	at org.eclipse.rdf4j.sail.base.SailDatasetTripleSource$Eval.convert(SailDatasetTripleSource.java:59)
	at org.eclipse.rdf4j.common.iteration.ExceptionConvertingIteration.hasNext(ExceptionConvertingIteration.java:70)
	at org.eclipse.rdf4j.common.iteration.ConvertingIteration.hasNext(ConvertingIteration.java:62)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.JoinIterator.getNextElement(JoinIterator.java:75)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.JoinIterator.getNextElement(JoinIterator.java:32)
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:76)
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:50)
	at org.eclipse.rdf4j.common.iteration.ConvertingIteration.hasNext(ConvertingIteration.java:62)
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63)
	at org.eclipse.rdf4j.sail.base.SailClosingIteration.hasNext(SailClosingIteration.java:81)
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63)
	at org.eclipse.rdf4j.sail.helpers.SailBaseIteration.hasNext(SailBaseIteration.java:40)
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63)
	at org.eclipse.rdf4j.common.iteration.TimeLimitIteration.hasNext(TimeLimitIteration.java:48)
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63)
	at org.eclipse.rdf4j.query.QueryResults.report(QueryResults.java:269)
	at org.eclipse.rdf4j.http.server.repository.TupleQueryResultView.renderInternal(TupleQueryResultView.java:99)
	at org.eclipse.rdf4j.http.server.repository.QueryResultView.render(QueryResultView.java:63)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1401)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1145)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1084)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:920)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:684)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at com.github.ziplet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:263)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:660)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
	at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1701)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1190)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:633)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:611)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException: null
	at org.eclipse.rdf4j.sail.lmdb.TxnRef.free(TxnRef.java:113)
	at org.eclipse.rdf4j.sail.lmdb.LmdbRecordIterator.close(LmdbRecordIterator.java:195)
	at org.eclipse.rdf4j.sail.lmdb.LmdbRecordIterator.next(LmdbRecordIterator.java:174)
	at org.eclipse.rdf4j.sail.lmdb.LmdbStatementIterator.getNextElement(LmdbStatementIterator.java:52)
	at org.eclipse.rdf4j.sail.lmdb.LmdbStatementIterator.getNextElement(LmdbStatementIterator.java:23)
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:76)
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:50)
	at org.eclipse.rdf4j.common.iteration.ExceptionConvertingIteration.hasNext(ExceptionConvertingIteration.java:64)
	... 56 common frames omitted
[INFO ] 2022-04-17 14:59:45,481 [repositories/xxx] transaction rollback
[INFO ] 2022-04-17 14:59:45,482 [repositories/xxx] transaction rollback request finished.
```

### Version

4.0.0-M3

### Are you interested in contributing a solution yourself?

Perhaps?

**Comment by jeenbroekstra** [comment]
@kenwenzel are you able to take a look at this?

**Comment by kenwenzel** [comment]
@jeenbroekstra Yes, but I'm on holidays this week. It seems that the connection is used by multiple threads as the per-thread-state is null within TxnRef at line 113.
Is the server-side connection shared for multiple HTTP requests that may happen within different threads?

**Comment by kenwenzel** [comment]
I will change the transaction handling to one LMDB read txn per connection instead of one read txn per thread. I hope I can finish this in the beginning of next week.

**Comment by kenwenzel** [comment]
What ist the exact contract for multiple threads, connections and iterations?

- Can connections be used by multiple threads when these are coordinated (only one thread at a time accesses the connection object)?
- Can iterations created by one thread on a connection be also used by other threads?

Up to now thought that RDF4J allows only one thread to create and use a connection along with the iterations created via the connection object.

**Comment by jeenbroekstra** [comment]
I haven't really looked into the issue here yet, so just answering generally:

> What ist the exact contract for multiple threads, connections and iterations?
> 
>     * Can connections be used by multiple threads when these are coordinated (only one thread at a time accesses the connection object)?

Yes. This is what happens in the Server - it keeps a register of open connections that can be accessed by multiple threads (necessary to handle long-running remote transactions, where requests for the same transaction come in on different threads), but in a controlled fashion.

Generally speaking though, RepositoryConnections are not thread-safe, and the advice is to use a single connection per thread.

>     * Can iterations created by one thread on a connection be also used by other threads?

The contract is that iterations are not thread-safe. As far as I'm aware that's not a rule we break anywhere in RDF4J itself (but there's been lot of refactoring/optimizing recently, and I may not be fully up to speed with the latest).

> Up to now thought that RDF4J allows only one thread to create and use a connection along with the iterations created via the connection object.

The public contract is that neither RepositoryConnections nor Iterations are thread-safe. Under controlled circumstance (such as what we do for txn handling in the Server) you can pass a RepositoryConnection between threads (not sure about Iterations, I don't think I'd care to try).

There is a recent internal optimization that makes concurrent reads on SailConnections (though not _all_ SailConnections) possible - there's a behavioral interface called `ThreadSafetyAware` that signals if a SailConnection supports this. But it's not something we expose up through the Repository API.

**Comment by kenwenzel** [comment]
Thank you for the clarification. It seems that the server opens iterations in one thread and reuses/closes them in another. This makes the LMDB store currently unusable with the server. I'll try to fix this within next week.
