### ISSUE TITLE
Regression when parsing queries with math operations on aggregates without GROUP BY

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#3954]
### Current Behavior

The following query throws an exception during parsing since 4.0.0. It works fine with 3.7.7.

```
SELECT (COUNT (DISTINCT *) AS ?count) (?count / ?count AS ?result) {
    ?s a ?o .
}
```

```
Exception in thread "main" org.eclipse.rdf4j.query.MalformedQueryException: non-aggregate expression 'MathExpr (/)
   Var (name=count)
   Var (name=count)
' not allowed in projection when using GROUP BY.
	at org.eclipse.rdf4j.query.parser.sparql.SPARQLParser.buildQueryModel(SPARQLParser.java:220)
	at org.eclipse.rdf4j.query.parser.sparql.SPARQLParser.parseQuery(SPARQLParser.java:178)
	at org.eclipse.rdf4j.query.parser.QueryParserUtil.parseQuery(QueryParserUtil.java:93)
	at org.eclipse.rdf4j.query.parser.QueryParserUtil.parseTupleQuery(QueryParserUtil.java:108)
	at org.eclipse.rdf4j.repository.sail.SailRepositoryConnection.prepareTupleQuery(SailRepositoryConnection.java:288)
	at org.eclipse.rdf4j.repository.sail.SailRepositoryConnection.prepareTupleQuery(SailRepositoryConnection.java:59)
	at org.eclipse.rdf4j.repository.base.AbstractRepositoryConnection.prepareTupleQuery(AbstractRepositoryConnection.java:143)
	at org.eclipse.rdf4j.repository.RepositoryConnection.prepareTupleQuery(RepositoryConnection.java:212)
	at org.eclipse.rdf4j.sail.memory.Temp.main(Temp.java:37)
Caused by: org.eclipse.rdf4j.query.parser.sparql.ast.VisitorException: non-aggregate expression 'MathExpr (/)
   Var (name=count)
   Var (name=count)
' not allowed in projection when using GROUP BY.
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:644)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:234)
	at org.eclipse.rdf4j.query.parser.sparql.ast.ASTSelect.jjtAccept(ASTSelect.java:32)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:397)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:234)
	at org.eclipse.rdf4j.query.parser.sparql.ast.ASTSelectQuery.jjtAccept(ASTSelectQuery.java:24)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:346)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:234)
	at org.eclipse.rdf4j.query.parser.sparql.ast.ASTQueryContainer.jjtAccept(ASTQueryContainer.java:26)
	at org.eclipse.rdf4j.query.parser.sparql.SPARQLParser.buildQueryModel(SPARQLParser.java:218)
	... 8 more
```

### Given the following data:
```
[] a [].
[] a [].
[] a [].
```

### And the following query:

```
SELECT (COUNT (DISTINCT *) AS ?count) (?count / ?count AS ?result) {
    ?s a ?o .
}
```

### We get the following result with RDF4J 3.7.7:

[result="1"^^<http://www.w3.org/2001/XMLSchema#decimal>;count="3"^^<http://www.w3.org/2001/XMLSchema#integer>]

### Steps To Reproduce

```java
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.TupleQuery;
import org.eclipse.rdf4j.query.TupleQueryResult;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.repository.sail.SailRepositoryConnection;
import org.eclipse.rdf4j.rio.RDFFormat;

import java.io.IOException;
import java.io.StringReader;

public class Temp {

	public static void main(String[] args) throws IOException {

		SailRepository sailRepository = new SailRepository(new MemoryStore());

		try (SailRepositoryConnection connection = sailRepository.getConnection()) {

			connection.add(new StringReader("[] a [].\n [] a [].\n [] a [].\n"), RDFFormat.TURTLE);

			String query = "SELECT (COUNT (DISTINCT *) AS ?count) (?count / ?count AS ?result) {\n" +
				"    ?s a ?o .\n" +
				"}\n";

			System.out.println(query);

			TupleQuery tupleQuery = connection.prepareTupleQuery(query);

			try (TupleQueryResult evaluate = tupleQuery.evaluate()) {
				for (BindingSet bindings : evaluate) {
					System.out.println(bindings);
				}
			}

		}

	}

}
```

### Version

4.0.1

### Are you interested in contributing a solution yourself?

Yes

**Comment by hmottestad** [comment]
Query works fine on:
 - 3.7.7
 - 4.0.0-M1

**Comment by hmottestad** [comment]
I've narrowed it down to the [PR](https://github.com/eclipse/rdf4j/pull/3788) for the [issue](https://github.com/eclipse/rdf4j/issues/3782) that @jeenbroekstra mentioned earlier.

**Comment by hmottestad** [comment]
### Old query plan

```
Projection
   ProjectionElemList
      ProjectionElem "count"
      ProjectionElem "result"
   Extension
      Group ()
         StatementPattern
            Var (name=s)
            Var (name=_const_f5e5585a_uri, value=http://www.w3.org/1999/02/22-rdf-syntax-ns#type, anonymous)
            Var (name=o)
         GroupElem (count)
            Count (Distinct)
      ExtensionElem (count)
         Count (Distinct)
      ExtensionElem (result)
         MathExpr (/)
            Var (name=count)
            Var (name=count)
```

**Comment by hmottestad** [comment]
The SPARQL validator allows projecting of any variable that can be traced back to an aggregate.

```
SELECT (COUNT (*) AS ?count) (?count / ?count AS ?result) (?result AS ?temp) (?temp / 2 AS ?temp2) {
    ?s a ?o .
}
```

`?temp2` effectively becomes `(COUNT (*) / COUNT (*)) / 2`.
