### ISSUE TITLE
Error evaluating TupleQuery since 4.1.0-M1

### ISSUE THREAD

**Issue by maxstolze** [eclipse/rdf4j#4037]
### Current Behavior

Error evaluating TupleQuery:

```
org.eclipse.rdf4j.spring.dao.exception.RDF4JSpringException: Error evaluating TupleQuery:
QueryRoot
   Distinct
      Projection
         ProjectionElemList
            ProjectionElem "id"
            ProjectionElem "f_copyOf"
            ProjectionElem "f_standardId"
            ProjectionElem "f_name"
            ProjectionElem "dateCreated"
            ProjectionElem "dateModified"
            ProjectionElem "f_private"
            ProjectionElem "f_description"
            ProjectionElem "creator"
            ProjectionElem "editor"
            ProjectionElem "f_featureKind"
            ProjectionElem "class"
            ProjectionElem "quantityKind"
            ProjectionElem "quantityKindLabel"
            ProjectionElem "unit"
            ProjectionElem "unitLabel"
            ProjectionElem "allowMultiple"
            ProjectionElem "optionId"
            ProjectionElem "optionValue"
            ProjectionElem "optionDescription"
            ProjectionElem "path"
         Extension
            Filter
               Not
                  And
                     Bound
                        Var (name=organizationId)
                     Bound
                        Var (name=projectId)
               Join
                  Join
                     LeftJoin
                        LeftJoin
                           LeftJoin
                              LeftJoin
                                 Join
                                    Join
                                       Join
                                          Join
                                             Join
                                                Join
                                                   Join
                                                      StatementPattern
                                                         Var (name=id)
                                                         Var (name=_const_f5e5585a_uri, value=http://www.w3.org/1999/02/22-rdf-syntax-ns#type, anonymous)
                                                         Var (name=_const_78de6dd_uri, value=https://mms.researchstudio.at/mms#Feature, anonymous)
                                                      StatementPattern
                                                         Var (name=id)
                                                         Var (name=_const_9763fc31_uri, value=http://schema.org/name, anonymous)
                                                         Var (name=f_name)
                                                   StatementPattern
                                                      Var (name=id)
                                                      Var (name=_const_cbf3f98a_uri, value=https://mms.researchstudio.at/mms#private, anonymous)
                                                      Var (name=f_private)
                                                StatementPattern
                                                   Var (name=id)
                                                   Var (name=_const_4af93ef4_uri, value=http://schema.org/dateCreated, anonymous)
                                                   Var (name=dateCreated)
                                             StatementPattern
                                                Var (name=id)
                                                Var (name=_const_82fd443d_uri, value=http://schema.org/dateModified, anonymous)
                                                Var (name=dateModified)
                                          StatementPattern
                                             Var (name=id)
                                             Var (name=_const_530dd4c6_uri, value=http://schema.org/creator, anonymous)
                                             Var (name=creator)
                                       StatementPattern
                                          Var (name=id)
                                          Var (name=_const_3f22d193_uri, value=http://schema.org/editor, anonymous)
                                          Var (name=editor)
                                    StatementPattern
                                       Var (name=id)
                                       Var (name=_const_1128dfd3_uri, value=https://mms.researchstudio.at/mms#belongsToStandard, anonymous)
                                       Var (name=f_standardId)
                                 StatementPattern
                                    Var (name=f_standardId)
                                    Var (name=_const_3c9e3349_uri, value=https://mms.researchstudio.at/mms#belongsToOrganization, anonymous)
                                    Var (name=organizationId)
                              StatementPattern
                                 Var (name=f_standardId)
                                 Var (name=_const_803d0f43_uri, value=https://mms.researchstudio.at/mms#belongsToProject, anonymous)
                                 Var (name=projectId)
                           StatementPattern
                              Var (name=id)
                              Var (name=_const_5fa4fb96_uri, value=http://schema.org/description, anonymous)
                              Var (name=f_description)
                        StatementPattern
                           Var (name=id)
                           Var (name=_const_b66fbf45_uri, value=https://mms.researchstudio.at/mms#copyOf, anonymous)
                           Var (name=f_copyOf)
                     StatementPattern
                        Var (name=id)
                        Var (name=_const_624abadd_uri, value=https://mms.researchstudio.at/mms#dataType, anonymous)
                        Var (name=f_featureKind)
                  Filter (new scope)
                     Or
                        ListMemberOperator
                           Var (name=f_featureKind)
                           ValueConstant (value=https://mms.researchstudio.at/mms#StringType)
                           ValueConstant (value=https://mms.researchstudio.at/mms#BooleanType)
                           ValueConstant (value=https://mms.researchstudio.at/mms#ReferenceType)
                        ListMemberOperator
                           Var (name=class)
                           ValueConstant (value=https://mms.researchstudio.at/mms#NumericType)
                           ValueConstant (value=https://mms.researchstudio.at/mms#EnumerationType)
                     LeftJoin
                        LeftJoin
                           LeftJoin
                              LeftJoin
                                 And
                                    Compare (!=)
                                       Var (name=f_featureKind)
                                       ValueConstant (value=http://www.linkedmodel.org/schema/dtype#SimpleCodeList)
                                    Compare (!=)
                                       Var (name=f_featureKind)
                                       ValueConstant (value=https://mms.researchstudio.at/mms#DataType)
                                 StatementPattern
                                    Var (name=f_featureKind)
                                    Var (name=_const_f5e5585a_uri, value=http://www.w3.org/1999/02/22-rdf-syntax-ns#type, anonymous)
                                    Var (name=class)
                                 StatementPattern
                                    Var (name=f_featureKind)
                                    Var (name=_const_f5e5585a_uri, value=http://www.w3.org/1999/02/22-rdf-syntax-ns#type, anonymous)
                                    Var (name=class)
                              Join
                                 Join
                                    Join
                                       StatementPattern
                                          Var (name=f_featureKind)
                                          Var (name=_const_98446f18_uri, value=https://mms.researchstudio.at/mms#quantityKind, anonymous)
                                          Var (name=quantityKind)
                                       StatementPattern
                                          Var (name=f_featureKind)
                                          Var (name=_const_c9e0dadd_uri, value=https://mms.researchstudio.at/mms#unit, anonymous)
                                          Var (name=unit)
                                    StatementPattern
                                       Var (name=quantityKind)
                                       Var (name=_const_9285ccfc_uri, value=http://www.w3.org/2000/01/rdf-schema#label, anonymous)
                                       Var (name=quantityKindLabel)
                                 StatementPattern
                                    Var (name=unit)
                                    Var (name=_const_9285ccfc_uri, value=http://www.w3.org/2000/01/rdf-schema#label, anonymous)
                                    Var (name=unitLabel)
                           StatementPattern
                              Var (name=f_featureKind)
                              Var (name=_const_1e1cc740_uri, value=https://mms.researchstudio.at/mms#allowMultiple, anonymous)
                              Var (name=allowMultiple)
                        LeftJoin
                           Join
                              StatementPattern
                                 Var (name=f_featureKind)
                                 Var (name=_const_4ff5813_uri, value=http://www.linkedmodel.org/schema/dtype#hasMember, anonymous)
                                 Var (name=optionId)
                              StatementPattern
                                 Var (name=optionId)
                                 Var (name=_const_d3edb330_uri, value=http://www.linkedmodel.org/schema/dtype#value, anonymous)
                                 Var (name=optionValue)
                           StatementPattern
                              Var (name=optionId)
                              Var (name=_const_5fa4fb96_uri, value=http://schema.org/description, anonymous)
                              Var (name=optionDescription)
            ExtensionElem (path)
               FunctionCall (http://www.w3.org/2005/xpath-functions#concat)
                  If
                     Bound
                        Var (name=organizationId)
                     FunctionCall (http://www.w3.org/2005/xpath-functions#concat)
                        ValueConstant (value="/organizations/")
                        FunctionCall (http://www.w3.org/2005/xpath-functions#replace)
                           Str
                              Var (name=organizationId)
                           ValueConstant (value="urn:uuid:|/|#|:|\\.")
                           ValueConstant (value="")
                     FunctionCall (http://www.w3.org/2005/xpath-functions#concat)
                        ValueConstant (value="/projects/")
                        FunctionCall (http://www.w3.org/2005/xpath-functions#replace)
                           Str
                              Var (name=projectId)
                           ValueConstant (value="urn:uuid:|/|#|:|\\.")
                           ValueConstant (value="")
                  ValueConstant (value="/standards/")
                  FunctionCall (http://www.w3.org/2005/xpath-functions#replace)
                     Str
                        Var (name=f_standardId)
                     ValueConstant (value="urn:uuid:|/|#|:|\\.")
                     ValueConstant (value="")
                  ValueConstant (value="/features/")
                  FunctionCall (http://www.w3.org/2005/xpath-functions#replace)
                     Str
                        Var (name=id)
                     ValueConstant (value="urn:uuid:|/|#|:|\\.")
                     ValueConstant (value="")


	at org.eclipse.rdf4j.spring.dao.exception.mapper.ExceptionMapper.mapException(ExceptionMapper.java:23)
	at org.eclipse.rdf4j.spring.dao.support.opbuilder.TupleQueryEvaluationBuilder.evaluateAndConvert(TupleQueryEvaluationBuilder.java:40)
	at at.researchstudio.sat.merkmalservice.service.entity.feature.FeatureDao.getFeaturesForStandard(FeatureDao.java:439)
	at at.researchstudio.sat.merkmalservice.dao.FeatureDaoTests.testGetFeaturesForStandardOfProject(FeatureDaoTests.java:188)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.UnsupportedOperationException
	at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:72)
	at java.base/java.util.ImmutableCollections$AbstractImmutableCollection.removeAll(ImmutableCollections.java:80)
	at org.eclipse.rdf4j.query.algebra.evaluation.optimizer.QueryModelNormalizerOptimizer.isWellDesigned(QueryModelNormalizerOptimizer.java:235)
	at org.eclipse.rdf4j.query.algebra.evaluation.optimizer.QueryModelNormalizerOptimizer.meet(QueryModelNormalizerOptimizer.java:86)
	at org.eclipse.rdf4j.query.algebra.Join.visit(Join.java:65)
	at org.eclipse.rdf4j.query.algebra.BinaryTupleOperator.visitChildren(BinaryTupleOperator.java:103)
	at org.eclipse.rdf4j.query.algebra.LeftJoin.visitChildren(LeftJoin.java:86)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractSimpleQueryModelVisitor.meetBinaryTupleOperator(AbstractSimpleQueryModelVisitor.java:547)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractSimpleQueryModelVisitor.meet(AbstractSimpleQueryModelVisitor.java:336)
	at org.eclipse.rdf4j.query.algebra.evaluation.optimizer.QueryModelNormalizerOptimizer.meet(QueryModelNormalizerOptimizer.java:105)
	at org.eclipse.rdf4j.query.algebra.LeftJoin.visit(LeftJoin.java:77)
	at org.eclipse.rdf4j.query.algebra.evaluation.optimizer.QueryModelNormalizerOptimizer.meet(QueryModelNormalizerOptimizer.java:92)
	at org.eclipse.rdf4j.query.algebra.Join.visit(Join.java:65)
	at org.eclipse.rdf4j.query.algebra.BinaryTupleOperator.visitChildren(BinaryTupleOperator.java:103)
	at org.eclipse.rdf4j.query.algebra.LeftJoin.visitChildren(LeftJoin.java:86)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractSimpleQueryModelVisitor.meetBinaryTupleOperator(AbstractSimpleQueryModelVisitor.java:547)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractSimpleQueryModelVisitor.meet(AbstractSimpleQueryModelVisitor.java:336)
	at org.eclipse.rdf4j.query.algebra.evaluation.optimizer.QueryModelNormalizerOptimizer.meet(QueryModelNormalizerOptimizer.java:105)
	at org.eclipse.rdf4j.query.algebra.LeftJoin.visit(LeftJoin.java:77)
	at org.eclipse.rdf4j.query.algebra.evaluation.optimizer.QueryModelNormalizerOptimizer.meet(QueryModelNormalizerOptimizer.java:92)
	at org.eclipse.rdf4j.query.algebra.Join.visit(Join.java:65)
	at org.eclipse.rdf4j.query.algebra.BinaryTupleOperator.visitChildren(BinaryTupleOperator.java:103)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractSimpleQueryModelVisitor.meetBinaryTupleOperator(AbstractSimpleQueryModelVisitor.java:547)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractSimpleQueryModelVisitor.meet(AbstractSimpleQueryModelVisitor.java:316)
	at org.eclipse.rdf4j.query.algebra.evaluation.optimizer.QueryModelNormalizerOptimizer.meet(QueryModelNormalizerOptimizer.java:57)
	at org.eclipse.rdf4j.query.algebra.Join.visit(Join.java:65)
	at org.eclipse.rdf4j.query.algebra.UnaryTupleOperator.visitChildren(UnaryTupleOperator.java:79)
	at org.eclipse.rdf4j.query.algebra.Filter.visitChildren(Filter.java:75)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractSimpleQueryModelVisitor.meetUnaryTupleOperator(AbstractSimpleQueryModelVisitor.java:593)
	at org.eclipse.rdf4j.query.algebra.evaluation.optimizer.QueryModelNormalizerOptimizer.meetUnaryTupleOperator(QueryModelNormalizerOptimizer.java:175)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractSimpleQueryModelVisitor.meet(AbstractSimpleQueryModelVisitor.java:241)
	at org.eclipse.rdf4j.query.algebra.evaluation.optimizer.QueryModelNormalizerOptimizer.meet(QueryModelNormalizerOptimizer.java:184)
	at org.eclipse.rdf4j.query.algebra.Filter.visit(Filter.java:69)
	at org.eclipse.rdf4j.query.algebra.UnaryTupleOperator.visitChildren(UnaryTupleOperator.java:79)
	at org.eclipse.rdf4j.query.algebra.Extension.visitChildren(Extension.java:96)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractSimpleQueryModelVisitor.meetUnaryTupleOperator(AbstractSimpleQueryModelVisitor.java:593)
	at org.eclipse.rdf4j.query.algebra.evaluation.optimizer.QueryModelNormalizerOptimizer.meetUnaryTupleOperator(QueryModelNormalizerOptimizer.java:175)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractSimpleQueryModelVisitor.meet(AbstractSimpleQueryModelVisitor.java:231)
	at org.eclipse.rdf4j.query.algebra.Extension.visit(Extension.java:91)
	at org.eclipse.rdf4j.query.algebra.UnaryTupleOperator.visitChildren(UnaryTupleOperator.java:79)
	at org.eclipse.rdf4j.query.algebra.Projection.visitChildren(Projection.java:81)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractSimpleQueryModelVisitor.meetUnaryTupleOperator(AbstractSimpleQueryModelVisitor.java:593)
	at org.eclipse.rdf4j.query.algebra.evaluation.optimizer.QueryModelNormalizerOptimizer.meetUnaryTupleOperator(QueryModelNormalizerOptimizer.java:175)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractSimpleQueryModelVisitor.meet(AbstractSimpleQueryModelVisitor.java:412)
	at org.eclipse.rdf4j.query.algebra.Projection.visit(Projection.java:75)
	at org.eclipse.rdf4j.query.algebra.UnaryTupleOperator.visitChildren(UnaryTupleOperator.java:79)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractSimpleQueryModelVisitor.meetUnaryTupleOperator(AbstractSimpleQueryModelVisitor.java:593)
	at org.eclipse.rdf4j.query.algebra.evaluation.optimizer.QueryModelNormalizerOptimizer.meetUnaryTupleOperator(QueryModelNormalizerOptimizer.java:175)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractSimpleQueryModelVisitor.meet(AbstractSimpleQueryModelVisitor.java:217)
	at org.eclipse.rdf4j.query.algebra.Distinct.visit(Distinct.java:29)
	at org.eclipse.rdf4j.query.algebra.UnaryTupleOperator.visitChildren(UnaryTupleOperator.java:79)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractSimpleQueryModelVisitor.meet(AbstractSimpleQueryModelVisitor.java:428)
	at org.eclipse.rdf4j.query.algebra.QueryRoot.visit(QueryRoot.java:45)
	at org.eclipse.rdf4j.query.algebra.evaluation.optimizer.QueryModelNormalizerOptimizer.optimize(QueryModelNormalizerOptimizer.java:52)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategy.optimize(StrictEvaluationStrategy.java:264)
	at org.eclipse.rdf4j.sail.base.SailSourceConnection.evaluateInternal(SailSourceConnection.java:244)
	at org.eclipse.rdf4j.sail.helpers.AbstractSailConnection.evaluate(AbstractSailConnection.java:311)
	at org.eclipse.rdf4j.sail.helpers.SailConnectionWrapper.evaluate(SailConnectionWrapper.java:102)
	at org.eclipse.rdf4j.repository.sail.SailTupleQuery.evaluate(SailTupleQuery.java:50)
	at org.eclipse.rdf4j.spring.dao.support.opbuilder.TupleQueryEvaluationBuilder.evaluateAndConvert(TupleQueryEvaluationBuilder.java:37)
	... 67 more
```

### Expected Behavior

Same query, no problems with 4.0.2

### Version

4.1.0-M1

### Are you interested in contributing a solution yourself?

Perhaps?

**Comment by maxstolze** [comment]
Same data & query as in #4038 just with MemoryStore
