### ISSUE TITLE
Duplicate URI created in MemoryStore

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#408]
(Migrated from https://openrdf.atlassian.net/browse/SES-1993)

For a very simple code snippet, I get a "Created a duplicate MemURI" exception when adding statements from a TreeModel to a MemoryStore. The code looks as follows:

{code}
        Repository repository = new SailRepository(new MemoryStore());
        repository.initialize();
        RepositoryConnection con = repository.getConnection();
        try {
            con.begin();
            con.add(model);
            con.commit();
        } catch(RepositoryException ex) {
            con.rollback();
        } finally {
            con.close();
        }
{code}

The following Exception is thrown when calling con.add(...):

{code}
java.lang.AssertionError: Created a duplicate MemURI for URI http://sws.geonames.org/3020251/
    at org.openrdf.sail.memory.model.MemValueFactory.getOrCreateMemURI(MemValueFactory.java:281)
    at org.openrdf.sail.memory.model.MemValueFactory.getOrCreateMemResource(MemValueFactory.java:247)
    at org.openrdf.sail.memory.MemoryStore.addStatement(MemoryStore.java:538)
    at org.openrdf.sail.memory.MemoryStoreConnection.addStatementInternal(MemoryStoreConnection.java:470)
    at org.openrdf.sail.memory.MemoryStoreConnection.addStatementInternal(MemoryStoreConnection.java:422)
    at org.openrdf.sail.helpers.SailConnectionBase.addStatement(SailConnectionBase.java:471)
    at org.openrdf.repository.sail.SailRepositoryConnection.addWithoutCommit(SailRepositoryConnection.java:281)
    at org.openrdf.repository.base.RepositoryConnectionBase.addWithoutCommit(RepositoryConnectionBase.java:561)
    at org.openrdf.repository.base.RepositoryConnectionBase.add(RepositoryConnectionBase.java:409)
{code}

The strange thing is it only happens in certain cases (but then reproducibly). I could imagine it is somehow related to the uri registry in the memory store holding weak references instead of strong references, so maybe I am running into a "bad luck garbage collector" or so.

**Comment by jamesrdf** [comment]
I cannot reproduce this
