### ISSUE TITLE
Incompatible format version: 2 when saving Data to repo

### ISSUE THREAD

**Issue by mudduvenkatesh** [eclipse/rdf4j#4150]
### Current Behavior

Creating ttl file ./uploads/DebtIssueDQRuleset.ttl
2022-09-04 23:09:08.434  WARN 6011 --- [http-nio-16008-exec-3] o.e.r.http.client.SPARQLProtocolSession  : Server reports problem: null (enable debug logging for full details)
2022-09-04 23:09:08.435  WARN 6011 --- [http-nio-16008-exec-3] o.e.r.r.http.HTTPRepositoryConnection    : Rolling back transaction due to connection close

java.lang.Throwable: null
	at org.eclipse.rdf4j.repository.http.HTTPRepositoryConnection.close(HTTPRepositoryConnection.java:357) ~[rdf4j-repository-http-4.1.0.jar!/:4.1.0]
	at net.trigyan.glide.dao.IDao.save(IDao.java:79) ~[classes!/:0.9.7-SNAPSHOT]
	at net.trigyan.glide.dao.iqm.DataQualityDao.save(DataQualityDao.java:2511) ~[classes!/:0.9.7-SNAPSHOT]
	at net.trigyan.glide.dao.iqm.DataQualityDao$$FastClassBySpringCGLIB$$a20182e0.invoke(<generated>) ~[classes!/:0.9.7-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.20.jar!/:5.3.20]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.20.jar!/:5.3.20]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.20.jar!/:5.3.20]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.20.jar!/:5.3.20]
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:123) ~[spring-context-5.3.20.jar!/:5.3.20]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.20.jar!/:5.3.20]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.20.jar!/:5.3.20]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.20.jar!/:5.3.20]
	at net.trigyan.glide.dao.iqm.DataQualityDao$$EnhancerBySpringCGLIB$$3ed14f0.save(<generated>) ~[classes!/:0.9.7-SNAPSHOT]
	at net.trigyan.glide.service.ManageDataQualityService.saveRuleset(ManageDataQualityService.java:79) ~[classes!/:0.9.7-SNAPSHOT]
	at net.trigyan.glide.api.iqm.DataQualityEngineAPI.saveRuleset(DataQualityEngineAPI.java:181) ~[classes!/:0.9.7-SNAPSHOT]
	at net.trigyan.glide.api.iqm.DataQualityEngineAPI$$FastClassBySpringCGLIB$$fbec83be.invoke(<generated>) ~[classes!/:0.9.7-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.20.jar!/:5.3.20]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.20.jar!/:5.3.20]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.20.jar!/:5.3.20]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:7

### Expected Behavior

Triple data to be saved into Graphdb (Ontotext)  9.10.3

### Version

4.1.0 - Works with 3.7.0

### Are you interested in contributing a solution yourself?

Yes

**Comment by hmottestad** [comment]
Does this work with GraphDB 10?

**Comment by mudduvenkatesh** [comment]
> Does this work with GraphDB 10?

I just upgraded to grapdb 10.0.2. I dont have a issue now.. seems to work all ok.. running final tests to validate

**Comment by hmottestad** [comment]
I found a related issue to yours with a work around: https://github.com/eclipse/rdf4j/issues/3899

I recommend you use the same version of RDF4J in your own code as the version supported by GraphDB. [GraphDB 10.0.2 uses RDF4J 4.0.3](https://graphdb.ontotext.com/documentation/10.0/release-notes.html). We strive to keep our code backwards compatible, especially for minor releases and bug fix releases, so using 4.1.x with GraphDB 10.0.x should be fine. Please let us, or Ontotext, know if you run into any issues.

I'll close this issue for now.
