### ISSUE TITLE
Cannot parse a query with a complex path

### ISSUE THREAD

**Issue by desislava-hristova-ontotext** [eclipse/rdf4j#4187]
### Current Behavior

The following code:
```
		conn.prepareTupleQuery("PREFIX skos:<http://www.w3.org/2004/02/skos/core#> \r\n" +
				" SELECT *  " +
				" WHERE {\r\n" +
				"   ?s (skos:broader|^skos:narrower|skos:topConceptOf|^skos:hasTopConcept) ?o.\r\n" +
				" }");
```
throws an error:
java.lang.AssertionError
	at org.eclipse.rdf4j.query.algebra.Var.setParentNode(Var.java:112)
	at org.eclipse.rdf4j.query.algebra.StatementPattern.<init>(StatementPattern.java:101)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:1486)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:237)
	at org.eclipse.rdf4j.query.parser.sparql.ast.ASTPathElt.jjtAccept(ASTPathElt.java:32)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:1411)
	at org.eclipse.rdf4j.query.parser.sparql.TupleExprBuilder.visit(TupleExprBuilder.java:237)
Due to the objVar already having a parent and the restriction imposed by https://github.com/eclipse/rdf4j/commit/e7ff6a72321d9b68925b34bdedf033a4ddd1610c

### Expected Behavior

The query should be succesfully parsed.

### Version

4.1.2

**Comment by hmottestad** [comment]
Thanks for finding this. The assertion was added as a way to detect shared Var objects in the query tree. When objects in the query tree are shared the parent reference becomes incorrect. Just because the assertion fails doesn't mean that the Var object is shared, so usually it's not due to a bug.
