### ISSUE TITLE
Regression RDF4J 4.2: NPE when control flow computes hashCode of "COUNT(*)" algebra node

### ISSUE THREAD

**Issue by aschwarte10** [eclipse/rdf4j#4245]
### Current Behavior

One of our unit tests fails with a NullpointerException after upgrading RDF4J to 4.2: 

the `hashCode` function of `UnaryValueOperator` invokes `arg.hashCode`, where there exist cases of `arg` being `null`.

An example is the algebra reprentation of `COUNT(*) AS ?cnt`  in a projection.

In our case the hashCode is invoke when rendering the query string (see below), but it may be invoked also by other optimizers or parts of the query engine.

Stack Trace for my test scenario (see below)

```
java.lang.NullPointerException
	at org.eclipse.rdf4j.query.algebra.UnaryValueOperator.hashCode(UnaryValueOperator.java:96)
	at org.eclipse.rdf4j.query.algebra.AbstractAggregateOperator.hashCode(AbstractAggregateOperator.java:65)
	at org.eclipse.rdf4j.query.algebra.Count.hashCode(Count.java:39)
	at org.eclipse.rdf4j.query.algebra.GroupElem.hashCode(GroupElem.java:95)
	at java.base/java.util.ArrayList.hashCodeRange(ArrayList.java:627)
	at java.base/java.util.ArrayList.hashCode(ArrayList.java:614)
	at org.eclipse.rdf4j.query.algebra.Group.hashCode(Group.java:164)
	at org.eclipse.rdf4j.query.algebra.UnaryTupleOperator.hashCode(UnaryTupleOperator.java:104)
	at org.eclipse.rdf4j.query.algebra.Extension.hashCode(Extension.java:124)
	at org.eclipse.rdf4j.query.algebra.UnaryTupleOperator.hashCode(UnaryTupleOperator.java:104)
	at org.eclipse.rdf4j.query.algebra.Projection.hashCode(Projection.java:109)
	at java.base/java.util.HashMap.hash(HashMap.java:339)
	at java.base/java.util.HashMap.put(HashMap.java:607)
	at org.eclipse.rdf4j.queryrender.sparql.experimental.ParsedQueryPreprocessor.meet(ParsedQueryPreprocessor.java:718)
	at org.eclipse.rdf4j.query.algebra.Projection.visit(Projection.java:80)
	at org.eclipse.rdf4j.query.algebra.UnaryTupleOperator.visitChildren(UnaryTupleOperator.java:82)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetNode(AbstractQueryModelVisitor.java:582)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meet(AbstractQueryModelVisitor.java:425)
	at org.eclipse.rdf4j.queryrender.sparql.experimental.ParsedQueryPreprocessor.meet(ParsedQueryPreprocessor.java:314)
	at org.eclipse.rdf4j.query.algebra.QueryRoot.visit(QueryRoot.java:48)
	at org.eclipse.rdf4j.queryrender.sparql.experimental.ParsedQueryPreprocessor.transformToSerialize(ParsedQueryPreprocessor.java:140)
	at org.eclipse.rdf4j.queryrender.sparql.experimental.SparqlQueryRenderer.render(SparqlQueryRenderer.java:56)
	at org.eclipse.rdf4j.queryrender.sparql.experimental.SparqlQueryRenderer.render(SparqlQueryRenderer.java:77)
```

### Expected Behavior

The code must not throw an NPE

Addiitionally: the rendering example from below should produce the expected result

### Steps To Reproduce

Minimal example to reproduce:

```
@Test
public void test() throws Exception {

  String query = "SELECT (COUNT(*) AS ?cnt) WHERE { ?s ?p ?o }";
  ParsedOperation operation = QueryParserUtil.parseOperation(QueryLanguage.SPARQL, query, null);

  String rendered = new SparqlQueryRenderer().render(operation);
  System.out.println(rendered);
}
```

### Version

4.2.0

**Comment by aschwarte10** [comment]
@hmottestad , @jeenbroekstra : if you can me provide with a hint how the hashCode computation for a `COUNT(*)` algebra node should look like, I could offer to do the implementation.

We would require a fix in a 4.2.1 patch release to be able to use RDF4J 4.2.x. Side question: is there already a timeline?

**Comment by hmottestad** [comment]
The hashcode code doesn't look like it's changed in 4.2.0. Are you sure that this used to work before? Any chance you could debug the code and see why it's null now but wasn't null before?

**Comment by aschwarte10** [comment]
Ok, I did some local debugging and was able to trace it down - looks like some accidential change in the hashCode of some intermediate base class.

Essentially the difference is in `org.eclipse.rdf4j.query.algebra.AbstractAggregateOperator.hashCode()` (the super class of the `Count`algebra node.

This previously was able to deal with the inner `arg` being `null`

Relevant commit: https://github.com/eclipse/rdf4j/commit/b00d9b8ed2e1179697afd6dc762592b2738e6428#diff-207d84abce65078462b13d5cfd6848f93b2a366d1b7ec159701f2a7b8082950a

Implementation before (i.e. 4.1.3)

```
	@Override
	public int hashCode() {
		int distHash = (isDistinct() ? 1 : 0);
		if (arg == null) {
			return 73 + distHash;
		} else {
			return arg.hashCode() + distHash;
		}
	}
```

Implementation now on 4.2.x

```
	@Override
	public int hashCode() {
		int result = super.hashCode();
		result = 31 * result + (distinct ? 1 : 0);
		return result;
	}
```


@hmottestad : is the fix to go back to the previous version of the `hashCode` implementation? If so, I can create a PR and also add my query renderer unit test where the NPE occurred.

**Comment by hmottestad** [comment]
I ended up fixing the hashCode method in the UnaryValueOperator because the other code in that class doesn't assume that arg can't be null.
