### ISSUE TITLE
Service block fails to evaluate if last item in it is a comment

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#426]
(Migrated from https://openrdf.atlassian.net/browse/SES-1911)

If you run a query such as:

{code}
SELECT \* {
  SERVICE http://localhost:18081/sesameserver/repositories/repository-1 {
    ?s ?p ?o . # Comment
  }
} 
{code}

it should evaluate fine (assuming the endpoint is correct). However, you will instead get:

{code}
Caused by: org.openrdf.sail.SailException: org.openrdf.query.QueryEvaluationException: Encountered "<EOF>" at line 1, column 359.
Was expecting one of:
"{" ... "}" ...
"optional" ...
"graph" ...
"minus" ...
"filter" ...
"bind" ...
"service" ...
"values" ...
at org.openrdf.sail.memory.MemoryStoreConnection.evaluateInternal(MemoryStoreConnection.java:171)
at org.openrdf.sail.helpers.SailConnectionBase.evaluate(SailConnectionBase.java:297)
at org.openrdf.sail.helpers.SailConnectionWrapper.evaluate(SailConnectionWrapper.java:95)
at com.ontologypartners.textsail.TextSailConnection.evaluate(TextSailConnection.java:103)
at org.openrdf.repository.sail.SailTupleQuery.evaluate(SailTupleQuery.java:60)
... 61 more
Caused by: org.openrdf.query.QueryEvaluationException: Encountered "<EOF>" at line 1, column 359.
Was expecting one of:
"{" ... "}}" ...
"optional" ...
"graph" ...
"minus" ...
"filter" ...
"bind" ...
"service" ...
"values" ...
at org.openrdf.repository.sparql.query.SPARQLTupleQuery.evaluate(SPARQLTupleQuery.java:64)
at org.openrdf.query.algebra.evaluation.federation.SPARQLFederatedService.evaluate(SPARQLFederatedService.java:150)
at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:328)
at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:574)
at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:193)
at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:645)
at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:565)
at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:193)
at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:672)
at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:577)
at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:193)
at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:595)
at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:193)
at org.openrdf.sail.memory.MemoryStoreConnection.evaluateInternal(MemoryStoreConnection.java:165)
... 65 more
Caused by: org.openrdf.query.MalformedQueryException: Encountered "<EOF>" at line 1, column 359.
Was expecting one of:
"{" ... "}" ...
"optional" ...
"graph" ...
"minus" ...
"filter" ...
"bind" ...
"service" ...
"values" ...
at org.openrdf.http.client.HTTPClient.handleHTTPError(HTTPClient.java:947)
at org.openrdf.http.client.HTTPClient.sendTupleQueryViaHttp(HTTPClient.java:718)
at org.openrdf.http.client.HTTPClient.getBackgroundTupleQueryResult(HTTPClient.java:602)
at org.openrdf.http.client.HTTPClient.sendTupleQuery(HTTPClient.java:367)
at org.openrdf.repository.sparql.query.SPARQLTupleQuery.evaluate(SPARQLTupleQuery.java:54)
... 78 more
{code}

It appears this is because the sub query is created without inserting new lines, so the closing brace ends up commented out, and thus parsing fails.

**Comment by jamesrdf** [comment]
I cannot reproduce this using 2.3-SNAPSHOT
