### ISSUE TITLE
[Docker compose-RDF4J] Not able to start rdf4j docker container using docker compose file

### ISSUE THREAD

**Issue by niio972** [eclipse/rdf4j#4302]
### Current Behavior

I have use the docker _eclipse/rdf4j-workbench:3.7.4_ for a while but now only _docker _eclipse/rdf4j-workbench:3.7.7_ and docker _eclipse/rdf4j-workbench:4.X.X_ images are available.
I start to use the docker  _eclipse/rdf4j-workbench:3.7.7_ but my dockerized application can't reach the rdf4j-server. I also tried with the 4.1.2 version.

The error appears when rdf4j server start inside the container with the following message : 

```
method failed; nested exception is java.io.IOException: Unable to create logging directory /var/rdf4j/server/logs
[ERROR] 2022-12-02 20:07:16,216 [localhost-startStop-1] Context initialization failed
```

### Expected Behavior

I can connect to the rdf4j-server.

### Steps To Reproduce
I use docker compose with docker compose plugin. Docker version 20.X.X and docker compose version 2.

docker compose file
```
version: "3.5"

services:
  rdf4j:
    container_name: $RDF4J_DOCKER_NAME
    env_file: .env
    image:  eclipse/rdf4j-workbench:$RDF4J_IMAGE_VERSION
    volumes:
      - persist_rdf4j_data:/var/rdf4j
      - persist_rdf4j_logs:/usr/local/tomcat/logs
    ports:
      - "$RDF4J_EXPOSED_PORT:8080"
volumes:
  persist_rdf4j_data:
  persist_rdf4j_logs:
```

.env file
```
RDF4J_DOCKER_NAME=docker-rdf4j
RDF4J_EXPOSED_PORT=28887
RDF4J_IMAGE_VERSION=3.7.7
RDF4J_DATA_VOLUME=persist_rdf4j_data
RDF4J_LOGS_VOLUME=persist_rdf4j_logs
```

Start the rdf4j-workbench container. in docker-compose using ` docker compose  --env-file .env up`` command.

### Version

3.7.7

### Are you interested in contributing a solution yourself?

Perhaps?

### Anything else?
```
> 
> NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
> 02-Dec-2022 20:07:10.934 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/8.5.83
> 02-Dec-2022 20:07:10.940 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Oct 3 2022 21:11:09 UTC
> 02-Dec-2022 20:07:10.941 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 8.5.83.0
> 02-Dec-2022 20:07:10.944 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
> 02-Dec-2022 20:07:10.944 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.15.0-53-generic
> 02-Dec-2022 20:07:10.944 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
> 02-Dec-2022 20:07:10.944 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /opt/java/openjdk
> 02-Dec-2022 20:07:10.944 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.17+8
> 02-Dec-2022 20:07:10.945 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Eclipse Adoptium
> 02-Dec-2022 20:07:10.945 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
> 02-Dec-2022 20:07:10.945 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
> 02-Dec-2022 20:07:10.948 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
> 02-Dec-2022 20:07:10.948 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
> 02-Dec-2022 20:07:10.948 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util=ALL-UNNAMED
> 02-Dec-2022 20:07:10.948 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
> 02-Dec-2022 20:07:10.949 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
> 02-Dec-2022 20:07:10.949 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
> 02-Dec-2022 20:07:10.949 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
> 02-Dec-2022 20:07:10.949 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx2g
> 02-Dec-2022 20:07:10.949 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
> 02-Dec-2022 20:07:10.949 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
> 02-Dec-2022 20:07:10.950 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
> 02-Dec-2022 20:07:10.950 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.eclipse.rdf4j.appdata.basedir=/var/rdf4j
> 02-Dec-2022 20:07:10.950 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
> 02-Dec-2022 20:07:10.950 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
> 02-Dec-2022 20:07:10.950 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
> 02-Dec-2022 20:07:10.950 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
> 02-Dec-2022 20:07:10.951 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [1.2.35] using APR version [1.7.0].
> 02-Dec-2022 20:07:10.956 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true], UDS [{4}].
> 02-Dec-2022 20:07:10.957 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
> 02-Dec-2022 20:07:10.962 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 3.0.2 15 Mar 2022]
> 02-Dec-2022 20:07:11.031 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
> 02-Dec-2022 20:07:11.071 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 944 ms
> 02-Dec-2022 20:07:11.179 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
> 02-Dec-2022 20:07:11.180 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/8.5.83]
> 02-Dec-2022 20:07:11.251 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/rdf4j-server.war]
> 02-Dec-2022 20:07:15.022 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
> [WARN ] 2022-12-02 20:07:16,191 [localhost-startStop-1] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'commonAppConfig' defined in ServletContext resource [/WEB-INF/rdf4j-http-server-servlet.xml]: Invocation of init method failed; nested exception is java.io.IOException: Unable to create logging directory /var/rdf4j/server/logs
> [ERROR] 2022-12-02 20:07:16,216 [localhost-startStop-1] Context initialization failed
> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'commonAppConfig' defined in ServletContext resource [/WEB-INF/rdf4j-http-server-servlet.xml]: Invocation of init method failed; nested exception is java.io.IOException: Unable to create logging directory /var/rdf4j/server/logs
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
> 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
> 	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:702)
> 	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:668)
> 	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:716)
> 	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:591)
> 	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:530)
> 	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:170)
> 	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
> 	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1173)
> 	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1118)
> 	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1011)
> 	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4953)
> 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5267)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
> 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
> 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:727)
> 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:695)
> 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1016)
> 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1903)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.base/java.lang.Thread.run(Unknown Source)
> Caused by: java.io.IOException: Unable to create logging directory /var/rdf4j/server/logs
> 	at org.eclipse.rdf4j.common.app.logging.base.AbstractLogConfiguration.setBaseDir(AbstractLogConfiguration.java:64)
> 	at org.eclipse.rdf4j.common.app.AppConfiguration.init(AppConfiguration.java:158)
> 	at org.eclipse.rdf4j.common.app.AppConfiguration.init(AppConfiguration.java:139)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1930)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1872)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
> 	... 32 common frames omitted
> 02-Dec-2022 20:07:16.228 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/rdf4j-server.war] has finished in [4,977] ms
> 02-Dec-2022 20:07:16.229 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/rdf4j-workbench.war]
> 02-Dec-2022 20:07:18.031 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
> 02-Dec-2022 20:07:18.046 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/rdf4j-workbench.war] has finished in [1,817] ms
> 02-Dec-2022 20:07:18.049 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
> 02-Dec-2022 20:07:18.091 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 7020 ms
```

**Comment by barthanssens** [comment]
Hi, could you perhaps add the exact docker command you're using to start the image ?

Preferred way is to mount the data and log volume like this 

`docker run -d -p 8080:8080 -v data:/your/dir -v logs:/your/dir/logs eclipse/rdf4j-workbench:latest`

**Comment by niio972** [comment]
Hi sorry , I have done some others tests. 

This following command works : docker run -d -p 8080:8080 -v data:/your/dir -v logs:/your/dir/logs eclipse/rdf4j-workbench:latest

But when I run it from a docker compose file it doesn't work. It works only when I remove the volumes in the service configuration.

Strange behaviour : 

In the container runs with `docker compose -up` comand I have found these rights on /var/rdf4j directory.
![image](https://user-images.githubusercontent.com/17789831/205411268-6a62d2b3-185b-4c88-873f-f2f1ece15f09.png)

But using your command with `docker run` command :
![image](https://user-images.githubusercontent.com/17789831/205411373-13471a30-9348-43e0-a690-52a3188d650a.png)

The rights are differents.

Have you already encountered this behaviour between `docker` command and `docker compose` command ?

**Comment by hmottestad** [comment]
I gave this a try locally but I'm not able to reproduce the issue using your docker-compose file.

Do your volumes already contain data from your previous 3.7.4 server/workbench?

**Comment by niio972** [comment]
Hi, you were right about this issue. This issue was due to the volumes that already contains data from your previous 3.7.4 server/workbench. 
I exported the data from my previous container volumes, removed this one and imported the previous data in the new container volumes.
Thanks you !

**Comment by hmottestad** [comment]
@barthanssens do you think this is something that we could fix on our end? Something that fixes the permissions on existing directories as part of the dockerfile?

**Comment by barthanssens** [comment]
Hmz, not sure. I hardly use docker-compose, so I could be wrong of course, but I assume it boils down to the permissions of the host directory / docker user on host (which is probably limited on purpose)... So perhaps it should be added to the documentation

**Comment by ticapix** [comment]
Hi,

I faced the same issue with docker-compose and latest 5.1.0 tomcat&jetty

The docker compose config is

```yaml
services:
  rdf4j:
    container_name: "rdf4j"
    image: "eclipse/rdf4j-workbench:5.1.0-tomcat"
    restart: always
    environment:
      - JAVA_OPTS=-Xms1g -Xmx4g
    ports:
      - "7000:8080"
    volumes:
      - /home/pierre/docker/rdf4j/data:/var/rdf4j
      - /home/pierre/docker/rdf4j/logs:/usr/local/tomcat/logs
```

and to fix the permission errors, on the host, I ran:

```shell
$ docker run --rm -it eclipse/rdf4j-workbench:5.1.0-tomcat id -u
101
$ cd /home/pierre/docker/rdf4j && sudo chown -R 101 data logs
```

**Comment by ticapix** [comment]
I think I managed to fix it with a standalone compose file, with a sidecar like below:

Of course, one would have to know that the user `tomcat` inside the `eclipse/rdf4j-workbench:5.1.0-tomcat` is 101, for example using cmd from the previous message.

```yaml
services:
  change-ownership:
    image: alpine
    user: root
    volumes:
      - /home/pierre/docker/rdf4j/data:/var/rdf4j
      - /home/pierre/docker/rdf4j/logs:/usr/local/tomcat/logs
    command: chown -R 101 /var/rdf4j /usr/local/tomcat/logs

  rdf4j:
    container_name: "rdf4j"
    image: "eclipse/rdf4j-workbench:5.1.0-tomcat"
    restart: always
    environment:
      - JAVA_OPTS=-Xms1g -Xmx4g
    ports:
      - "7000:8080"
    volumes:
      - /home/pierre/docker/rdf4j/data:/var/rdf4j
      - /home/pierre/docker/rdf4j/logs:/usr/local/tomcat/logs
    depends_on:
      change-ownership:
        condition: service_completed_successfully
```
