### ISSUE TITLE
Native store BTree RangeIterator NullPointerException regression

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#432]
(Migrated from https://openrdf.atlassian.net/browse/SES-1886)

The fix for SES-1867 seems to be causing an intermittent failure in a test on the Jenkins server with the following stacktrace:

java.lang.NullPointerException: null
    at org.openrdf.sail.nativerdf.btree.BTree$RangeIterator.findNext(BTree.java:2166)
    at org.openrdf.sail.nativerdf.btree.BTree$RangeIterator.next(BTree.java:2091)
    at org.openrdf.sail.nativerdf.NativeStatementIterator.getNextElement(NativeStatementIterator.java:65)
    at org.openrdf.sail.nativerdf.NativeStatementIterator.getNextElement(NativeStatementIterator.java:34)
    at info.aduna.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:91)
    at info.aduna.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:60)
    at info.aduna.iteration.ExceptionConvertingIteration.hasNext(ExceptionConvertingIteration.java:78)
    at info.aduna.iteration.IterationWrapper.hasNext(IterationWrapper.java:68)
    at info.aduna.iteration.FilterIteration.findNextElement(FilterIteration.java:79)
    at info.aduna.iteration.FilterIteration.hasNext(FilterIteration.java:54)
    at info.aduna.iteration.ConvertingIteration.hasNext(ConvertingIteration.java:73)
    at org.openrdf.query.algebra.evaluation.iterator.JoinIterator.getNextElement(JoinIterator.java:69)
    at org.openrdf.query.algebra.evaluation.iterator.JoinIterator.getNextElement(JoinIterator.java:30)
    at info.aduna.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:91)
    at info.aduna.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:60)
    at org.openrdf.query.algebra.evaluation.iterator.JoinIterator.getNextElement(JoinIterator.java:69)
    at org.openrdf.query.algebra.evaluation.iterator.JoinIterator.getNextElement(JoinIterator.java:30)
    at info.aduna.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:91)
    at info.aduna.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:60)
    at org.openrdf.query.algebra.evaluation.iterator.JoinIterator.getNextElement(JoinIterator.java:69)
    at org.openrdf.query.algebra.evaluation.iterator.JoinIterator.getNextElement(JoinIterator.java:30)
    at info.aduna.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:91)
    at info.aduna.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:60)
    at info.aduna.iteration.ConvertingIteration.hasNext(ConvertingIteration.java:73)
    at org.openrdf.query.algebra.evaluation.iterator.OrderIterator.createIteration(OrderIterator.java:90)
    at info.aduna.iteration.DelayedIteration.hasNext(DelayedIteration.java:73)
    at info.aduna.iteration.IterationWrapper.hasNext(IterationWrapper.java:68)
    at info.aduna.iteration.LimitIteration.hasNext(LimitIteration.java:73)
    at info.aduna.iteration.IterationWrapper.hasNext(IterationWrapper.java:68)
    at org.openrdf.sail.helpers.SailBaseIteration.hasNext(SailBaseIteration.java:61)
    at info.aduna.iteration.IterationWrapper.hasNext(IterationWrapper.java:68)
    at info.aduna.iteration.TimeLimitIteration.hasNext(TimeLimitIteration.java:62)
    at info.aduna.iteration.IterationWrapper.hasNext(IterationWrapper.java:68)
    at org.openrdf.repository.RepositoryConnectionTest.testOrderByQueriesAreInterruptable(RepositoryConnectionTest.java:1725)

**Comment by jamesrdf** [comment]
I cannot reproduce this
