### ISSUE TITLE
NPE From SERVICE Clause When Endpoint is Invalid

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#444]
(Migrated from https://openrdf.atlassian.net/browse/SES-1843)

When we make a SERVICE call that returns nothing the outer query fails with a NullPointerException when the SERVICE URL is wrong. The response from the endpoint is Content-Type: text/html;charset=utf-8, which cannot be parsed by SPARQLTupleQuery. A more graceful error is expected.

SELECT ?s ?dt
WHERE { 
  SERVICE http://localhost:8080/openrdf-workbench/repositories/K4/query {
    GRAPH http://example.com {
      ?s a http://example.com/staging/Trial .
      ?s rdfs:label "NothingToFind".
    }
  }
}

Caused by: java.lang.NullPointerException
    at java.util.ArrayList.<init>(ArrayList.java:131)
    at org.openrdf.repository.sparql.query.SPARQLTupleQuery.evaluate(SPARQLTupleQuery.java:49)
    at org.openrdf.query.algebra.evaluation.federation.SPARQLFederatedService.evaluate(SPARQLFederatedService.java:129)
    at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:861)
    at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:1074)
    at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:179)
    at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:1197)
    at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:1080)
    at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:179)
    at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:1151)
    at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:1065)
    at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:179)
    at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:1095)
    at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:179)
    at org.openrdf.sail.nativerdf.NativeStoreConnection.evaluateInternal(NativeStoreConnection.java:137)
    at org.openrdf.sail.helpers.SailConnectionBase.evaluate(SailConnectionBase.java:213)
    at org.openrdf.sail.helpers.SailConnectionWrapper.evaluate(SailConnectionWrapper.java:82)
    at org.openrdf.sail.helpers.SailConnectionWrapper.evaluate(SailConnectionWrapper.java:82)

**Comment by barthanssens** [comment]
An HTTPQueryEvaluationException might perhaps be slightly better than NPE ?

Reading the federated query spec, it is OK to fail if the service does not work, unless the SILENT keyword is given (https://www.w3.org/TR/sparql11-federated-query/#serviceFailure)

**Comment by jamesrdf** [comment]
The error from the master branch looks fine now:
  QueryEvaluationException: Server responded with an unsupported file format: text/html
