### ISSUE TITLE
UnknownShapesTest should not be flaky

### ISSUE THREAD

**Issue by erikgb** [eclipse/rdf4j#4457]
I have seen this test failing in multiple unrelated PR workflows.

Example: https://github.com/eclipse/rdf4j/actions/runs/4269384547/jobs/7432529052

```
Error:  org.eclipse.rdf4j.sail.shacl.UnknownShapesTest.testComplexPath  Time elapsed: 0.261 s  <<< ERROR!
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1661)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.eclipse.rdf4j.sail.shacl.UnknownShapesTest.testComplexPath(UnknownShapesTest.java:89)
```

**Comment by erikgb** [comment]
Another example: https://github.com/eclipse/rdf4j/actions/runs/4270340337/jobs/7434077749

**Comment by abrokenjester** [comment]
@hmottestad I have also seen this test be flaky - do you have any thoughts on the cause?
