### ISSUE TITLE
java.lang.ClassCastException: Cannot cast [Ljava.lang.Object; to org.eclipse.rdf4j.sail.helpers.AbstractSailConnection

### ISSUE THREAD

**Issue by naturzukunft** [eclipse/rdf4j#4565]
### Current Behavior

start to do a setup for a unit test:
```
public class SparqlQueryEvaluatorDefaultTest {

	private static final Resource CTX1 = Values.iri("http://example.com/ctx1");
	private static final IRI CTX2 = Values.iri("http://example.com/ctx2");
	private static final IRI TYP1 = Values.iri("http://example.com/typ1");
	private static final IRI TYP2 = Values.iri("http://example.com/typ2");

	@Test
	public void test() {

		Repository repo = new SailRepository(new MemoryStore());

		Model model = new ModelBuilder()
				.subject(Values.iri("http://example.com/user1/object1"))
					.add(TYP1, Values.literal("testValue_user1_obj1_1"))
					.add(TYP2, Values.literal("testValue_user1_obj1_2"))
				.subject(Values.iri("http://example.com/user1/object2"))
					.add(TYP1, Values.literal("testValue_user1_obj2_1"))
					.add(TYP2, Values.literal("testValue_user1_obj2_2"))
				.build();

		try (RepositoryConnection con = repo.getConnection()) {
			con.add(model, CTX1);
			con.getStatements(null, null, null).forEach(System.out::println);
		}
```
and got an exception:

```
java.lang.ClassCastException: Cannot cast [Ljava.lang.Object; to org.eclipse.rdf4j.sail.helpers.AbstractSailConnection
	at java.base/java.lang.Class.cast(Class.java:3946)
	at org.eclipse.rdf4j.sail.helpers.AbstractSailConnection.verifyIsOpen(AbstractSailConnection.java:169)
	at org.eclipse.rdf4j.sail.helpers.AbstractSailConnection.begin(AbstractSailConnection.java:209)
	at org.eclipse.rdf4j.sail.helpers.AbstractSailConnection.begin(AbstractSailConnection.java:187)
	at org.eclipse.rdf4j.repository.sail.SailRepositoryConnection.begin(SailRepositoryConnection.java:153)
	at org.eclipse.rdf4j.repository.base.AbstractRepositoryConnection.startLocalTransaction(AbstractRepositoryConnection.java:308)
	at org.eclipse.rdf4j.repository.base.AbstractRepositoryConnection.add(AbstractRepositoryConnection.java:370)
	at org.eclipse.rdf4j.http.server.readonly.sparql.SparqlQueryEvaluatorDefaultTest.test(SparqlQueryEvaluatorDefaultTest.java:36)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:95)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:91)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:60)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
	Suppressed: java.lang.invoke.WrongMethodTypeException: cannot convert MethodHandle(VarHandle,AbstractSailConnection,boolean,boolean)boolean to (VarHandle,Object[])boolean
		at java.base/java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:903)
		at java.base/java.lang.invoke.MethodHandle.asType(MethodHandle.java:870)
		at org.eclipse.rdf4j.sail.helpers.AbstractSailConnection.close(AbstractSailConnection.java:250)
		at org.eclipse.rdf4j.repository.sail.SailRepositoryConnection.close(SailRepositoryConnection.java:240)
		at org.eclipse.rdf4j.http.server.readonly.sparql.SparqlQueryEvaluatorDefaultTest.test(SparqlQueryEvaluatorDefaultTest.java:38)
		... 67 more

```

### Expected Behavior

no exception ;-)

### Steps To Reproduce

https://github.com/naturzukunft/rdf4j/blob/GH-4562-problemsWithNamedGraphsUsingSparqlQueryEvaluator/spring-components/spring-boot-sparql-web/src/test/java/org/eclipse/rdf4j/http/server/readonly/sparql/SparqlQueryEvaluatorDefaultTest.java

### Version

4.2.5-SNAPSHOT

### Are you interested in contributing a solution yourself?

No

### Anything else?

On the way to test https://github.com/eclipse/rdf4j/discussions/4562

**Comment by hmottestad** [comment]
Could you try this with 4.3.0-M3? I just tried with the develop branch and it didn't throw an exception, so might be fixed already.

**Comment by naturzukunft** [comment]
Which branch is 4.3.0-M3 ?

**Comment by naturzukunft** [comment]
Looks like just a tag of https://github.com/eclipse/rdf4j/commits/develop

**Comment by naturzukunft** [comment]
I've now a new branch based on develop: https://github.com/naturzukunft/rdf4j/tree/GH_4565-4.0.3_ClassCastException_Object_to_AbstractSailConnection
There is no Problem with the ClassCastException !

**Comment by hmottestad** [comment]
4.3.0 should be out later today.
