### ISSUE TITLE
AbstractRDFParser: Base IRI is not added to namespace table

### ISSUE THREAD

**Issue by MaximilianWenzel** [eclipse/rdf4j#4675]
### Current Behavior

Hello everyone, 

I'm having an issue parsing RDF Turtle files with declared base IRIs (see attached code :
`org.eclipse.rdf4j.rio.RDFParseException: Default namespace used but not defined [line 3]

	at org.eclipse.rdf4j.rio.helpers.RDFParserHelper.reportFatalError(RDFParserHelper.java:347)
	at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.reportFatalError(AbstractRDFParser.java:682)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.reportFatalError(TurtleParser.java:1308)
	at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.getNamespace(AbstractRDFParser.java:280)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseQNameOrBoolean(TurtleParser.java:967)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseValue(TurtleParser.java:573)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseSubject(TurtleParser.java:397)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseTriples(TurtleParser.java:332)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseStatement(TurtleParser.java:202)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:164)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:127)
	at org.eclipse.rdf4j.rio.RDFParser.parse(RDFParser.java:107)
	at TurtleParserTest.turtleParserTest(TurtleParserTest.java:23)`

Here is a minimal example to reproduce the issue (see attached maven project):

Turtle file
```
@base <http://www.example.org#> .
:s :p :o .
```

Java code
```Java
// dependency to rdf4j-rio-turtle 4.3.3
File turtleFile = new File("path/to/file");
TurtleParser parser = new TurtleParser();
parser.parse(new FileInputStream(turtleFile));
```
[parser-issue.zip](https://github.com/eclipse/rdf4j/files/12026153/parser-issue.zip)

The issue might be that when the base URI gets parsed, it is not added to the namespace table of the AbstractRDFParser class in the `setBaseURI(...)` method. I think it could be easily fixed (by someone who is more familiar with the project).

### Expected Behavior

The base IRI should be added to the namespace table in order to process prefixed IRIs appropriately. 

Here is the method:
org.eclipse.rdf4j.rio.helpers.AbstractRDFParser#setBaseURI(java.lang.String)
For the fix, I'm suggesting to add a line `namespaceTable.put("", this.baseURI);` to the method. Maybe someone who is familiar with the RDF4J project could validate this fix.

### Version

4.3.3

### Are you interested in contributing a solution yourself?

Perhaps?

**Comment by kenwenzel** [comment]
Hi @MaximilianWenzel,

you have to define the prefix as follows:
```
@prefix : <http://www.example.org#> .
```

See also https://stackoverflow.com/questions/34146707/turtle-difference-between-base-and-empty-prefix

I hope this helps.

Best regards,
Ken

**Comment by MaximilianWenzel** [comment]
Thank you for the timely answer and the reference! Unfortunately, I was not aware of the difference yet.
