### ISSUE TITLE
OutOfMemoryError in NativeStore with large values.hash files on 32-bit platforms

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#529]
(Migrated from https://openrdf.atlassian.net/browse/SES-724)

Due to http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6822107 the HashFile used by Sesame's NativeStore can run into an OutOfMemoryError when it needs to grow. This happens when there's insufficient memory address space to store the hash file's overflow buckets. This problem has been seen on 32-bit platforms where a considerable part of the ~2GB of address space is used for the java heap. The relevant part of the stack trace looks like this: java.io.IOException: Map failed at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:761) at sun.nio.ch.FileChannelImpl.transferToTrustedChannel(FileChannelImpl.java:450) at sun.nio.ch.FileChannelImpl.transferTo(FileChannelImpl.java:523) at org.openrdf.sail.nativerdf.datastore.HashFile.increaseHashTable(HashFile.java:405) at org.openrdf.sail.nativerdf.datastore.HashFile.storeID(HashFile.java:201) at org.openrdf.sail.nativerdf.datastore.DataStore.storeData(DataStore.java:158) at org.openrdf.sail.nativerdf.ValueStore.storeValue(ValueStore.java:319) at org.openrdf.sail.nativerdf.NativeStoreConnection.addStatement(NativeStoreConnection.java:381) ... 24 common frames omitted Caused by: java.lang.OutOfMemoryError: Map failed at sun.nio.ch.FileChannelImpl.map0(Native Method) at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:758) ... 31 common frames omitted

**Comment by jeenbroekstra** [comment]
Since the bug only occurs in Java 6 SDK (it was fixed in Java 7), this particular issue is no longer relevant.
