### ISSUE TITLE
nativerdf: id must be larger than 0, is: 0 (again)

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#533]
(Migrated from https://openrdf.atlassian.net/browse/SES-701)

This issue sounds similar to http://www.openrdf.org/issues/browse/SES-631 and to http://www.openrdf.org/issues/browse/SES-550 we are not able to reproduce it, it happens in the wild. We did not have the issue for the last two years of using previous sesame versions, our software didn't change too much. It may be related to changes done in sesame 2.3.0. here is the stacktrace: SCHWERWIEGEND: Encountered an unexpected problem while trying to add a statement java.lang.IllegalArgumentException: id must be larger than 0, is: 0 at org.openrdf.sail.nativerdf.btree.BTree.readNode(BTree.java:1210) at org.openrdf.sail.nativerdf.btree.BTree.access$700(BTree.java:45) at org.openrdf.sail.nativerdf.btree.BTree$Node.getChildNode(BTree.java:1543) at org.openrdf.sail.nativerdf.btree.AllocatedNodesList.crawlAllocatedNodes(AllocatedNodesList.java:279) at org.openrdf.sail.nativerdf.btree.AllocatedNodesList.crawlAllocatedNodes(AllocatedNodesList.java:279) at org.openrdf.sail.nativerdf.btree.AllocatedNodesList.crawlAllocatedNodes(AllocatedNodesList.java:279) at org.openrdf.sail.nativerdf.btree.AllocatedNodesList.crawlAllocatedNodes(AllocatedNodesList.java:265) at org.openrdf.sail.nativerdf.btree.AllocatedNodesList.initAllocatedNodes(AllocatedNodesList.java:227) at org.openrdf.sail.nativerdf.btree.AllocatedNodesList.allocateNode(AllocatedNodesList.java:181) at org.openrdf.sail.nativerdf.btree.BTree.createNewNode(BTree.java:1179) at org.openrdf.sail.nativerdf.btree.BTree.insertInNode(BTree.java:925) at org.openrdf.sail.nativerdf.btree.BTree.insertInTree(BTree.java:896) at org.openrdf.sail.nativerdf.btree.BTree.insertInTree(BTree.java:902) at org.openrdf.sail.nativerdf.btree.BTree.insertInTree(BTree.java:902) at org.openrdf.sail.nativerdf.btree.BTree.insertInTree(BTree.java:902) at org.openrdf.sail.nativerdf.btree.BTree.insert(BTree.java:843) at org.openrdf.sail.nativerdf.TripleStore.storeTriple(TripleStore.java:720) at org.openrdf.sail.nativerdf.NativeStoreConnection.addStatement(NativeStoreConnection.java:393) at org.openrdf.sail.nativerdf.NativeStoreConnection.addStatementInternal(NativeStoreConnection.java:346) at org.openrdf.sail.helpers.SailConnectionBase.addStatement(SailConnectionBase.java:331) at org.openrdf.sail.helpers.SailConnectionWrapper.addStatement(SailConnectionWrapper.java:124) at org.semanticdesktop.nepomuk.comp.rdfrepository.crappyinferencer.CrappyInferencingConnection.addStatement CrappyInferencingConnection.java:286) at org.openrdf.sail.helpers.SailConnectionWrapper.addStatement(SailConnectionWrapper.java:124) at org.openrdf.sail.lucene.LuceneSailConnection.addStatement(LuceneSailConnection.java:136) at org.openrdf.sail.helpers.SailConnectionWrapper.addStatement(SailConnectionWrapper.java:124) at org.semanticdesktop.nepomuk.comp.rdfrepository.synchronizedsail.SynchonizedSailConnection.addStatement(SynchonizedSailConnection.java:57) at org.openrdf.repository.sail.SailRepositoryConnection.addWithoutCommit(SailRepositoryConnection.java:228) at org.openrdf.repository.base.RepositoryConnectionBase.addWithoutCommit(RepositoryConnectionBase.java:547) at org.openrdf.repository.base.RepositoryConnectionBase.add(RepositoryConnectionBase.java:447) at org.openrdf.rdf2go.RepositoryModelSet.update(RepositoryModelSet.java:1097) at org.semanticdesktop.nepomuk.comp.pimoservice.client.DiffModelSet.commit(DiffModelSet.java:740) at org.semanticdesktop.nepomuk.comp.pimoservice.client.ClientSession.commit(ClientSession.java:1026) at org.semanticdesktop.nepomuk.psew.pimo.editors.PimoEditorSWT$PimoEditorSavingJob.run(PimoEditorSWT.java:165) at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by jeenbroekstra** [comment]
Very old, have not seen this since in the wild, assuming fixed subsequently by other improvements to native store.
