### ISSUE TITLE
SPARQL Update ClassCastException

### ISSUE THREAD

**Issue by skodapetr** [eclipse/rdf4j#610]
RDF4J version 2.0.1.
The program:
```
    public static final String QUERY = ""
            + "DELETE {\n"
            + "  ?contract ?p1 ?o1 .\n"
            + "  ?o1 ?p2 ?o2 .\n"
            + "}\n"
            + "WHERE {\n"
            + "  ?contract a <http://localhost/Type> ;\n"
            + "    ?p1 ?o1 .\n"
            + "  OPTIONAL {\n"
            + "    ?o1 ?p2 ?o2 .\n"
            + "    FILTER isBlank(?o1) \n"
            + "  }\n"
            + "}";

    public static void main(String[] args) throws Exception {
        final Repository repository = new SailRepository(new MemoryStore());
        repository.initialize();
        //
        final ValueFactory vf = SimpleValueFactory.getInstance();
        final IRI iri = vf.createIRI("http://localhost/resources");
        Repositories.consume(repository, (connection) -> {
            connection.add(vf.createStatement(
                    iri, RDF.TYPE, vf.createIRI("http://localhost/Type")));
            connection.add(vf.createStatement(
                    iri, SKOS.PREF_LABEL, vf.createLiteral("String")));
        });
        //
        Repositories.consume(repository, (connection) -> {
            connection.prepareUpdate(QUERY).execute();
        });
        repository.shutDown();
    }
```
The output:
```
12:51:35.006 WARN  o.e.r.s.m.MemoryStoreConnection - Rolling back transaction due to connection close
java.lang.Throwable: null
	at org.eclipse.rdf4j.sail.helpers.AbstractSailConnection.close(AbstractSailConnection.java:224) [rdf4j-sail-api-2.0.1.jar:na]
	at org.eclipse.rdf4j.repository.sail.SailRepositoryConnection.close(SailRepositoryConnection.java:193) [rdf4j-repository-sail-2.0.1.jar:na]
	at org.eclipse.rdf4j.repository.util.Repositories.get(Repositories.java:139) [rdf4j-repository-api-2.0.1.jar:na]
	at org.eclipse.rdf4j.repository.util.Repositories.consume(Repositories.java:53) [rdf4j-repository-api-2.0.1.jar:na]
	at skodape.sandbox.rdf4j.QueryDelete.main(QueryDelete.java:46) [classes/:na]
Exception in thread "main" java.lang.ClassCastException: org.eclipse.rdf4j.sail.memory.model.MemLiteral cannot be cast to org.eclipse.rdf4j.model.Resource
	at org.eclipse.rdf4j.repository.sail.helpers.SailUpdateExecutor.deleteBoundTriples(SailUpdateExecutor.java:598)
	at org.eclipse.rdf4j.repository.sail.helpers.SailUpdateExecutor.executeModify(SailUpdateExecutor.java:507)
	at org.eclipse.rdf4j.repository.sail.helpers.SailUpdateExecutor.executeUpdate(SailUpdateExecutor.java:126)
	at org.eclipse.rdf4j.repository.sail.SailUpdate.execute(SailUpdate.java:64)
	at skodape.sandbox.rdf4j.QueryDelete.lambda$main$1(QueryDelete.java:47)
	at org.eclipse.rdf4j.repository.util.Repositories.lambda$consume$11(Repositories.java:54)
	at org.eclipse.rdf4j.repository.util.Repositories.get(Repositories.java:127)
	at org.eclipse.rdf4j.repository.util.Repositories.consume(Repositories.java:53)
	at skodape.sandbox.rdf4j.QueryDelete.main(QueryDelete.java:46)
```
The evaluateWhereClause return following bindings:
```p1 = RDF.TYPE | o1 = http://localhost/Type | contract = http://localhost/resources```
```p1 = SKOS.PREF_LABEL | o1 = "String" | contract = http://localhost/resources```
which is ok. 

But then deleteBoundTriples function try to map this bindings against all delete patterns, including the ```?o1 ?p2 ?o2```.

In this pattern o1 is used as a subject = Resource, while it is in fact a Literal. 

Could this be fixed be moving the "not null" (all bind) checks (in SailUpdateExcutor.deleteBoundTriples) before casting?

**Comment by ansell** [comment]
RDF4J doesn't support Literal's occurring in the subject position. You need to modify your query to filter out non-literals so that you aren't attempting to create RDF triples of that structure.

**Comment by jeenbroekstra** [comment]
@ansell That's what I thought too, but if I read the [SPARQL 1.1 update spec](https://www.w3.org/TR/sparql11-update/#deleteInsert) correctly, we may actually have to filter and ignore these illegal constructs, rather than produce an error. See this bit about behavior of INSERT:

> If any instantiation arising from the solution sequence produces a triple containing an unbound variable or an illegal RDF construct, such as a literal in subject or predicate position, then that triple is not inserted. 

I haven't pinpointed the similar definition for DELETE behavior but it would be consistent if it is defined that way.

**Comment by jeenbroekstra** [comment]
Ah, here we go, in [section 3.1.3: DELETE/INSERT](https://www.w3.org/TR/sparql11-update/#deleteInsert), third paragraph: 

> If any solution produces a triple containing an unbound variable or an illegal RDF construct, such as a literal in a subject or predicate position, then that triple is not included when processing the operation: INSERT will not instantiate new data in the output graph, and DELETE will not remove anything.

**Comment by ansell** [comment]
Okay, so we need to detect and ignore that binding (and add a regression test as it doesn't seem to be tested by the standard compliance suite).
