### ISSUE TITLE
Lucene SPIN: ValueExprEvaluationException when predicate is variable  

### ISSUE THREAD

**Issue by jgrzebyta** [eclipse/rdf4j#771]
I need to process more complex data (made by **Apache Any23**) with sparql query where predicate should be found using Lucene index (new syntax referenced issues #220 #235) and I have quite complex stack trace - bellow.

In my fork I created example query (branch *issues/#771-evaluation*).

```
prefix t: <urn:test.org/onto#> 
sb.append("prefix kw: <urn:test.org/key-words/> 

select ?term_string ?sub ?score where { 
  ?pred_map rdfs:label "keyWord" ; 
  t:column ?pred . 
  [] ?pred ?term . 
  bind(str(?term) as ?term_string) . 
  (?term_string search:allMatches search:score) search:search (?sub ?score) . 
  ?sub a t:Data .
}
```

stack trace is:

```
org.eclipse.rdf4j.query.algebra.evaluation.ValueExprEvaluationException
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategy.evaluate(StrictEvaluationStrategy.java:1181)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategy.evaluate(StrictEvaluationStrategy.java:1065)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.TupleFunctionEvaluationStrategy.evaluate(TupleFunctionEvaluationStrategy.java:87)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.TupleFunctionEvaluationStrategy.evaluate(TupleFunctionEvaluationStrategy.java:69)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.JoinIterator.<init>(JoinIterator.java:44)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategy.evaluate(StrictEvaluationStrategy.java:918)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategy.evaluate(StrictEvaluationStrategy.java:881)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategy.evaluate(StrictEvaluationStrategy.java:240)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.TupleFunctionEvaluationStrategy.evaluate(TupleFunctionEvaluationStrategy.java:72)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.JoinIterator.getNextElement(JoinIterator.java:68)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.JoinIterator.getNextElement(JoinIterator.java:20)
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:90)
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:52)
	at org.eclipse.rdf4j.common.iteration.DelayedIteration.hasNext(DelayedIteration.java:71)
	at org.eclipse.rdf4j.common.iteration.UnionIteration.getNextElement(UnionIteration.java:69)
	at org.eclipse.rdf4j.common.iteration.UnionIteration.getNextElement(UnionIteration.java:86)
	at org.eclipse.rdf4j.common.iteration.UnionIteration.getNextElement(UnionIteration.java:86)
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:90)
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:52)
	at org.eclipse.rdf4j.common.iteration.ConvertingIteration.hasNext(ConvertingIteration.java:68)
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.QueryContextIteration.hasNext(QueryContextIteration.java:43)
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63)
	at org.eclipse.rdf4j.query.QueryResults.report(QueryResults.java:256)
	at org.eclipse.rdf4j.repository.sail.SailTupleQuery.evaluate(SailTupleQuery.java:94)
```

**Comment by jgrzebyta** [comment]
Parsed SPARQL query:

[log_parsed.txt](https://github.com/eclipse/rdf4j/files/798089/log_parsed.txt)

**Comment by jgrzebyta** [comment]
I found Byway for the issue. I separated finding `?term_string` and search query using the sub-select query:

```
prefix t: <urn:test.org/onto#>
 prefix kw: <urn:test.org/key-words/>

select ?term_string ?sub ?score where { 
(?term_string search:allMaches search:score) search:search (?sub ?score) . 
?sub a t:Data . 
   { select ?term_string where 
       { 
       ?pred_map rdfs:label "keyWord" ; 
       t:column ?pred . 
       [] ?pred ?term . 
       bind(str(?term) as ?term_string) . 
       } 
   }
 } 
```

Merged with PR-739.
