### ISSUE TITLE
NullPointerException in SailSourceModel

### ISSUE THREAD

**Issue by blevasseur** [eclipse/rdf4j#774]
I am getting an intermittent NullPointerException in SailSourceModel.java. Specifically when I am adding triples to the RDF4J server and running multiple queries at the same time I sometimes get the following exception in the RDF4J server log:

`
[ERROR] 2017-02-23 10:57:25,945 [repositories/rjk-test] Error while handling request
java.lang.NullPointerException: null
	at org.eclipse.rdf4j.sail.nativerdf.SailSourceModel.dataset(SailSourceModel.java:403)
	at org.eclipse.rdf4j.sail.nativerdf.SailSourceModel.contains(SailSourceModel.java:231)
	at org.eclipse.rdf4j.sail.nativerdf.MemoryOverflowModel.contains(MemoryOverflowModel.java:111)
	at org.eclipse.rdf4j.model.impl.FilteredModel.contains(FilteredModel.java:147)
	at org.eclipse.rdf4j.model.impl.AbstractModel.isEmpty(AbstractModel.java:45)
	at org.eclipse.rdf4j.sail.base.SailDatasetImpl.union(SailDatasetImpl.java:336)
	at org.eclipse.rdf4j.sail.base.SailDatasetImpl.getStatements(SailDatasetImpl.java:305)
	at org.eclipse.rdf4j.sail.base.DelegatingSailDataset.getStatements(DelegatingSailDataset.java:74)
	at org.eclipse.rdf4j.sail.base.DelegatingSailDataset.getStatements(DelegatingSailDataset.java:74)
	at org.eclipse.rdf4j.sail.base.UnionSailDataset.getStatements(UnionSailDataset.java:101)
	at org.eclipse.rdf4j.sail.base.SailDatasetTripleSource.getStatements(SailDatasetTripleSource.java:47)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategy.evaluate(StrictEvaluationStrategy.java:531)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategy.evaluate(StrictEvaluationStrategy.java:234)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategy.evaluate(StrictEvaluationStrategy.java:783)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategy.evaluate(StrictEvaluationStrategy.java:673)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategy.evaluate(StrictEvaluationStrategy.java:237)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategy.evaluate(StrictEvaluationStrategy.java:706)
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategy.evaluate(StrictEvaluationStrategy.java:237)
	at org.eclipse.rdf4j.sail.base.SailSourceConnection.evaluateInternal(SailSourceConnection.java:246)
	at org.eclipse.rdf4j.sail.helpers.AbstractSailConnection.evaluate(AbstractSailConnection.java:267)
	at org.eclipse.rdf4j.repository.sail.SailTupleQuery.evaluate(SailTupleQuery.java:54)
	at org.eclipse.rdf4j.http.server.repository.RepositoryController.handleRequestInternal(RepositoryController.java:208)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:147)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at com.github.ziplet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:300)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
`

This error refers to line 403 in SailSourceModel (https://github.com/eclipse/rdf4j/blob/2.2/core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/SailSourceModel.java#L403). There is a check if the object sink is null on line 398, so somehow sink is not null when the check happens but then before line 403 is executed sink becomes null. Since I am only getting this problem sometimes on a couple of systems (and others I am working with are not seeing it at all) I am guessing there is some race condition and threading problem.

Since this appears to be a race condition I could not create a repeatable test but here is some basic information on my setup.

- Java Version: 1.8.0_112

- RDF4J Server Version : 2.2

- RDF4J  Workbench Version: 2.2

- RDF4J Client Side Library Version: 2.2 (rdf4j-repository-sail, rdf4j-sail-memory, rdf4j-rio-turtle, rdf4j-repository-http, rdf4j-repository-manager)

- Ran RDF4J Server and Workbench in Apache Tomcat 8.5.11

- Created a "Native Java Store" for my test repository

On my client side I have multiple threads where one is uploading a large number of triples using RepositoryConnection.add and some threads are querying data with RepositoryConnection.prepareTupleQuery and then calling evaluate on the TupleQuery. I normally am sending lots of queries at the same time as the triples are being added.

I do not know if this issue is connected to specific uses of the client library for adding and querying or if it has more to do with running multiple requests against the server at once. Even if I am not using the client library properly, this should not result in a null pointer exception where there is already a check that the object is not null.

**Comment by ansell** [comment]
Multi-threading can explain why the NPE occurs, due to thread interleaving while the method is executing on two separate threads. If both threads pass the "!= null" guard, then one thread changes the reference at line 404, the previous thread could throw an NPE at either line 403 or 400.

It requires the sink variable to be locally dereferenced to a copy of the variable before operating on it, and also requires the field to be declared as volatile so that changes are propagated to other threads.
