### ISSUE TITLE
RDFStoreTest.testMultiThreadedAccess may be silently failing

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#84]
(Migrated from https://openrdf.atlassian.net/browse/SES-2289 )

The testMultiThreadedAccess test in RDFStoreTest may be silently failing (with a stacktrace to the console), and most of the test doesn't seem to be executed.

A full multi-threaded test would need to use CountDownLatch or similar to make the test consistent. The current use of a busy-wait loop and Thread.sleep testing con.isActive doesn't seem to work to make sure that only one thread gets a transaction open at one time.

The exception printed to the console is an AssertionError with the following trace:

org.openrdf.sail.SailException: a transaction is already active on this connection.
    at org.openrdf.sail.helpers.AbstractSailConnection.begin(AbstractSailConnection.java:196)
    at org.openrdf.sail.helpers.AbstractSailConnection.begin(AbstractSailConnection.java:170)
    at org.openrdf.sail.RDFStoreTest$1.run(RDFStoreTest.java:741)
    at java.lang.Thread.run(Thread.java:745)
Exception in thread "B (parallel)" java.lang.AssertionError: a transaction is already active on this connection.
    at org.junit.Assert.fail(Assert.java:88)
    at org.openrdf.sail.RDFStoreTest$1.run(RDFStoreTest.java:764)
    at java.lang.Thread.run(Thread.java:745)

I have only tested it on master right now (just after 4.0.0-M1), but it may also apply to earlier versions.

**Comment by jeenbroekstra** [comment]
This test has been disabled for a while now as it is fundamentally flawed anyway.
