### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by rune66** [eclipse/rdf4j#853]
I'm using rdf4j in a web application running on Tomcat (instance 1). rdf4j runs in a seperate Tomcat container (instance 2).

I'm doing a multithreaded stress test (10 concurrent threads) of my system which runs fine for many hours (60k requests being processed for example). At some point in time one some of the queries start to fail with various exceptions, like:

Exception in thread "rdf4j-sesameclientimpl-7484" java.lang.ArrayIndexOutOfBoundsException: length == 8441 off == -249 buffer length == 8192
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
        at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:266)
        at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:227)
        at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:186)
        at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:215)
        at org.apache.http.impl.io.ChunkedInputStream.close(ChunkedInputStream.java:316)
        at org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:140)
        at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
        at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:174)
        at org.eclipse.rdf4j.query.resultio.helpers.BackgroundTupleResult.handleClose(BackgroundTupleResult.java:73)
        at org.eclipse.rdf4j.common.iteration.AbstractCloseableIteration.close(AbstractCloseableIteration.java:51)
        at org.eclipse.rdf4j.query.resultio.helpers.BackgroundTupleResult.run(BackgroundTupleResult.java:119)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "rdf4j-sesameclientimpl-7480" java.lang.ArrayIndexOutOfBoundsException: length == 8441 off == -249 buffer length == 8192

15 06:33:02.313 [http-nio-8080-exec-7] ERROR KLERepository 192 getCurrentVersionInfo - Catching org.eclipse.rdf4j.repository.http.HTTPQueryEvaluationException
	at org.eclipse.rdf4j.repository.http.HTTPTupleQuery.evaluate(HTTPTupleQuery.java:53) ~[rdf4j-repository-http-2.2.2.jar:?]
	at dk.rdfined.kle.model.KLERepository.getCurrentVersionInfo(KLERepository.java:172) [classes/:?]
	at dk.rdfined.kle.controller.Controller.getLastModified(Controller.java:274) [classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:631) [servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.15]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.15]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.15]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.15]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.15]
	at dk.rdfined.kle.controller.CacheControlFilter.doFilter(CacheControlFilter.java:66) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.15]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.15]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [catalina.jar:8.5.15]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:8.5.15]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) [catalina.jar:8.5.15]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [catalina.jar:8.5.15]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80) [catalina.jar:8.5.15]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624) [catalina.jar:8.5.15]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.15]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [catalina.jar:8.5.15]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799) [tomcat-coyote.jar:8.5.15]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.15]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861) [tomcat-coyote.jar:8.5.15]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455) [tomcat-coyote.jar:8.5.15]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.15]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_131]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.15]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.2.jar:4.5.2]
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.execute(SPARQLProtocolSession.java:1113) ~[rdf4j-http-client-2.2.2.jar:?]
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.executeOK(SPARQLProtocolSession.java:1066) ~[rdf4j-http-client-2.2.2.jar:?]
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.sendTupleQueryViaHttp(SPARQLProtocolSession.java:834) ~[rdf4j-http-client-2.2.2.jar:?]
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.getBackgroundTupleQueryResult(SPARQLProtocolSession.java:720) ~[rdf4j-http-client-2.2.2.jar:?]
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.sendTupleQuery(SPARQLProtocolSession.java:381) ~[rdf4j-http-client-2.2.2.jar:?]
	at org.eclipse.rdf4j.repository.http.HTTPTupleQuery.evaluate(HTTPTupleQuery.java:49) ~[rdf4j-repository-http-2.2.2.jar:?]
	... 29 more
Caused by: org.apache.http.ProtocolException: The server failed to respond with a valid HTTP response
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:151) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261) ~[httpcore-4.4.4.jar:4.4.4]
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165) ~[httpcore-4.4.4.jar:4.4.4]
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272) ~[httpcore-4.4.4.jar:4.4.4]
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124) ~[httpcore-4.4.4.jar:4.4.4]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.2.jar:4.5.2]
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.execute(SPARQLProtocolSession.java:1113) ~[rdf4j-http-client-2.2.2.jar:?]
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.executeOK(SPARQLProtocolSession.java:1066) ~[rdf4j-http-client-2.2.2.jar:?]
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.sendTupleQueryViaHttp(SPARQLProtocolSession.java:834) ~[rdf4j-http-client-2.2.2.jar:?]
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.getBackgroundTupleQueryResult(SPARQLProtocolSession.java:720) ~[rdf4j-http-client-2.2.2.jar:?]
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.sendTupleQuery(SPARQLProtocolSession.java:381) ~[rdf4j-http-client-2.2.2.jar:?]
	at org.eclipse.rdf4j.repository.http.HTTPTupleQuery.evaluate(HTTPTupleQuery.java:49) ~[rdf4j-repository-http-2.2.2.jar:?]
	... 29 more

The exact same query is used every time. I have also experienced that the exceptions resulted in a hanging thread but apparently only when I didn’t supply the auto closable try/catch with a dedicated catch expression.

**Comment by jamesrdf** [comment]
This looks like the stack trace of the client, but I think that error is from the server. Can you post to the mailing list the relevant server log entries?

**Comment by rune66** [comment]
Hi James - There are no exceptions in the server-log (under Aduna->server->logs). I think this is a client side issue with the libraries.

**Comment by rune66** [comment]
Any idea what is going on?

**Comment by jamesrdf** [comment]
It looks like there was an error reading the tuple response, leaving the stream in an invalid state, and when the client tried to close the stream it threw ArrayIndexOutOfBoundsException. It is not clear what the initial exception was, but it looks like it was from dk.rdfined.kle.model.KLERepository. Try to see if you can reproduce this without RDFined and post your results to the mailing list.

**Comment by rune66** [comment]
How can the client cause “an error reading the tuple response”?

The method that is being called looks like this:

    public static String getCurrentVersionInfo(String property) {
        String returnvalue = null;
        String query = null;
        try (RepositoryConnection conn = getRepository(versionsRepositoryUri).getConnection()) {
            query = String.format(currentVersionInfoQuery, getDefaultRepositoryUri().substring(getDefaultRepositoryUri().lastIndexOf("/") + 1));
            TupleQuery tupleQuery = conn.prepareTupleQuery(QueryLanguage.SPARQL, query);
            try (TupleQueryResult result = tupleQuery.evaluate()) {
                if (result.hasNext()) {
                    BindingSet bindings = result.next();
                }
            }
        } catch (Exception e) {
            logger.catching(e);
        }
        return returnvalue;
    }

The problem is not so much the exception but that the service actually goes into some kind of deadlocked state, and thus the entire application freezes.

I found out that the problem apparently goes away if I add another catch clause, like this:

    public static String getCurrentVersionInfo(String property) {
        String returnvalue = null;
        String query = null;
        try (RepositoryConnection conn = getRepository(versionsRepositoryUri).getConnection()) {
            query = String.format(currentVersionInfoQuery, getDefaultRepositoryUri().substring(getDefaultRepositoryUri().lastIndexOf("/") + 1));
            TupleQuery tupleQuery = conn.prepareTupleQuery(QueryLanguage.SPARQL, query);
            try (TupleQueryResult result = tupleQuery.evaluate()) {
                if (result.hasNext()) {
                    BindingSet bindings = result.next();
                }
            } catch (Exception e) {
                logger.catching(e);
            }
        } catch (Exception e) {
            logger.catching(e);
        }
        return returnvalue;
    }

Does that make sense?

**Comment by jamesrdf** [comment]
It is possible the server becomes overloaded and starts to terminate requests. This could happen in a number of ways and, if so, it is likely that those error conditions are not well understood, nor have clear messages, nor clear error handling paths. If you are concerned with the error handling, in the event of overloaded server, please open a new issue once you have a way for others to reproduce the error. However, if you are more concerned with the server getting overloaded in the first place, then you can start by posting your requirements to the mailing list for help and/or contacting commercial support at ontotext.com
