### ISSUE TITLE
committing large file to HTTPRepository throws RejectedExecutionException

### ISSUE THREAD

**Issue by s7ygian** [eclipse/rdf4j#880]
Hi,

I want to write large RDF turtle files (up to 100 MB) via RDF4J HTTP client (version 2.2.2) to a java native store in RDF4J Server (version 2.2.2) via this java code:

```java
ValueFactory valueFactory = SimpleValueFactory.getInstance();
final IRI iri = valueFactory.createIRI("urn:test_iri");
final IRI context = valueFactory.createIRI("urn:test_context");
Repository repository = new HTTPRepository("http://localhost:8080/rdf4j-server/", "test");
repository.initialize();
RepositoryConnection tripleStoreConnection = null;
try {
	tripleStoreConnection = repository.getConnection();
	tripleStoreConnection.begin();
        tripleStoreConnection.clear(context);
	tripleStoreConnection.add(file, iri, RDFFormat.TURTLE, context);
	tripleStoreConnection.commit();
} catch (final Exception e) {
	// print exception
} finally {
	try {
		if (tripleStoreConnection != null) {
			tripleStoreConnection.close();
		}
	} catch (final Exception e) {
		// print exception
	}
}
```

Client and server are running in the same tomcat instance on a CentOS7 VM.

Unfortunately in most cases (not always) the server throws a RejectedExecutionException (see below) during commit phase after up to 20 minutes. Curiously the commit works after several retries (the bigger the file the more retries are necessary). The last commit needs only a few seconds. During commit phase the number of disk writes per second is very high (up to 1300 writes per second) but the throughput per write is very small (up to 6 KB per write).

Does anybody has an explanation for this strange behavior? Is there an alternative way for fast and robust writing large RDF files to a HTTP repository via RDF4J?

Thanks in advance.

```
[INFO ] 2017-08-03 15:14:33,665 [repositories/test] POST transaction start
[INFO ] 2017-08-03 15:14:33,720 [repositories/test] transaction started
[INFO ] 2017-08-03 15:14:33,819 [repositories/test] PUT txn operation
[INFO ] 2017-08-03 15:14:33,996 [repositories/test] PUT txn operation request finished.
[INFO ] 2017-08-03 15:14:34,775 [repositories/test] PUT txn operation
[INFO ] 2017-08-03 15:26:09,885 [repositories/test] PUT txn operation request finished.
[WARN ] 2017-08-03 15:26:09,969 [rdf4j-transaction-0] Rolling back transaction due to connection close
[WARN ] 2017-08-03 15:26:09,970 [repositories/test] deregistered expired transaction cbc6cedf-6099-4ceb-8cdd-f9d8744a2dc8
[INFO ] 2017-08-03 15:26:09,972 [repositories/test] PUT txn operation
[ERROR] 2017-08-03 15:26:09,978 [repositories/test] Error while handling request (500)
org.eclipse.rdf4j.http.server.ServerHTTPException: Transaction handling error: Task java.util.concurrent.FutureTask@37727308 rejected from java.util.concurrent.ThreadPoolExecutor@69baa56d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 5]
	at org.eclipse.rdf4j.http.server.repository.transaction.TransactionController.processModificationOperation(TransactionController.java:277)
	at org.eclipse.rdf4j.http.server.repository.transaction.TransactionController.handleRequestInternal(TransactionController.java:182)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:147)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:653)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.github.ziplet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:300)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@37727308 rejected from java.util.concurrent.ThreadPoolExecutor@69baa56d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 5]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:681)
	at org.eclipse.rdf4j.http.server.repository.transaction.Transaction.submit(Transaction.java:502)
	at org.eclipse.rdf4j.http.server.repository.transaction.Transaction.commit(Transaction.java:168)
	at org.eclipse.rdf4j.http.server.repository.transaction.TransactionController.processModificationOperation(TransactionController.java:258)
	... 33 common frames omitted
[ERROR] 2017-08-03 15:26:10,093 [repositories/test] Error while handling request
org.eclipse.rdf4j.repository.RepositoryException: transaction with id cbc6cedf-6099-4ceb-8cdd-f9d8744a2dc8 not registered.
	at org.eclipse.rdf4j.http.server.repository.transaction.ActiveTransactionRegistry.getTransaction(ActiveTransactionRegistry.java:139)
	at org.eclipse.rdf4j.http.server.repository.transaction.TransactionController.handleRequestInternal(TransactionController.java:113)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:147)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doDelete(FrameworkServlet.java:894)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:656)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.github.ziplet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:300)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by elky87** [comment]
Hi @s7ygian this seems to be related with the issue I reported https://github.com/eclipse/rdf4j/issues/852

Problem is that you maybe run into a connection timeout and because of that your transaction gets thrown away: you cann see that in this part of the error message 
transaction with id cbc6cedf-6099-4ceb-8cdd-f9d8744a2dc8 not registered.

standard timeout is after 60seconds, meaning if you do nothing on the httpconnection in 60 seconds, then your transaction is thrown away.

On startup you can supply the following parameter -Drdf4j.server.txn.registry.timeout=0 this will give you no timeout at all.

Also, if you use try-with blocks you can get rid of the ugly finally blocks

try(RepositoryConnection tripleStoreConnection = repository.getConnection()) {
//do something
}

**Comment by elky87** [comment]
More general answer how to handle big files: http://www.rivuli-development.com/further-reading/sesame-cookbook/loading-large-file-in-sesame-native/

**Comment by jgrzebyta** [comment]
Hi @s7ygian The chanking solution IMHO is not good solution because there is built-in chanking within **HTTPRepositoryConnection** already. The pack size is fixed on 200000 statements using the constant. In my PR I made the size change-able so hope the feature will be updated soon.

**Comment by jgrzebyta** [comment]
Might be related with #750 . I had a file opened properly in a transaction but for some file (not so big) the transaction was just broken. Loading the same file to a local repository was successful.

**Comment by greenguy33** [comment]
@elky87 I was having this same issue with large transactions using RDF4J with Ontotext GraphDB, but supplying parameter `-Drdf4j.server.txn.registry.timeout=0` to GraphDB on startup appears to have fixed it.
