### ISSUE TITLE
Make RDF4J compile with Java 9

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#919]
This is an issue to track all modifications that will be necessary to have RDF4J compile and run with Java 9.

**Comment by hmottestad** [comment]
And now we have a branch.

**Comment by hmottestad** [comment]
## Incompatible maven plugins
 - 

## Maven plugins that have been upgraded
 -

**Comment by hmottestad** [comment]
## Other notable changes

 - building and running require the java.xml.bind module

**Comment by hmottestad** [comment]
Issue with Lucene that uses an undocumented Java api. 

```
Caused by: java.lang.IllegalAccessException: class org.apache.lucene.store.MMapDirectory$2$1 cannot access class jdk.internal.ref.Cleaner (in module java.base) because module java.base does not export jdk.internal.ref to unnamed module @559c09b7
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361) ~[na:na]
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:589) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:556) ~[na:na]
        at org.apache.lucene.store.MMapDirectory$2$1.run(MMapDirectory.java:294) ~[lucene-core-5.2.1.jar:5.2.1 1684708 - shalin - 2015-06-10 23:11:06]
        at org.apache.lucene.store.MMapDirectory$2$1.run(MMapDirectory.java:286) ~[lucene-core-5.2.1.jar:5.2.1 1684708 - shalin - 2015-06-10 23:11:06]
        at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
        at org.apache.lucene.store.MMapDirectory$2.freeBuffer(MMapDirectory.java:286) ~[lucene-core-5.2.1.jar:5.2.1 1684708 - shalin - 2015-06-10 23:11:06]
        ... 38 common frames omitted
```


More info here: http://mail.openjdk.java.net/pipermail/jigsaw-dev/2016-August/009032.html

**Comment by jamesrdf** [comment]
The develop branches can now compile under jdk9 when using the MAVEN_OPTS="--add-modules=java.xml.bind" environment variable. That can be stored in .mavenrc or the project's .mvn/jvm.confg file. This Java parameter only works if jdk9 is used, fails on jdk8.
