### ISSUE TITLE
CONSTRUCT statement not working with SPARQL endpoint

### ISSUE THREAD

**Issue by amalic** [eclipse/rdf4j#982]
I am getting errors when executing CONSTRUCT statements (see sample code below) against various SPARQL endpoints.

Against Ontotext GraphDB
```
Exception in thread "main" org.eclipse.rdf4j.query.QueryEvaluationException: Server responded with an unsupported file format: application/rdf+xml
	at org.eclipse.rdf4j.repository.sparql.query.SPARQLTupleQuery.evaluate(SPARQLTupleQuery.java:50)
	at nl.unimaas.ids.Main.main(Main.java:30)
Caused by: org.eclipse.rdf4j.repository.RepositoryException: Server responded with an unsupported file format: application/rdf+xml
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.lambda$getBackgroundTupleQueryResult$0(SPARQLProtocolSession.java:726)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.getBackgroundTupleQueryResult(SPARQLProtocolSession.java:725)
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.sendTupleQuery(SPARQLProtocolSession.java:381)
	at org.eclipse.rdf4j.repository.sparql.query.SPARQLTupleQuery.evaluate(SPARQLTupleQuery.java:43)
	... 1 more
```

Virtuoso
```
Exception in thread "main" org.eclipse.rdf4j.query.QueryEvaluationException: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>406 Not Acceptable</title>
</head><body>
<h1>406 Not Acceptable</h1>
<p>An appropriate representation of the requested resource sparql could not be found on this server.</p>
Available variant(s):
<ul>
<li><a href="sparql">sparql</a> , type application/rdf+xml, charset UTF-8</li>
</ul>
</body></html>
	at org.eclipse.rdf4j.repository.sparql.query.SPARQLTupleQuery.evaluate(SPARQLTupleQuery.java:50)
	at nl.unimaas.ids.Main.main(Main.java:30)
Caused by: org.eclipse.rdf4j.repository.RepositoryException: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>406 Not Acceptable</title>
</head><body>
<h1>406 Not Acceptable</h1>
<p>An appropriate representation of the requested resource sparql could not be found on this server.</p>
Available variant(s):
<ul>
<li><a href="sparql">sparql</a> , type application/rdf+xml, charset UTF-8</li>
</ul>
</body></html>
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.execute(SPARQLProtocolSession.java:1143)
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.executeOK(SPARQLProtocolSession.java:1066)
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.sendTupleQueryViaHttp(SPARQLProtocolSession.java:834)
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.getBackgroundTupleQueryResult(SPARQLProtocolSession.java:720)
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.sendTupleQuery(SPARQLProtocolSession.java:381)
	at org.eclipse.rdf4j.repository.sparql.query.SPARQLTupleQuery.evaluate(SPARQLTupleQuery.java:43)
	... 1 more

```

Sample Code:
```
Repository repo = new SPARQLRepository(sparqlEndpoint);
repo.initialize();
try(RepositoryConnection conn = repo.getConnection()){
    TupleQuery query = conn.prepareTupleQuery(QueryLanguage.SPARQL,
        "PREFIX : <http://example.org/>"
        + " CONSTRUCT {"
        + " :myThing :linksToASubject ?s ."
        + " :myThing :linksToAPredicate ?p ."
        + " :myThing :linksToAObject ?o ."
        + " } WHERE { SELECT  ?s ?p ?o WHERE { ?s  ?p  ?o } LIMIT 1 }");
    query.setMaxExecutionTime(0);
    try(TupleQueryResult result = query.evaluate()){
        while(result.hasNext()) {
            BindingSet bindingSet = result.next();
            System.out.println(bindingSet);
        }
    };
};
repo.shutDown();
```

**Comment by jeenbroekstra** [comment]
A CONSTRUCT-query is not a `TupleQuery`, but a `GraphQuery`. So you need to use `GraphQuery query = conn.prepareGraphQuery` instead. See [the section on querying](http://docs.rdf4j.org/programming/#_querying_a_repository) in [Programming with RDF4J](http://docs.rdf4j.org/programming/) for more details.
