### ISSUE TITLE
[Rio fatal] Not a valid (absolute) IRI

### ISSUE THREAD

**Issue by archenroot** [eclipse/rdf4j#988]
Hi guys,

first of all thanks for this library. We just started adoption of new input data format RDFXML. I tried to do simple test to parse the model, and got this error:
```
[main] ERROR org.eclipse.rdf4j.rio.helpers.ParseErrorLogger - [Rio fatal] Not a valid (absolute) IRI: #_7d2bcaf9-c831-44fd-b6a3-2fb888564f08 (18, 102)
Exception in thread "main" org.eclipse.rdf4j.rio.RDFParseException: Not a valid (absolute) IRI: #_7d2bcaf9-c831-44fd-b6a3-2fb888564f08 [line 18, column 102]
	at org.eclipse.rdf4j.rio.helpers.RDFParserHelper.reportFatalError(RDFParserHelper.java:442)
	at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.reportFatalError(AbstractRDFParser.java:712)
	at org.eclipse.rdf4j.rio.rdfxml.RDFXMLParser.reportFatalError(RDFXMLParser.java:1281)
	at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.createURI(AbstractRDFParser.java:407)
	at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.resolveURI(AbstractRDFParser.java:394)
	at org.eclipse.rdf4j.rio.rdfxml.RDFXMLParser.buildURIFromID(RDFXMLParser.java:985)
	at org.eclipse.rdf4j.rio.rdfxml.RDFXMLParser.getNodeResource(RDFXMLParser.java:688)
	at org.eclipse.rdf4j.rio.rdfxml.RDFXMLParser.processNodeElt(RDFXMLParser.java:587)
	at org.eclipse.rdf4j.rio.rdfxml.RDFXMLParser.startElement(RDFXMLParser.java:493)
	at org.eclipse.rdf4j.rio.rdfxml.SAXFilter.reportDeferredStartElement(SAXFilter.java:326)
	at org.eclipse.rdf4j.rio.rdfxml.SAXFilter.startElement(SAXFilter.java:249)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:351)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.eclipse.rdf4j.rio.rdfxml.RDFXMLParser.parse(RDFXMLParser.java:327)
	at org.eclipse.rdf4j.rio.rdfxml.RDFXMLParser.parse(RDFXMLParser.java:206)
	at org.eclipse.rdf4j.rio.Rio.parse(Rio.java:256)
	at org.eclipse.rdf4j.rio.Rio.parse(Rio.java:182)
	at RdfProcessor.parse(RdfProcessor.java:36)
	at Main.main(Main.java:4)
Caused by: java.lang.IllegalArgumentException: Not a valid (absolute) IRI: #_11
	at org.eclipse.rdf4j.model.impl.SimpleIRI.setIRIString(SimpleIRI.java:76)
	at org.eclipse.rdf4j.model.impl.SimpleIRI.<init>(SimpleIRI.java:65)
	at org.eclipse.rdf4j.model.impl.AbstractValueFactory.createIRI(AbstractValueFactory.java:88)
	at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.createURI(AbstractRDFParser.java:404)
	... 25 more
```

Here is sample file I played with:
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with PowerFactory 16.0.5 (digcimdb.dll ServicePack 0) -->
<rdf:RDF xmlns:cim="http://iec.ch/TC57/2013/CIM-schema-cim16#"
         xmlns:entsoe="http://entsoe.eu/CIM/SchemaExtension/3/1#"
         xmlns:md="http://iec.ch/TC57/61970-552/ModelDescription/1#"
         xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <cim:EquivalentBranch rdf:ID="_11">
        <cim:ConductingEquipment.BaseVoltage rdf:resource="#_22" />
        <cim:EquivalentBranch.negativeR12>0.</cim:EquivalentBranch.negativeR12>
        <cim:EquivalentBranch.negativeR21>0.</cim:EquivalentBranch.negativeR21>
        <cim:EquivalentBranch.negativeX12>0.</cim:EquivalentBranch.negativeX12>
        <cim:EquivalentBranch.negativeX21>0.</cim:EquivalentBranch.negativeX21>
        <cim:EquivalentBranch.positiveR12>4.08827</cim:EquivalentBranch.positiveR12>
        <cim:EquivalentBranch.positiveR21>4.03348</cim:EquivalentBranch.positiveR21>
        <cim:EquivalentBranch.positiveX12>75.3228</cim:EquivalentBranch.positiveX12>
        <cim:EquivalentBranch.positiveX21>75.316</cim:EquivalentBranch.positiveX21>
        <cim:EquivalentBranch.r>4.08827</cim:EquivalentBranch.r>
        <cim:EquivalentBranch.r21>4.03348</cim:EquivalentBranch.r21>
        <cim:EquivalentBranch.x>75.3228</cim:EquivalentBranch.x>
        <cim:EquivalentBranch.x21>75.316</cim:EquivalentBranch.x21>
        <cim:EquivalentBranch.zeroR12>0.</cim:EquivalentBranch.zeroR12>
        <cim:EquivalentBranch.zeroR21>0.</cim:EquivalentBranch.zeroR21>
        <cim:EquivalentBranch.zeroX12>0.</cim:EquivalentBranch.zeroX12>
        <cim:EquivalentBranch.zeroX21>0.</cim:EquivalentBranch.zeroX21>
        <cim:IdentifiedObject.name>eqZpu-34-57</cim:IdentifiedObject.name>
    </cim:EquivalentBranch>
    <cim:EquivalentBranch rdf:ID="_33">
        <cim:ConductingEquipment.BaseVoltage rdf:resource="#_22" />
        <cim:EquivalentBranch.negativeR12>0.</cim:EquivalentBranch.negativeR12>
        <cim:EquivalentBranch.negativeR21>0.</cim:EquivalentBranch.negativeR21>
        <cim:EquivalentBranch.negativeX12>0.</cim:EquivalentBranch.negativeX12>
        <cim:EquivalentBranch.negativeX21>0.</cim:EquivalentBranch.negativeX21>
        <cim:EquivalentBranch.positiveR12>14517.3</cim:EquivalentBranch.positiveR12>
        <cim:EquivalentBranch.positiveR21>14616.2</cim:EquivalentBranch.positiveR21>
        <cim:EquivalentBranch.positiveX12>8351.35</cim:EquivalentBranch.positiveX12>
        <cim:EquivalentBranch.positiveX21>7091.53</cim:EquivalentBranch.positiveX21>
        <cim:EquivalentBranch.r>14517.3</cim:EquivalentBranch.r>
        <cim:EquivalentBranch.r21>14616.2</cim:EquivalentBranch.r21>
        <cim:EquivalentBranch.x>8351.35</cim:EquivalentBranch.x>
        <cim:EquivalentBranch.x21>7091.53</cim:EquivalentBranch.x21>
        <cim:EquivalentBranch.zeroR12>0.</cim:EquivalentBranch.zeroR12>
        <cim:EquivalentBranch.zeroR21>0.</cim:EquivalentBranch.zeroR21>
        <cim:EquivalentBranch.zeroX12>0.</cim:EquivalentBranch.zeroX12>
        <cim:EquivalentBranch.zeroX21>0.</cim:EquivalentBranch.zeroX21>
        <cim:IdentifiedObject.name>eqZpu-112-295</cim:IdentifiedObject.name>
    </cim:EquivalentBranch>
</rdf:RDF>
```

Thanks for any suggestions, also these IDs in the file are defined by provider, we shouldn't change those.

**Comment by jamesrdf** [comment]
This is better addressed on the mailing list, but it looks like the base IRI is not available.

**Comment by archenroot** [comment]
I will just add update, it works from RDFlib in python. Only Java implementation has this problem, so it looks as core bug from my perspective.
